### ISSUE TITLE
nekpoi eror sama stickergif

### ISSUE THREAD

**Issue by MSI0072** [ArugaZ/whatsapp-bot#10]
![image](https://user-images.githubusercontent.com/63404067/98072392-862eac00-1e98-11eb-83ce-320a22eb1a5c.png)
![image](https://user-images.githubusercontent.com/63404067/98072420-92b30480-1e98-11eb-9040-da1927aa007e.png)

**Comment by ArugaZ** [comment]
nekopoi kadang kena re-captcha

**Comment by ArugaZ** [comment]
nt ane update yg gif nya
