### ISSUE TITLE
[SARAN] fitur stikerteks

### ISSUE THREAD

**Issue by selyxn** [ArugaZ/whatsapp-bot#103]
Tambahin fitur stiker teks gan

Contoh: #stikerteks Gua bagian "wkwk" aja dah

maka outputnya seperti ini
![IMG_20201127_200927](https://user-images.githubusercontent.com/69533502/100452820-79465680-30ec-11eb-84df-f680d2e44f26.jpg)

**Comment by Tanaka9531** [comment]
> Tambahin fitur stiker teks gan
> 
> Contoh: #stikerteks Gua bagian "wkwk" aja dah
> 
> maka outputnya seperti ini
> ![IMG_20201127_200927](https://user-images.githubusercontent.com/69533502/100452820-79465680-30ec-11eb-84df-f680d2e44f26.jpg)

minta linknya plis :)

**Comment by selyxn** [comment]
> > Tambahin fitur stiker teks gan
> > Contoh: #stikerteks Gua bagian "wkwk" aja dah
> > maka outputnya seperti ini
> > ![IMG_20201127_200927](https://user-images.githubusercontent.com/69533502/100452820-79465680-30ec-11eb-84df-f680d2e44f26.jpg)
> 
> minta linknya plis :)

Link apa

**Comment by Tanaka9531** [comment]
> > > Tambahin fitur stiker teks gan
> > > Contoh: #stikerteks Gua bagian "wkwk" aja dah
> > > maka outputnya seperti ini
> > > ![IMG_20201127_200927](https://user-images.githubusercontent.com/69533502/100452820-79465680-30ec-11eb-84df-f680d2e44f26.jpg)
> > 
> > 
> > minta linknya plis :)
> 
> Link apa

https://github.com/ArugaZ/whatsapp-bot/issues/150
