### ISSUE TITLE
req fitur !afk gw dh coba mlh [EROR] TypeError: Cannot read property 'slice' of undefined 

### ISSUE THREAD

**Issue by Fucksociety666** [ArugaZ/whatsapp-bot#105]
[ttp + afk.zip](https://github.com/ArugaZ/whatsapp-bot/files/5608238/ttp.%2B.afk.zip)

**Comment by ArugaZ** [comment]
oke nt saya coba masukin

**Comment by Fucksociety666** [comment]
> oke nt saya coba masukin

ditunggu ngab

**Comment by ArugaZ** [comment]
> > oke nt saya coba masukin
> 
> ditunggu ngab

sippp

**Comment by ArugaZ** [comment]
> > oke nt saya coba masukin
> 
> ditunggu ngab

pake xampp mysql?

**Comment by ArugaZ** [comment]
> > oke nt saya coba masukin
> 
> ditunggu ngab

ane publish apa gmn? di saya bisa ini

**Comment by Fucksociety666** [comment]
> > > oke nt saya coba masukin
> > 
> > 
> > ditunggu ngab
> 
> ane publish apa gmn? di saya bisa ini

`kalo bisa jangan di publish dlu ngab susah cari scnya soalnya heehe

**Comment by Fucksociety666** [comment]
> > > oke nt saya coba masukin
> > 
> > 
> > ditunggu ngab
> 
> pake xampp mysql?

pke. gw kira bakal lama ngab,  tau2 bngun tidur udh selesai di kekrjain mntp dah,,, mana ngab gk sabar pke whhwhe

**Comment by Fucksociety666** [comment]
> > > oke nt saya coba masukin
> > 
> > 
> > ditunggu ngab
> 
> ane publish apa gmn? di saya bisa ini

mn ngab? gk sbr pke

**Comment by ArugaZ** [comment]
> > > > oke nt saya coba masukin
> > > 
> > > 
> > > ditunggu ngab
> > 
> > 
> > ane publish apa gmn? di saya bisa ini
> 
> mn ngab? gk sbr pke

chat wa aja di readme ada nomornya
