### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by ShinzX** [ArugaZ/whatsapp-bot#111]
![IMG_20201128_173159](https://user-images.githubusercontent.com/74783040/100507314-ec5cd500-319f-11eb-9589-c1be92a6e86a.jpg)

Req Fitur welcome nya di tambahin foto profil

**Comment by ArugaZ** [comment]
done ya

**Comment by ShinzX** [comment]
> done ya

Mantappp makasih gan
