### ISSUE TITLE
request fitur

### ISSUE THREAD

**Issue by akujeleksad** [ArugaZ/whatsapp-bot#112]
Gw request boleh ga bang?
#astik auto sticker jadi ada yang ngirim gambar langsung jadi stiker
#caklontong tebak tebakan
#Premium
dll

**Comment by ArugaZ** [comment]
> Gw request boleh ga bang?
> #astik auto sticker jadi ada yang ngirim gambar langsung jadi stiker
> #caklontong tebak tebakan
> #Premium
> dll

itu butuh api-key

**Comment by ArugaZ** [comment]
> Gw request boleh ga bang?
> #astik auto sticker jadi ada yang ngirim gambar langsung jadi stiker
> #caklontong tebak tebakan
> #Premium
> dll

atau nanti saya buat yang command premium?

**Comment by akujeleksad** [comment]
boleh bang jaki bisa buat apikey caklontong ama astik

**Comment by ArugaZ** [comment]
> boleh bang jaki bisa buat apikey caklontong ama astik

chat wa saya aja, ada di README.md

**Comment by akujeleksad** [comment]
ga dijawab jawab bang wa.me/6281395771492
tuhbang chat saya

**Comment by akujeleksad** [comment]
nomer abang brp

**Comment by ArugaZ** [comment]
+44 7451 244769

**Comment by akujeleksad** [comment]
ane udh chat abang ga di respon

**Comment by akujeleksad** [comment]
udh ane spam malah

**Comment by Fucksociety666** [comment]
> +44 7451 244769

sm njerr
