### ISSUE TITLE
request fitur

### ISSUE THREAD

**Issue by selyxn** [ArugaZ/whatsapp-bot#114]
saya request fitur cekzodiak dong gan, daritadi udah nyoba error mulu :(

**Comment by selyxn** [comment]
ane req gapernah di respon :(

**Comment by ArugaZ** [comment]
tambahin aja pake kan udh ada di rest api

**Comment by ArugaZ** [comment]
https://arugaz.herokuapp.com/api/getzodiak?nama=aruga&tgl-bln-thn=17-10-2003

**Comment by selyxn** [comment]
> tambahin aja pake kan udh ada di rest api

Iye gan, udah nyoba-nyoba dari sore, masih try & error :(

**Comment by EnzyyF** [comment]
> https://arugaz.herokuapp.com/api/getzodiak?nama=aruga&tgl-bln-thn=17-10-2003

itu nambahin nya dimana gan?
