### ISSUE TITLE
req

### ISSUE THREAD

**Issue by MrPawNO** [ArugaZ/whatsapp-bot#116]
Add fitur disabe/enable pesan welcome group (Admin only)

**Comment by idkmew** [comment]
bang, req dong, fitur send link auto kick yg bisa di set enable atau disable(bisa req ban words juga)hehe , biar joss tu

**Comment by Fucksociety666** [comment]
> Add fitur disabe/enable pesan welcome group (Admin only)

tingga; ambil d sci mhank bar bar :V
