### ISSUE TITLE
Eror Di Linux Khususnya Ubuntu

### ISSUE THREAD

**Issue by habibhantam445** [ArugaZ/whatsapp-bot#12]
Gw dah Install chromium Ttp Stuck Waktu Install Nya Brow

**Comment by mioscape** [comment]
Lancar di manjaro :D

**Comment by habibhantam445** [comment]
Tutorial Coba,Gw Di Ubuntu Gabisa Brow

Pada tanggal Sab, 7 Nov 2020 08.09, Mioscape <notifications@github.com>
menulis:

**Comment by Rimuru9531** [comment]
Bang Mau Nanya Itu Menu Ceklokasi Kok Gak Mau
