### ISSUE TITLE
bantu ngab

### ISSUE THREAD

**Issue by MrPawNO** [ArugaZ/whatsapp-bot#121]
[cekzodiak.zip](https://github.com/ArugaZ/whatsapp-bot/files/5611683/cekzodiak.zip)

![IMG_20201129_121219](https://user-images.githubusercontent.com/13583912/100533912-57f48000-323c-11eb-97b4-875a5f7a9209.jpg)

**Comment by ArugaZ** [comment]
nt ane update aja
