### ISSUE TITLE
Bang Mau nanya

### ISSUE THREAD

**Issue by akujeleksad** [ArugaZ/whatsapp-bot#122]
cara hapus welcome group gtu gmn bang
kaya hello welcome with us

**Comment by akujeleksad** [comment]
g direspon :(

**Comment by selyxn** [comment]
> cara hapus welcome group gtu gmn bang
> kaya hello welcome with us

Buka file index.js

Hapus //ketika boot diinvite ke dalam grup, sisakan //kondisi ketika batas group bot telah tercapai

**Comment by MrPawNO** [comment]
> cara hapus welcome group gtu gmn bang
> kaya hello welcome with us

Buka file index.js

Hapus //ketika boot diinvite ke dalam grup, sisakan //kondisi ketika batas group bot telah tercapai

**Comment by Fucksociety666** [comment]
> > cara hapus welcome group gtu gmn bang
> > kaya hello welcome with us
> 
> Buka file index.js
> 
> Hapus //ketika seseorang masuk/keluar dari grup, sisakan // kondisi ketika seseorang dikick/keluar dari group

ini Mr.pawno asli kan? mau join gc attacker blh minta wa g

**Comment by Fucksociety666** [comment]
> > cara hapus welcome group gtu gmn bang
> > kaya hello welcome with us
> 
> Buka file index.js
> 
> Hapus //ketika seseorang masuk/keluar dari grup, sisakan // kondisi ketika seseorang dikick/keluar dari group

temanya lion kan ngab :V

**Comment by selyxn** [comment]
> > > cara hapus welcome group gtu gmn bang
> > > kaya hello welcome with us
> > 
> > 
> > Buka file index.js
> > Hapus //ketika seseorang masuk/keluar dari grup, sisakan // kondisi ketika seseorang dikick/keluar dari group
> 
> ini Mr.pawno asli kan? mau join gc attacker blh minta wa g

Asli dong, gamain attack2er gan

**Comment by MrPawNO** [comment]
> > > cara hapus welcome group gtu gmn bang
> > > kaya hello welcome with us
> > 
> > 
> > Buka file index.js
> > Hapus //ketika seseorang masuk/keluar dari grup, sisakan // kondisi ketika seseorang dikick/keluar dari group
> 
> ini Mr.pawno asli kan? mau join gc attacker blh minta wa g

asli, gamain attacker2an

**Comment by Fucksociety666** [comment]
> > > > cara hapus welcome group gtu gmn bang
> > > > kaya hello welcome with us
> > > 
> > > 
> > > Buka file index.js
> > > Hapus //ketika seseorang masuk/keluar dari grup, sisakan // kondisi ketika seseorang dikick/keluar dari group
> > 
> > 
> > ini Mr.pawno asli kan? mau join gc attacker blh minta wa g
> 
> asli, gamain attacker2an
owh dh pensiun ya bg ,, bagi link gc donk bg mau join ane
