### ISSUE TITLE
Bang Ini Kenapa ya maaf

### ISSUE THREAD

**Issue by MulqiGaming64** [ArugaZ/whatsapp-bot#123]
Pas !ytmp3 Link sama !ytmp4 Link Di Console ad tulisan

(node:142113) UnhandledPromiseRejectionWarning: Error: Reque
st failed with status code 404
    at createError (/root/whatsapp-bot-2.1.0/node_modules/ax
ios/lib/core/createError.js:16:15)
    at settle (/root/whatsapp-bot-2.1.0/node_modules/axios/l
ib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/root/whatsapp-bot-2
.1.0/node_modules/axios/lib/adapters/http.js:244:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queu
es.js:84:21)
(node:142113) UnhandledPromiseRejectionWarning: Unhandled pr
omise rejection. This error originated either by throwing in
side of an async function without a catch block, or by rejec
ting a promise which was not handled with .catch(). To termi
nate the node process on unhandled promise rejection, use th
e CLI flag `--unhandled-rejections=strict` (see https://node
js.org/api/cli.html#cli_unhandled_rejections_mode). (rejecti
on id: 2)
(node:142113) [DEP0018] DeprecationWarning: Unhandled promis
e rejections are deprecated. In the future, promise rejectio
ns that are not handled will terminate the Node.js process w
ith a non-zero exit code.

kalo bisa di fix kalo enggak gak papa sih soalnya kan gratis :)

**Comment by ArugaZ** [comment]
tambahin .catch buat nge handle error nya

**Comment by MulqiGaming64** [comment]
udah kak sekarang jadi gini

(node:182151) UnhandledPromiseRejectionWarning: Error: Reque
st failed with status code 503
    at createError (/root/whatsapp-bot-2.1.0/node_modules/ax
ios/lib/core/createError.js:16:15)
    at settle (/root/whatsapp-bot-2.1.0/node_modules/axios/l
ib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/root/whatsapp-bot-2
.1.0/node_modules/axios/lib/adapters/http.js:244:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queu
es.js:84:21)
(node:182151) UnhandledPromiseRejectionWarning: Unhandled pr
omise rejection. This error originated either by throwing in
side of an async function without a catch block, or by rejec
ting a promise which was not handled with .catch(). To termi
nate the node process on unhandled promise rejection, use th
e CLI flag `--unhandled-rejections=strict` (see https://node
js.org/api/cli.html#cli_unhandled_rejections_mode). (rejecti
on id: 2)
(node:182151) [DEP0018] DeprecationWarning: Unhandled promis
e rejections are deprecated. In the future, promise rejectio
ns that are not handled will terminate the Node.js process w
ith a non-zero exit code.
