### ISSUE TITLE
request-feature: AFK

### ISSUE THREAD

**Issue by mioscape** [ArugaZ/whatsapp-bot#126]
Activation `${prefix}afk`
![image](https://user-images.githubusercontent.com/43681888/100547279-856f1700-3298-11eb-9e79-7227e037b01f.png)

Deactivation (Mengirim Chat apa aja akan membatalkan AFK)
![image](https://user-images.githubusercontent.com/43681888/100547305-a5063f80-3298-11eb-839b-43483fffdb28.png)

**Comment by ArugaZ** [comment]
ada yg jual fitur itu, kl saya buat jd free takut genak

**Comment by madamdroid** [comment]
> ada yg jual fitur itu, kl saya buat jd free takut genak

bang # nulis tolong diperbaiki

**Comment by akujeleksad** [comment]
iya nulis ga bisa

**Comment by mioscape** [comment]
> ada yg jual fitur itu, kl saya buat jd free takut genak

Oh iyakah? yaudah saya close aja
