### ISSUE TITLE
Fitur Ban Seluruh Member Grup

### ISSUE THREAD

**Issue by dedekganteng** [ArugaZ/whatsapp-bot#127]
Apakah memungkinkan untuk fitur ban seluruh member?
Untuk jaga-jaga semisal ada yang abuse, bukan cuma ban nomor hp, tapi seluruh grup member dimana bot berada

**Comment by ArugaZ** [comment]
ketik #ban @tag @tag

**Comment by ArugaZ** [comment]
kl lgsg semua blm sata buat
