### ISSUE TITLE
EROR WELCOME MESSAGE

### ISSUE THREAD

**Issue by MSI0072** [ArugaZ/whatsapp-bot#128]
Welcome Message sering muncul sendiri padahal tidak ada yang join kedalam grub

![image](https://user-images.githubusercontent.com/63404067/100559997-0228e200-32e7-11eb-9d34-358406f812d7.png)

**Comment by akujeleksad** [comment]
nnah mangkanya gw off in Tu fitur welcome Gmn tuh bang?

**Comment by MrPawNO** [comment]
> Welcome Message sering muncul sendiri padahal tidak ada yang join kedalam grub
> 
> ![image](https://user-images.githubusercontent.com/63404067/100559997-0228e200-32e7-11eb-9d34-358406f812d7.png)

Iya itu biasanya terjadi karena kita habis clear chat, di whatsapp terdeteksi "blablabla telah ditambahkan", saran gua mending nonaktifkan aja fitur welcome nya, di index.js

**Comment by ArugaZ** [comment]
nah eta
