### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bagusdwip** [ArugaZ/whatsapp-bot#13]
Fiture 
download
Nulis
Play
Maintenance?

**Comment by ArugaZ** [comment]
> Fiture
> download
> Nulis
> Play
> Maintenance?

**Comment by ArugaZ** [comment]
> > Fiture
> > download
> > Nulis
> > Play
> > Maintenance?

blm cek heroku lg, ntr sy cek

**Comment by ArugaZ** [comment]
> Fiture
> download
> Nulis
> Play
> Maintenance?
done ya
