### ISSUE TITLE
Fitur yang eror semenjak update

### ISSUE THREAD

**Issue by akujeleksad** [ArugaZ/whatsapp-bot#130]
#nulis
#igstalk
#lirik
#sgif
#ytmp3
#ytmp4
#resep
dll abang cek cekin aja

**Comment by nobar123** [comment]
Iya,gua malahan error request trus
![Screenshot_2020-11-30-12-34-57-06](https://user-images.githubusercontent.com/75187306/100572894-2ac1d380-3309-11eb-9a64-ef7eeefbd0e6.png)

**Comment by akujeleksad** [comment]
lagi maintenance
