### ISSUE TITLE
Ini kok eror ya

### ISSUE THREAD

**Issue by nobar123** [ArugaZ/whatsapp-bot#131]
![Screenshot_2020-11-30-12-34-57-06](https://user-images.githubusercontent.com/75187306/100572709-c0109800-3308-11eb-9228-f17714c74781.png)

Kok gitu trus ,nyepam lagi
Eror : request failed whit status code 503

**Comment by setyawan12** [comment]
> ![Screenshot_2020-11-30-12-34-57-06](https://user-images.githubusercontent.com/75187306/100572709-c0109800-3308-11eb-9228-f17714c74781.png)
> 
> Kok gitu trus ,nyepam lagi
> Eror : request failed whit status code 503

lagi maintenance apinya.

**Comment by nobar123** [comment]
Oh ok thanks 😀
Kalau boleh tahu sampe kapan maintenance nya ?
