### ISSUE TITLE
#error_nekopoi

### ISSUE THREAD

**Issue by egmu** [ArugaZ/whatsapp-bot#135]
udh conect vpn, tp not work

**Comment by MSI0072** [comment]
> udh conect vpn, tp not work

ada rechaptanya

**Comment by egmu** [comment]
> 
> 
> > udh conect vpn, tp not work
> 
> ada rechaptanya

cra lewati?

**Comment by ArugaZ** [comment]
work kok ngab, ane liat di beberapa bot org jalan
