### ISSUE TITLE
cara fixnya gmn ??

### ISSUE THREAD

**Issue by MrZinAG** [ArugaZ/whatsapp-bot#136]
![Cuplikan layar dari 2020-12-01 14-08-25](https://user-images.githubusercontent.com/75297899/100708348-b48fa080-33de-11eb-968c-04aa605d418d.png)
[EROR] TypeError: Cannot read property 'slice' of undefined
    at HandleMsg (/home/fsociety/BOT/whatsapp-bot/HandleMsg.js:101:22)
    at runMicrotasks (<anonymous>)
![Cuplikan layar dari 2020-12-01 13-42-08](https://user-images.githubusercontent.com/75297899/100707431-3c74ab00-33dd-11eb-8448-131786203607.png)

**Comment by ArugaZ** [comment]
nanti saya fix, bntr ya
