### ISSUE TITLE
Bang Aku Mau Minta Tolong 

### ISSUE THREAD

**Issue by Tanaka9531** [ArugaZ/whatsapp-bot#137]
Cara Tambahain Fitur ini Gimana yah ini Api Nya
Yang tau kasi Tau Yah... Plis

https://api.haipbis.xyz/randomcooltext?text=aruga

Makasih

**Comment by ArugaZ** [comment]
nt ane buat direst api ane

**Comment by ArugaZ** [comment]
sekalian update di github ini

**Comment by Tanaka9531** [comment]
> sekalian update di github ini

Aku Tunggu updatenya

**Comment by Tanaka9531** [comment]
Bang Gimana Cara Nya Tambahin Menu Spamer Itu

**Comment by ArugaZ** [comment]
pakai fungsi for loop

**Comment by Tanaka9531** [comment]
> pakai fungsi for loop

gimana bang aku pemula :)

untuk sementara pake api dari sini dulu bang  
https://alfians-api.herokuapp.com/api/ytv?url=https://youtu.be/6l5V3BWDcMw
https://alfians-api.herokuapp.com/api/yta?url=https://youtu.be/6l5V3BWDcMw

**Comment by MrPawNO** [comment]
> > pakai fungsi for loop
> 
> itu apa bang aku baru pemula:)
> 
> untuk sementara pake api dari sini dulu bang
> https://alfians-api.herokuapp.com/api/ytv?url=https://youtu.be/6l5V3BWDcMw
> https://alfians-api.herokuapp.com/api/yta?url=https://youtu.be/6l5V3BWDcMw

Gua udah nyoba dari api itu, result link nya ga langsung ngarah ke tombol download, malah page ytmp3, alhasil bot malah ngirim null.html yang seharusnya ekstensi mp3 kalo langsung ngarah ke tombol download
Ada web api lain ga?

**Comment by Tanaka9531** [comment]
bang tambahin fitur kurs dong pls

**Comment by MrPawNO** [comment]
> bang tambahin fitur kurs dong pls dan google search

OOT, diharapkan untuk meng-close issue ini, terimakasih.
