### ISSUE TITLE
Problem saat pakai PLAY

### ISSUE THREAD

**Issue by Falentio** [ArugaZ/whatsapp-bot#138]
tidak ada musik yang dikirim
hanya data musik

**Comment by ArugaZ** [comment]
kamu tidak mau menerima cintaku, aku tidak mau membantu

**Comment by ArugaZ** [comment]
ntr gua update njeng gay kau fer

**Comment by Fucksociety666** [comment]
> ntr gua update njeng gay kau fer

afk + beli comand premium

**Comment by ShinzX** [comment]
> ntr gua update njeng gay kau fer

Ytmp3 juga eror gan :v

**Comment by ArugaZ** [comment]
fitur youtube lgi error dari rest api nya
