### ISSUE TITLE
REQUST / REPORT BUG

### ISSUE THREAD

**Issue by ArugaZ** [ArugaZ/whatsapp-bot#14]

**Comment by mioscape** [comment]
Siap, santai aja bang :D

**Comment by Cahyo224** [comment]
oke mhank istirahat ae dulu

**Comment by ArugaZ** [comment]
bantu contribusi aja gan wkk nt tak lihat

**Comment by riintan2** [comment]
bang @ArugaZ  instagram [link] gak connect

**Comment by riintan2** [comment]
dengan bug welcome dan member yang out,ngespam

**Comment by ArugaZ** [comment]
> bang @ArugaZ instagram [link] gak connect

Instagram emg gabs? nt saya cek rest api nya

**Comment by ArugaZ** [comment]
> dengan bug welcome dan member yang out,ngespam

dari open-wa nya kl itu gan nt ane update ke module yang baru

**Comment by mioscape** [comment]
Kenapa open-wa nya ndak di update ke versi terbaru ya?

**Comment by ArugaZ** [comment]
> Kenapa open-wa nya ndak di update ke versi terbaru ya?

ntr ane build ulang sekalian rapihin

**Comment by mioscape** [comment]
> > Kenapa open-wa nya ndak di update ke versi terbaru ya?
> 
> ntr ane build ulang sekalian rapihin

Asiap

**Comment by shinz404** [comment]
Cara matiin fitur anti spam gimana ? Kasian orang pada ngeluh ga di bales :v

**Comment by ArugaZ** [comment]
> > > Kenapa open-wa nya ndak di update ke versi terbaru ya?
> > 
> > 
> > ntr ane build ulang sekalian rapihin
> 
> Asiap

sip 🐤 

> Cara matiin fitur anti spam gimana ? Kasian orang pada ngeluh ga di bales :v

>>di file pada folder utils/index.js ubah 5000ms jadi brp dh seterah lu ✌️

**Comment by exaho** [comment]
Bro, yg pornhub gmn cara pakenya ya? Kok Premium terus?

**Comment by ArugaZ** [comment]
> Bro, yg pornhub gmn cara pakenya ya? Kok Premium terus?

clone ulang mang

**Comment by harieyadi** [comment]
Simsimi udah bisa blm bang

**Comment by Aryasatya12** [comment]
![ GOME_C7_Note_Plus_20201110_145435_0](https://user-images.githubusercontent.com/61396346/98645988-4dde1080-2365-11eb-99ed-c70abd8606f0.jpg)
Bang ini kenapa ya??

**Comment by mioscape** [comment]
> ![ GOME_C7_Note_Plus_20201110_145435_0](https://user-images.githubusercontent.com/61396346/98645988-4dde1080-2365-11eb-99ed-c70abd8606f0.jpg)
> Bang ini kenapa ya??

Habis ngubah apa?

**Comment by Aryasatya12** [comment]
> > ![ GOME_C7_Note_Plus_20201110_145435_0](https://user-images.githubusercontent.com/61396346/98645988-4dde1080-2365-11eb-99ed-c70abd8606f0.jpg)
> > Bang ini kenapa ya??
> 
> Habis ngubah apa?

Blum di ubah gan pas npm start malah eror

**Comment by ArugaZ** [comment]
> ![ GOME_C7_Note_Plus_20201110_145435_0](https://user-images.githubusercontent.com/61396346/98645988-4dde1080-2365-11eb-99ed-c70abd8606f0.jpg)
> Bang ini kenapa ya??

okeoke bntr

**Comment by ArugaZ** [comment]
kok klean pd gbisa module phub nya y hmmm

**Comment by bagusdwip** [comment]
Saran tambahin
Di Fiture play di saring dong kalo durasi lebih dari 30menit jangan dikirim biar ga error' di CMd nya trus stuck gajalan:(

**Comment by ArugaZ** [comment]
> Saran tambahin
> Di Fiture play di saring dong kalo durasi lebih dari 30menit jangan dikirim biar ga error' di CMd nya trus stuck gajalan:(

siaaap nt ane benerin

**Comment by arh-space** [comment]
Tolong tambahin fitur limit gan :(

**Comment by RzkyO** [comment]
tambahin fiture limit harian dong bro di tts sama di play, soalnya disitu sering error bro, pada sering" banget makenya sampe ngespam jadi nya ngestuck ga ke kirim" :(

**Comment by ArugaZ** [comment]
> tambahin fiture limit harian dong bro di tts sama di play, soalnya disitu sering error bro, pada sering" banget makenya sampe ngespam jadi nya ngestuck ga ke kirim" :(

hmm mungkin nt saya kasih filter di command play nya

**Comment by RzkyO** [comment]
> > tambahin fiture limit harian dong bro di tts sama di play, soalnya disitu sering error bro, pada sering" banget makenya sampe ngespam jadi nya ngestuck ga ke kirim" :(
> 
> hmm mungkin nt saya kasih filter di command play nya

ohh iya bang saran aja bang, tambahin fiture lirik lagu,kalo bisa :D

**Comment by iksanriyanto** [comment]
![IMG_20201111_153200](https://user-images.githubusercontent.com/34216476/98788235-2b1a2d80-2433-11eb-9983-4046fac00dfe.jpg)
Bang ini yang nekopoi kenapa ya bgini hehe pdhal pengen make :v

**Comment by riintan2** [comment]
> ![IMG_20201111_153200](https://user-images.githubusercontent.com/34216476/98788235-2b1a2d80-2433-11eb-9983-4046fac00dfe.jpg)
> Bang ini yang nekopoi kenapa ya bgini hehe pdhal pengen make :v

tobat om

**Comment by iksanriyanto** [comment]
> > ![IMG_20201111_153200](https://user-images.githubusercontent.com/34216476/98788235-2b1a2d80-2433-11eb-9983-4046fac00dfe.jpg)
> > Bang ini yang nekopoi kenapa ya bgini hehe pdhal pengen make :v
> 
> tobat om

Penasaran aja kenapa bisa error+buat fun aja sih sama anak grup wkwk

**Comment by ArugaZ** [comment]
> > > ![IMG_20201111_153200](https://user-images.githubusercontent.com/34216476/98788235-2b1a2d80-2433-11eb-9983-4046fac00dfe.jpg)
> > > Bang ini yang nekopoi kenapa ya bgini hehe pdhal pengen make :v
> > 
> > 
> > tobat om
> 
> Penasaran aja kenapa bisa error+buat fun aja sih sama anak grup wkwk



> > > ![IMG_20201111_153200](https://user-images.githubusercontent.com/34216476/98788235-2b1a2d80-2433-11eb-9983-4046fac00dfe.jpg)
> > > Bang ini yang nekopoi kenapa ya bgini hehe pdhal pengen make :v
> > 
> > 
> > tobat om
> 
> Penasaran aja kenapa bisa error+buat fun aja sih sama anak grup wkwk

pas itu sih kena recaptha

**Comment by ArugaZ** [comment]
ane blm coba lg

**Comment by RzkyO** [comment]
> ![IMG_20201111_153200](https://user-images.githubusercontent.com/34216476/98788235-2b1a2d80-2433-11eb-9983-4046fac00dfe.jpg)
> Bang ini yang nekopoi kenapa ya bgini hehe pdhal pengen make :v

Sama bro, entah kenapa nekopoi gabisa, jadinya gua ilangin aja deh dari menu botnya

**Comment by iksanriyanto** [comment]
> > > > ![IMG_20201111_153200](https://user-images.githubusercontent.com/34216476/98788235-2b1a2d80-2433-11eb-9983-4046fac00dfe.jpg)
> > > > Bang ini yang nekopoi kenapa ya bgini hehe pdhal pengen make :v
> > > 
> > > 
> > > tobat om
> > 
> > 
> > Penasaran aja kenapa bisa error+buat fun aja sih sama anak grup wkwk
> 
> > > > ![IMG_20201111_153200](https://user-images.githubusercontent.com/34216476/98788235-2b1a2d80-2433-11eb-9983-4046fac00dfe.jpg)
> > > > Bang ini yang nekopoi kenapa ya bgini hehe pdhal pengen make :v
> > > 
> > > 
> > > tobat om
> > 
> > 
> > Penasaran aja kenapa bisa error+buat fun aja sih sama anak grup wkwk
> 
> pas itu sih kena recaptha

Owh bgitu ya bang ,ane mudeng klo ada yg error gtu ga ngerti coding haha...bot nya keren dah, sukses trus bang biar makin banyak fitur kece🤣

**Comment by ArugaZ** [comment]
> Saran tambahin
> Di Fiture play di saring dong kalo durasi lebih dari 30menit jangan dikirim biar ga error' di CMd nya trus stuck gajalan:(

DONE!! untuk ubah filesize ganti di file dalam folder lib/rugaApi.js, disitu ada ukuran file nya

**Comment by alvinope** [comment]
BANG KASI FITUR TTP :)

**Comment by mioscape** [comment]
> BANG KASI FITUR TTP :)

TTP tuh apa?

**Comment by Aryasatya12** [comment]
> > BANG KASI FITUR TTP :)
> 
> TTP tuh apa?
> Tanda tangan palsu?😂

Itu loh gan, text ke sticker 🤣 klo ngetik text langsung jadi stiker gitu

**Comment by ArugaZ** [comment]
> > BANG KASI FITUR TTP :)
> 
> TTP tuh apa?
> Tanda tangan palsu?😂

text to png, tp di proses lgsg jd sticker

**Comment by Rimuru9531** [comment]
> recaptha

reCAPTCHA adalah layanan gratis dari Google yang membantu melindungi situs web dari spam dan penyalahgunaan. Sedangkan Captcha sendiri merupakan tes turing untuk membedakan manusia dan bot.

**Comment by mioscape** [comment]
> > recaptha
> 
> reCAPTCHA adalah layanan gratis dari Google yang membantu melindungi situs web dari spam dan penyalahgunaan. Sedangkan Captcha sendiri merupakan tes turing untuk membedakan manusia dan bot.

Sedikit kesel sama reCAPTCHA, tapi bagus buat ngelindungi web dari bot

**Comment by Rimuru9531** [comment]
Bang Kok Gini 
![bandicam 2020-11-12 08-54-22-119](https://user-images.githubusercontent.com/73052642/98885629-f48cf300-24c4-11eb-9315-a2cd316e48fb.jpg) Btw bang itu api kyk Di situs itu yah https://gardanasional.com/blog/menggunakan-api-cuaca maaf aku gak ngerti

**Comment by kokomif** [comment]
Kak yang 'nulis' error
![98886735-2f902600-24c7-11eb-9048-fd4a715c56ab](https://user-images.githubusercontent.com/74335565/98886832-55b5c600-24c7-11eb-800f-6b70431c9e26.png)
`axios.get(`${link}/nulis?text=${encodeURIComponent(url)}`)`

pas diganti jadi kode yang sebelumnya
`axios.get(`${link}/nulis?text=${teks}`)`

jadi bisa lagi.

**Comment by Rimuru9531** [comment]
> Kak yang 'nulis' error
> ![98886735-2f902600-24c7-11eb-9048-fd4a715c56ab](https://user-images.githubusercontent.com/74335565/98886832-55b5c600-24c7-11eb-800f-6b70431c9e26.png)
> `axios.get(`${link}/nulis?text=${encodeURIComponent(url)}`)`
> 
> pas diganti jadi kode yang sebelumnya
> `axios.get(`${link}/nulis?text=${teks}`)`
> 
> jadi bisa lagi.

Thx aku juga sama

**Comment by ArugaZ** [comment]
ohiya urlnya ganti jd teks

**Comment by ArugaZ** [comment]
> Bang Kok Gini
> ![bandicam 2020-11-12 08-54-22-119](https://user-images.githubusercontent.com/73052642/98885629-f48cf300-24c4-11eb-9315-a2cd316e48fb.jpg) Btw bang itu api kyk Di situs itu yah https://gardanasional.com/blog/menggunakan-api-cuaca maaf aku gak ngerti
> 
> Ini juga bang
> ![bandicam 2020-11-12 09-14-59-968](https://user-images.githubusercontent.com/73052642/98886966-99a8cb00-24c7-11eb-8b79-b98b0fcfaedb.jpg) https://kawalcorona.com/api/

udh gan typo ane

**Comment by Aryasatya12** [comment]
Bang tambahin fitur simsimi pakai api nya
https://st4rz.herokuapp.com/

**Comment by Rimuru9531** [comment]
> Bang tambahin fitur simsimi pakai api nya
> https://st4rz.herokuapp.com/

itu fitur apa

**Comment by Rimuru9531** [comment]
> > Bang Kok Gini
> > ![bandicam 2020-11-12 08-54-22-119](https://user-images.githubusercontent.com/73052642/98885629-f48cf300-24c4-11eb-9315-a2cd316e48fb.jpg) Btw bang itu api kyk Di situs itu yah https://gardanasional.com/blog/menggunakan-api-cuaca maaf aku gak ngerti
> > Ini juga bang
> > ![bandicam 2020-11-12 09-14-59-968](https://user-images.githubusercontent.com/73052642/98886966-99a8cb00-24c7-11eb-8b79-b98b0fcfaedb.jpg) https://kawalcorona.com/api/
> 
> udh gan typo ane

ini maksudnya udah bisa di pake lagi ?

**Comment by ArugaZ** [comment]
cuaca & nulis udh ane benerin typo nya

**Comment by Rimuru9531** [comment]
> cuaca & nulis udh ane benerin typo nya

Makasih Bang Itu wa bot fitur cek covid yang mana yah ?

**Comment by Rimuru9531** [comment]
> > cuaca & nulis udh ane benerin typo nya
> 
> Makasih Bang Itu wa bot fitur cek covid yang mana yah ?

emang gak ada atau . . . . .

**Comment by ArugaZ** [comment]
> > cuaca & nulis udh ane benerin typo nya
> 
> Makasih Bang Itu wa bot fitur cek covid yang mana yah ?

DONE! fixed

**Comment by RzkyO** [comment]
coba bang tambahin fiture lirik lagu nih bang api key nya https://api.i-tech.id/tools/lirik?key=37aERZ-jlUQ3W-HschH0-cxGozl-NzIHio&query=zona%20nyaman atau https://documenter.getpostman.com/view/10780576/T1Ds9bRV?version=latest#2e9b80b0-bbaf-43c5-881c-f7b483d07d0a

**Comment by MSI0072** [comment]
nggab fitur anti sticker error

error :
[EROR] ReferenceError: serial is not defined
at HandleMsg (D:\IT\BOT\BOT 5\whatsapp-bot\HandleMsg.js:271:34)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
