### ISSUE TITLE
Antilink

### ISSUE THREAD

**Issue by NaldoMota1** [ArugaZ/whatsapp-bot#143]
tambahkan opsi antilink dalam grup.

**Comment by mioscape** [comment]
If someone send link, automatically kicked out or what?

**Comment by MrPawNO** [comment]
> If someone send link, automatically kicked out or what?
/
Sama2 kek antilin di Arugaz, kalo terdeteksi link chat.whatsapp.com -> Auto kick

**Comment by ArugaZ** [comment]
tambahin?

**Comment by thoriqazzikra** [comment]
> tambahin?

caranya gmna si
saya udah copy antilink dri git sebelah
cmn gabisa

iseng aja  si bang nambahin fitur

plis antilinknya tambahin bang

**Comment by thoriqazzikra** [comment]
sama mute bot bang
misalnya ngetik #mute terus bot nya bakalan gabisa dipake commandnya di group tertentu

**Comment by NaldoMota1** [comment]
> Se alguém enviar link, automaticamente expulso ou o quê?

ya, otomatis dikeluarkan

**Comment by MrZinAG** [comment]
> sama mute bot bang
> misalnya ngetik #mute terus bot nya bakalan gabisa dipake commandnya di group tertentu

ngrepotin owner aj lu

**Comment by thoriqazzikra** [comment]
> > sama mute bot bang
> > misalnya ngetik #mute terus bot nya bakalan gabisa dipake commandnya di group tertentu
> 
> ngrepotin owner aj lu

lah

**Comment by ArugaZ** [comment]
sip bntr

**Comment by MrZinAG** [comment]
> > > sama mute bot bang
> > > misalnya ngetik #mute terus bot nya bakalan gabisa dipake commandnya di group tertentu
> > 
> > 
> > ngrepotin owner aj lu
> 
> lah

skali skali sendiri napa tod,, klo ada yg syntaxx cari di stackoverflow,  mnding lu liat pp gw smbil bacol.

**Comment by idkmew** [comment]
//FITUR ANTILINK 
if (isGroupMsg && !isGroupAdmins && !isAdmin && !isOwner){
                    if (chats.match(/(https:\/\/chat.whatsapp.com)/gi)) {
                        const check = await kris.inviteInfo(chats);
                        if (!check) {
                            return
                        } else {
                            kris.reply(from, `*「 GROUP LINK DETECTOR 」*\nKamu mengirimkan link grup chat, maaf kamu di kick dari grup :(`, id).then(() => {
                                kris.removeParticipant(groupId, sender.id)
                            })
                        }
                    }
                }    

Setelah dipasang, dan di npm run, maka akan muncul error tentang chats
jadi taruh ini : 
const chats = (type === 'chat') ? body : (type === 'image' || type === 'video') ? caption : ''

Maka setelah itu tinggal npm run, dan dicoba kirimkan link, untuk member maka Bot akan otomatis mengkick, dan klo untuk Admin Bot 

untuk yg isAdmin bisa dibuat jadi gini 
const isAdmin = adminNumber.includes(pengirim)
dan untuk isOwner bisa juga dibuat jadi gini
const isOwner = ownerNumber.includes(pengirim)

Udah saya coba dan work ko :')

+ ada juga untuk yg antibadwords auto kick ma Bot
btw yg antilink bisa juga dibuat jadi untuk member auto kick, dan untuk admin cmn teguran gtu ✌️

**Comment by ArugaZ** [comment]
buat pull request aja gan

**Comment by thoriqazzikra** [comment]
> //FITUR ANTILINK
> if (isGroupMsg && !isGroupAdmins && !isAdmin && !isOwner){
> if (chats.match(/(https://chat.whatsapp.com)/gi)) {
> const check = await kris.inviteInfo(chats);
> if (!check) {
> return
> } else {
> kris.reply(from, `*「 GROUP LINK DETECTOR 」*\nKamu mengirimkan link grup chat, maaf kamu di kick dari grup :(`, id).then(() => {
> kris.removeParticipant(groupId, sender.id)
> })
> }
> }
> }
> 
> Setelah dipasang, dan di npm run, maka akan muncul error tentang chats
> jadi taruh ini :
> const chats = (type === 'chat') ? body : (type === 'image' || type === 'video') ? caption : ''
> 
> Maka setelah itu tinggal npm run, dan dicoba kirimkan link, untuk member maka Bot akan otomatis mengkick, dan klo untuk Admin Bot
> 
> untuk yg isAdmin bisa dibuat jadi gini
> const isAdmin = adminNumber.includes(pengirim)
> dan untuk isOwner bisa juga dibuat jadi gini
> const isOwner = ownerNumber.includes(pengirim)
> 
> Udah saya coba dan work ko :')
> 
> * ada juga untuk yg antibadwords auto kick ma Bot
>   btw yg antilink bisa juga dibuat jadi untuk member auto kick, dan untuk admin cmn teguran gtu v

ada yg error bang

coba pake code aja bang

**Comment by thoriqazzikra** [comment]
> > > > sama mute bot bang
> > > > misalnya ngetik #mute terus bot nya bakalan gabisa dipake commandnya di group tertentu
> > > 
> > > 
> > > ngrepotin owner aj lu
> > 
> > 
> > lah
> 
> skali skali sendiri napa tod,, klo ada yg syntaxx cari di stackoverflow, mnding lu liat pp gw smbil bacol.

udeh tod, cmn error tod ga ngerespon tod tod

**Comment by Tanaka9531** [comment]
Antilink itu apa gunanya

**Comment by thoriqazzikra** [comment]
> Antilink itu apa gunanya

kalo ada yg share link di group, itu bakalan kekick

**Comment by NaldoMota1** [comment]
> buat pull request aja gan

jelaskan kepada saya bagaimana menambahkan fungsi ini bro

> //FITUR ANTILINK
> if (isGroupMsg && !isGroupAdmins && !isAdmin && !isOwner){
> if (chats.match(/(https://chat.whatsapp.com)/gi)) {
> const check = await kris.inviteInfo(chats);
> if (!check) {
> return
> } else {
> kris.reply(from, `*「 GROUP LINK DETECTOR 」*\nKamu mengirimkan link grup chat, maaf kamu di kick dari grup :(`, id).then(() => {
> kris.removeParticipant(groupId, sender.id)
> })
> }
> }
> }
> 
> Setelah dipasang, dan di npm run, maka akan muncul error tentang chats
> jadi taruh ini :
> const chats = (type === 'chat') ? body : (type === 'image' || type === 'video') ? caption : ''
> 
> Maka setelah itu tinggal npm run, dan dicoba kirimkan link, untuk member maka Bot akan otomatis mengkick, dan klo untuk Admin Bot
> 
> untuk yg isAdmin bisa dibuat jadi gini
> const isAdmin = adminNumber.includes(pengirim)
> dan untuk isOwner bisa juga dibuat jadi gini
> const isOwner = ownerNumber.includes(pengirim)
> 
> Udah saya coba dan work ko :')
> 
> * ada juga untuk yg antibadwords auto kick ma Bot
>   btw yg antilink bisa juga dibuat jadi untuk member auto kick, dan untuk admin cmn teguran gtu ✌️

jelaskan kepada saya bagaimana menambahkan fungsi ini bro

**Comment by Fucksociety666** [comment]
> //FITUR ANTILINK
> if (isGroupMsg && !isGroupAdmins && !isAdmin && !isOwner){
> if (chats.match(/(https://chat.whatsapp.com)/gi)) {
> const check = await kris.inviteInfo(chats);
> if (!check) {
> return
> } else {
> kris.reply(from, `*「 GROUP LINK DETECTOR 」*\nKamu mengirimkan link grup chat, maaf kamu di kick dari grup :(`, id).then(() => {
> kris.removeParticipant(groupId, sender.id)
> })
> }
> }
> }
> 
> Setelah dipasang, dan di npm run, maka akan muncul error tentang chats
> jadi taruh ini :
> const chats = (type === 'chat') ? body : (type === 'image' || type === 'video') ? caption : ''
> 
> Maka setelah itu tinggal npm run, dan dicoba kirimkan link, untuk member maka Bot akan otomatis mengkick, dan klo untuk Admin Bot
> 
> untuk yg isAdmin bisa dibuat jadi gini
> const isAdmin = adminNumber.includes(pengirim)
> dan untuk isOwner bisa juga dibuat jadi gini
> const isOwner = ownerNumber.includes(pengirim)
> 
> Udah saya coba dan work ko :')
> 
>     * ada juga untuk yg antibadwords auto kick ma Bot
>       btw yg antilink bisa juga dibuat jadi untuk member auto kick, dan untuk admin cmn teguran gtu v

di lurusin dlu ngab :V , biar gk syntzax

**Comment by thoriqazzikra** [comment]
> > buat pull request aja gan
> 
> jelaskan kepada saya bagaimana menambahkan fungsi ini bro
> 
> > //FITUR ANTILINK
> > if (isGroupMsg && !isGroupAdmins && !isAdmin && !isOwner){
> > if (chats.match(/(https://chat.whatsapp.com)/gi)) {
> > const check = await kris.inviteInfo(chats);
> > if (!check) {
> > return
> > } else {
> > kris.reply(from, `*「 GROUP LINK DETECTOR 」*\nKamu mengirimkan link grup chat, maaf kamu di kick dari grup :(`, id).then(() => {
> > kris.removeParticipant(groupId, sender.id)
> > })
> > }
> > }
> > }
> > Setelah dipasang, dan di npm run, maka akan muncul error tentang chats
> > jadi taruh ini :
> > const chats = (type === 'chat') ? body : (type === 'image' || type === 'video') ? caption : ''
> > Maka setelah itu tinggal npm run, dan dicoba kirimkan link, untuk member maka Bot akan otomatis mengkick, dan klo untuk Admin Bot
> > untuk yg isAdmin bisa dibuat jadi gini
> > const isAdmin = adminNumber.includes(pengirim)
> > dan untuk isOwner bisa juga dibuat jadi gini
> > const isOwner = ownerNumber.includes(pengirim)
> > Udah saya coba dan work ko :')
> > 
> > * ada juga untuk yg antibadwords auto kick ma Bot
> >   btw yg antilink bisa juga dibuat jadi untuk member auto kick, dan untuk admin cmn teguran gtu v
> 
> jelaskan kepada saya bagaimana menambahkan fungsi ini bro

pull request

**Comment by Fakyy19** [comment]
Bro cara bikin antilink no kick gimana ya
