### ISSUE TITLE
tagall/everyone with info

### ISSUE THREAD

**Issue by thoriqazzikra** [ArugaZ/whatsapp-bot#148]
biar ga spam gimana ya bang, 1 doang gitu kek tagall cmn ada infonya

![image](https://user-images.githubusercontent.com/75126993/101237042-5b8a7a00-3708-11eb-87a3-1b3d49dedd96.png)

case 'infoall' :
            if (!isGroupMsg) return aruga.reply(from, 'Maaf, perintah ini hanya dapat dipakai didalam grup!', id)
            if (!isGroupAdmins) return aruga.reply(from, 'Gagal, fitur ini bakalan work kalo dipake sama admin, member mah gausah sok keras', id)
            const gpMem = await aruga.getGroupMembers(groupId)
            let msgs = body.slice(idk)
            for (let idk of chats){
            for (let i = 0; i < gpMem.length; i++) {
                var cvk = await aruga.getChatById(idk)
                msgs += '-'
                msgs += ` @${gpMem[i].id.replace(/@c.us/g, '')}\n`
            }
            msgs += '\n'
            await aruga.sendTextWithMentions(from, msgs)
        }
            break

**Comment by ArugaZ** [comment]
```
        case 'tagall':
            if (!isGroupMsg) return aruga.reply(from, 'Maaf, perintah ini hanya dapat dipakai didalam grup!', id)
            if (!isGroupAdmins) return aruga.reply(from, 'Gagal, perintah ini hanya dapat digunakan oleh admin grup!', id)
           const textInfo = body.slice(8)
            const groupMem = await aruga.getGroupMembers(groupId)
            let hehex = '╔══✪〘 Mention All 〙✪══\n'
            for (let i = 0; i < groupMem.length; i++) {
                hehex += '╠➥'
                hehex += ` @${groupMem[i].id.replace(/@c.us/g, '')}\n`
            }
            hehex += '╚═〘 *A R U G A  B O T* 〙'
            await aruga.sendTextWithMentions(from, textInfo+ '\n' +hehex)
            break
```

**Comment by ArugaZ** [comment]
atau bisa kaya gini, untuk nambahin dari siapa

#tagall selamat pagi!

```
        case 'tagall':
            if (!isGroupMsg) return aruga.reply(from, 'Maaf, perintah ini hanya dapat dipakai didalam grup!', id)
            if (!isGroupAdmins) return aruga.reply(from, 'Gagal, perintah ini hanya dapat digunakan oleh admin grup!', id)
           const textInfo = body.slice(8)
            const groupMem = await aruga.getGroupMembers(groupId)
            let hehex = '╔══✪〘 Mention All 〙✪══\n'
            for (let i = 0; i < groupMem.length; i++) {
                hehex += '╠➥'
                hehex += ` @${groupMem[i].id.replace(/@c.us/g, '')}\n`
            }
            hehex += '╚═〘 *A R U G A  B O T* 〙'
            await aruga.sendTextWithMentions(from, `Info dari: ${pushname}\n` + textInfo + '\n\n' +hehex)
            break
```

output:

Info dari: ArugaZ
selamat pagi!

@tagmember
@tagmember
@tagmember

**Comment by thoriqazzikra** [comment]
> atau bisa kaya gini, untuk nambahin dari siapa
> 
> #tagall selamat pagi!
> 
> ```
>         case 'tagall':
>             if (!isGroupMsg) return aruga.reply(from, 'Maaf, perintah ini hanya dapat dipakai didalam grup!', id)
>             if (!isGroupAdmins) return aruga.reply(from, 'Gagal, perintah ini hanya dapat digunakan oleh admin grup!', id)
>            const textInfo = body.slice(8)
>             const groupMem = await aruga.getGroupMembers(groupId)
>             let hehex = '╔══✪〘 Mention All 〙✪══\n'
>             for (let i = 0; i < groupMem.length; i++) {
>                 hehex += '╠➥'
>                 hehex += ` @${groupMem[i].id.replace(/@c.us/g, '')}\n`
>             }
>             hehex += '╚═〘 *A R U G A  B O T* 〙'
>             await aruga.sendTextWithMentions(from, `Info dari: ${pushname}\n` + textInfo + '\n\n' +hehex)
>             break
> ```
> 
> output:
> 
> Info dari: ArugaZ
> selamat pagi!
> 
> @tagmember
> @tagmember
> @tagmember

makasihhhhh banyakkkkkk bangggggggggg
