### ISSUE TITLE
API TEXT TO STICKER

### ISSUE THREAD

**Issue by Tanaka9531** [ArugaZ/whatsapp-bot#150]
https://st4rz.herokuapp.com/api/ttp?kata=kwkkwwkkwkw

**Comment by MrPawNO** [comment]
> https://st4rz.herokuapp.com/api/ttp?kata=kwkkwwkkwkw

Ngab minta kumpulan web rest api
Thanks

**Comment by selyxn** [comment]
> https://st4rz.herokuapp.com/api/ttp?kata=kwkkwwkkwkw

@ArugaZ Tolong buatin case nya :(

**Comment by ArugaZ** [comment]
nt ane buatin yg text 3D

**Comment by ArugaZ** [comment]
coba cek bot ane yg #ttp - #ttp10

**Comment by ArugaZ** [comment]
nih case nya kl mau pake

     ```
     case 'ttp':
     axios.get(`https://st4rz.herokuapp.com/api/ttp?kata=${body.slice(5)}`)
     .then(res => {
          aruga.sendImageAsSticker(from, res.data.result)
     })
```

**Comment by MrPawNO** [comment]
> nt ane buatin yg text 3D

Owhh image nya dari cooltext gan?, ane sudah bikin tadi

**Comment by selyxn** [comment]
> nih case nya kl mau pake
> 
> ```
>  ```
>  case 'ttp':
>  axios.get(`https://st4rz.herokuapp.com/api/ttp?kata=${body.slice(5)}`)
>  .then(res => {
>       aruga.sendImageAsSticker(from, res.data.result)
>  })
> ```

numpang tnya, fngsi body.slice(5) ap ya

**Comment by Tanaka9531** [comment]
> > https://st4rz.herokuapp.com/api/ttp?kata=kwkkwwkkwkw
> 
> Ngab minta kumpulan web rest api
> Thanks

Aku lagi kumpulin rest api di situs2 :) sekalian bantu2 bang aruga terus gratisan yah bang Makasih

**Comment by Tanaka9531** [comment]
> > https://st4rz.herokuapp.com/api/ttp?kata=kwkkwwkkwkw
> 
> Ngab minta kumpulan web rest api
> Thanks

BANG B

> > nt ane buatin yg text 3D
> 
> Owhh image nya dari cooltext gan?, ane sudah bikin sejenis itu

bang arugaz buatin case nya dong ini link nya plis https://api.haipbis.xyz/randomcooltext?text=blablabla

**Comment by Tanaka9531** [comment]
> > > https://st4rz.herokuapp.com/api/ttp?kata=kwkkwwkkwkw
> > 
> > 
> > Ngab minta kumpulan web rest api
> > Thanks
> > > nt ane buatin yg text 3D
> > 
> > 
> > Owhh image nya dari cooltext gan?, ane sudah bikin sejenis itu
> 
> bang arugaz buatin case nya dong ini link nya plis https://api.haipbis.xyz/randomcooltext?text=blablabla

bang bisa gak aku request jam dunia kalau bisa bang kalau gak bisa gak papa sih

**Comment by MrZinAG** [comment]
> > nt ane buatin yg text 3D
> 
> Owhh image nya dari cooltext gan?, ane sudah bikin sejenis itu

yg ttp gk pke lib langsung case kah? Mr.Pawno ori

**Comment by MrPawNO** [comment]
> > > https://st4rz.herokuapp.com/api/ttp?kata=kwkkwwkkwkw
> > 
> > 
> > Ngab minta kumpulan web rest api
> > Thanks
> > > nt ane buatin yg text 3D
> > 
> > 
> > Owhh image nya dari cooltext gan?, ane sudah bikin sejenis itu
> 
> bang arugaz buatin case nya dong ini link nya plis https://api.haipbis.xyz/randomcooltext?text=blablabla

NIHH ANE KASIH..

case 'cooltext':
            if (args.length == 0) return aruga.reply(from, `Untuk membuat teks keren CoolText pada gambar, gunakan ${prefix}cooltext teks\n\nContoh: ${prefix}cooltext fikri ganteng`, id)
			rugaapi.cooltext(args[0])
			.then(async(res) => {
				await aruga.sendFileFromUrl(from, `${res.link}`, '', `${res.text}`, id)
			})
			break

const cooltext = async (teks) => new Promise((resolve, reject) => {
	axios.get(`https://api.haipbis.xyz/randomcooltext?text=${teks}`)
	.then((res) => {
		const textc = `Teks: ${res.data.text}\nGambar: ${res.data.image}`
		resolve({link: res.data.image, text: textc})
	})
	.catch((err) => {
		reject(err)
	})
})

Jangan lupa masukin cooltext ke module exports juga

**Comment by MrPawNO** [comment]
> > > nt ane buatin yg text 3D
> > 
> > 
> > Owhh image nya dari cooltext gan?, ane sudah bikin sejenis itu
> 
> yg ttp gk pke lib langsung case kah? Mr.Pawno ori

hooh

**Comment by ArugaZ** [comment]
buat pull request aja gan, nt saya acc. sekalian bantu2 soalnya jrg buka github

**Comment by ArugaZ** [comment]
> > nih case nya kl mau pake
> > 
> > case 'ttp':
> > axios.get(`https://st4rz.herokuapp.com/api/ttp?kata=${body.slice(5)}`)
> > .then(res => {
> > aruga.sendImageAsSticker(from, res.data.result)
> > })
> 
> numpang tnya, fngsi body.slice(5) ap ya

referensi buat belajar 
`https://www.w3schools.com/jsref/jsref_slice_array.asp`

**Comment by Tanaka9531** [comment]
> > > > https://st4rz.herokuapp.com/api/ttp?kata=kwkkwwkkwkw
> > > 
> > > 
> > > Ngab minta kumpulan web rest api
> > > Thanks
> > > > nt ane buatin yg text 3D
> > > 
> > > 
> > > Owhh image nya dari cooltext gan?, ane sudah bikin sejenis itu
> > 
> > 
> > bang arugaz buatin case nya dong ini link nya plis https://api.haipbis.xyz/randomcooltext?text=blablabla
> 
> NIHH ANE KASIH..
> 
> case 'cooltext':
> if (args.length == 0) return aruga.reply(from, `Untuk membuat teks keren CoolText pada gambar, gunakan ${prefix}cooltext teks\n\nContoh: ${prefix}cooltext fikri ganteng`, id)
> rugaapi.cooltext(args[0])
> .then(async(res) => {
> await aruga.sendFileFromUrl(from, `${res.link}`, '', `${res.text}`, id)
> })
> break
> 
> const cooltext = async (teks) => new Promise((resolve, reject) => {
> axios.get(`https://api.haipbis.xyz/randomcooltext?text=${teks}`)
> .then((res) => {
> const textc = `Teks: ${res.data.text}\nGambar: ${res.data.image}`
> resolve({link: res.data.image, text: textc})
> })
> .catch((err) => {
> reject(err)
> })
> })
> 
> Jangan lupa masukin cooltext ke module exports juga

makasih

**Comment by Tanaka9531** [comment]
> > > > https://st4rz.herokuapp.com/api/ttp?kata=kwkkwwkkwkw
> > > 
> > > 
> > > Ngab minta kumpulan web rest api
> > > Thanks
> > > > nt ane buatin yg text 3D
> > > 
> > > 
> > > Owhh image nya dari cooltext gan?, ane sudah bikin sejenis itu
> > 
> > 
> > bang arugaz buatin case nya dong ini link nya plis https://api.haipbis.xyz/randomcooltext?text=blablabla
> 
> bang bisa gak aku request jam dunia kalau bisa bang kalau gak bisa gak papa sih

gak maksa :)

**Comment by ArugaZ** [comment]
buat yg baru aja gan dh oot
