### ISSUE TITLE
Req Bang

### ISSUE THREAD

**Issue by idkmew** [ArugaZ/whatsapp-bot#151]
Bang Req dong cron :'(

**Comment by ArugaZ** [comment]
pm2 with cron?

**Comment by idkmew** [comment]
> pm2 with cron?

Iya bang, hehe, dan saya juga bingung knp ya, kadang pas Botny dipake dan pas ngerespond bnyk command itu botny langsung ke determinate, jadi terpaksa harus di npm start lagi

**Comment by ArugaZ** [comment]
gini aja, 

`
npm i pm2 -g
cd ke folder whatsapp-bot
pm2 start index.js --cron "*/menit * * * *"
`
kalau restart setiap 20menit sekali jd gni
`
pm2 start index.js --cron "*/20 * * * *"
`

**Comment by idkmew** [comment]
> pm2 with cron?

dan juga, saya sebelumny nyoba di SC lain masukin case cerpen dan requireny udh bener lokasiny di arugaApi dan harusny udh bener, tapi pas saya npm start ko malah arugaApiny ga dikenal atau ap gtu lupa, ad solusiga bang?

**Comment by ArugaZ** [comment]
> > pm2 with cron?
> 
> dan juga, saya sebelumny nyoba di SC lain masukin case cerpen dan requireny udh bener lokasiny di arugaApi dan harusny udh bener, tapi pas saya npm start ko malah arugaApiny ga dikenal atau ap gtu lupa, ad solusiga bang?

panggil dlu
const rugaApi = require('./tempat file')

**Comment by idkmew** [comment]
> > > pm2 with cron?
> > 
> > 
> > dan juga, saya sebelumny nyoba di SC lain masukin case cerpen dan requireny udh bener lokasiny di arugaApi dan harusny udh bener, tapi pas saya npm start ko malah arugaApiny ga dikenal atau ap gtu lupa, ad solusiga bang?
> 
> panggil dlu
> const rugaApi = require('./tempat file')

udh bang tapi ttp ajh gabisa, pdhal yg lainny bisa kyk resep dari abang

**Comment by idkmew** [comment]
> > > pm2 with cron?
> > 
> > 
> > dan juga, saya sebelumny nyoba di SC lain masukin case cerpen dan requireny udh bener lokasiny di arugaApi dan harusny udh bener, tapi pas saya npm start ko malah arugaApiny ga dikenal atau ap gtu lupa, ad solusiga bang?
> 
> panggil dlu
> const rugaApi = require('./tempat file')

dan bang mau nanya, apakah bisa kalau fitur welcomeny dibuat dgn welcome.js + welcome.json, biar ga spam, soalny saya sebelumny pernah make SC Bot Elaina, dan krna welcomeny gtu + left yg dipisah, jadiny botny ga nyepam gtu bang, tapi entah saya coba terapkan welcomeny di sc abang knp ya gabisa, pdhal udh saya buat const welcome.js di index dan di msg handler untuk welcome.json tapi ttp ga berfungsi + yg welcome enable juga pas saya tulis !welcome enable, malah Botny cmn ngerespond  silahkan pilih enable atau Disable stuck disitu, ad saran ga bang? hehe

**Comment by MrZinAG** [comment]
> > > > pm2 with cron?
> > > 
> > > 
> > > dan juga, saya sebelumny nyoba di SC lain masukin case cerpen dan requireny udh bener lokasiny di arugaApi dan harusny udh bener, tapi pas saya npm start ko malah arugaApiny ga dikenal atau ap gtu lupa, ad solusiga bang?
> > 
> > 
> > panggil dlu
> > const rugaApi = require('./tempat file')
> 
> dan bang mau nanya, apakah bisa kalau fitur welcomeny dibuat dgn welcome.js + welcome.json, biar ga spam, soalny saya sebelumny pernah make SC Bot Elaina, dan krna welcomeny gtu + left yg dipisah, jadiny botny ga nyepam gtu bang, tapi entah saya coba terapkan welcomeny di sc abang knp ya gabisa, pdhal udh saya buat const welcome.js di index dan di msg handler untuk welcome.json tapi ttp ga berfungsi + yg welcome enable juga pas saya tulis !welcome enable, malah Botny cmn ngerespond silahkan pilih enable atau Disable stuck disitu, ad saran ga bang? hehe

klo tnya min 1 2 klo lebih dri itu mustahil untuk di bls

**Comment by MrZinAG** [comment]
> > > > pm2 with cron?
> > > 
> > > 
> > > dan juga, saya sebelumny nyoba di SC lain masukin case cerpen dan requireny udh bener lokasiny di arugaApi dan harusny udh bener, tapi pas saya npm start ko malah arugaApiny ga dikenal atau ap gtu lupa, ad solusiga bang?
> > 
> > 
> > panggil dlu
> > const rugaApi = require('./tempat file')
> 
> dan bang mau nanya, apakah bisa kalau fitur welcomeny dibuat dgn welcome.js + welcome.json, biar ga spam, soalny saya sebelumny pernah make SC Bot Elaina, dan krna welcomeny gtu + left yg dipisah, jadiny botny ga nyepam gtu bang, tapi entah saya coba terapkan welcomeny di sc abang knp ya gabisa, pdhal udh saya buat const welcome.js di index dan di msg handler untuk welcome.json tapi ttp ga berfungsi + yg welcome enable juga pas saya tulis !welcome enable, malah Botny cmn ngerespond silahkan pilih enable atau Disable stuck disitu, ad saran ga bang? hehe

ksih pertanyaan di buat 1 komntar tpi banyk ,, klo 1 1 mls ownernya

**Comment by idkmew** [comment]
> > > > > pm2 with cron?
> > > > 
> > > > 
> > > > dan juga, saya sebelumny nyoba di SC lain masukin case cerpen dan requireny udh bener lokasiny di arugaApi dan harusny udh bener, tapi pas saya npm start ko malah arugaApiny ga dikenal atau ap gtu lupa, ad solusiga bang?
> > > 
> > > 
> > > panggil dlu
> > > const rugaApi = require('./tempat file')
> > 
> > 
> > dan bang mau nanya, apakah bisa kalau fitur welcomeny dibuat dgn welcome.js + welcome.json, biar ga spam, soalny saya sebelumny pernah make SC Bot Elaina, dan krna welcomeny gtu + left yg dipisah, jadiny botny ga nyepam gtu bang, tapi entah saya coba terapkan welcomeny di sc abang knp ya gabisa, pdhal udh saya buat const welcome.js di index dan di msg handler untuk welcome.json tapi ttp ga berfungsi + yg welcome enable juga pas saya tulis !welcome enable, malah Botny cmn ngerespond silahkan pilih enable atau Disable stuck disitu, ad saran ga bang? hehe
> 
> ksih pertanyaan di buat 1 komntar tpi banyk ,, klo 1 1 mls ownernya

OK Thanks infony lur

**Comment by MrZinAG** [comment]
> > > > > > pm2 with cron?
> > > > > 
> > > > > 
> > > > > dan juga, saya sebelumny nyoba di SC lain masukin case cerpen dan requireny udh bener lokasiny di arugaApi dan harusny udh bener, tapi pas saya npm start ko malah arugaApiny ga dikenal atau ap gtu lupa, ad solusiga bang?
> > > > 
> > > > 
> > > > panggil dlu
> > > > const rugaApi = require('./tempat file')
> > > 
> > > 
> > > dan bang mau nanya, apakah bisa kalau fitur welcomeny dibuat dgn welcome.js + welcome.json, biar ga spam, soalny saya sebelumny pernah make SC Bot Elaina, dan krna welcomeny gtu + left yg dipisah, jadiny botny ga nyepam gtu bang, tapi entah saya coba terapkan welcomeny di sc abang knp ya gabisa, pdhal udh saya buat const welcome.js di index dan di msg handler untuk welcome.json tapi ttp ga berfungsi + yg welcome enable juga pas saya tulis !welcome enable, malah Botny cmn ngerespond silahkan pilih enable atau Disable stuck disitu, ad saran ga bang? hehe
> > 
> > 
> > ksih pertanyaan di buat 1 komntar tpi banyk ,, klo 1 1 mls ownernya
> 
> OK Thanks infony lur

btw cron buat apa ya ngab :V

**Comment by idkmew** [comment]
> > > > > > > pm2 with cron?
> > > > > > 
> > > > > > 
> > > > > > dan juga, saya sebelumny nyoba di SC lain masukin case cerpen dan requireny udh bener lokasiny di arugaApi dan harusny udh bener, tapi pas saya npm start ko malah arugaApiny ga dikenal atau ap gtu lupa, ad solusiga bang?
> > > > > 
> > > > > 
> > > > > panggil dlu
> > > > > const rugaApi = require('./tempat file')
> > > > 
> > > > 
> > > > dan bang mau nanya, apakah bisa kalau fitur welcomeny dibuat dgn welcome.js + welcome.json, biar ga spam, soalny saya sebelumny pernah make SC Bot Elaina, dan krna welcomeny gtu + left yg dipisah, jadiny botny ga nyepam gtu bang, tapi entah saya coba terapkan welcomeny di sc abang knp ya gabisa, pdhal udh saya buat const welcome.js di index dan di msg handler untuk welcome.json tapi ttp ga berfungsi + yg welcome enable juga pas saya tulis !welcome enable, malah Botny cmn ngerespond silahkan pilih enable atau Disable stuck disitu, ad saran ga bang? hehe
> > > 
> > > 
> > > ksih pertanyaan di buat 1 komntar tpi banyk ,, klo 1 1 mls ownernya
> > 
> > 
> > OK Thanks infony lur
> 
> btw cron buat apa ya ngab :V

Untuk ngatasin botny autoread dan ga respond commandny/delay kali yak , jadi klo di pasang cron bakal auto restart Bot sesuai waktu yg kita tentuin, jadiny gaperlu kita ribet ctrl + c trus npm start lagi, krna udh otomatis

**Comment by MrZinAG** [comment]
> > > > > > > > pm2 with cron?
> > > > > > > 
> > > > > > > 
> > > > > > > dan juga, saya sebelumny nyoba di SC lain masukin case cerpen dan requireny udh bener lokasiny di arugaApi dan harusny udh bener, tapi pas saya npm start ko malah arugaApiny ga dikenal atau ap gtu lupa, ad solusiga bang?
> > > > > > 
> > > > > > 
> > > > > > panggil dlu
> > > > > > const rugaApi = require('./tempat file')
> > > > > 
> > > > > 
> > > > > dan bang mau nanya, apakah bisa kalau fitur welcomeny dibuat dgn welcome.js + welcome.json, biar ga spam, soalny saya sebelumny pernah make SC Bot Elaina, dan krna welcomeny gtu + left yg dipisah, jadiny botny ga nyepam gtu bang, tapi entah saya coba terapkan welcomeny di sc abang knp ya gabisa, pdhal udh saya buat const welcome.js di index dan di msg handler untuk welcome.json tapi ttp ga berfungsi + yg welcome enable juga pas saya tulis !welcome enable, malah Botny cmn ngerespond silahkan pilih enable atau Disable stuck disitu, ad saran ga bang? hehe
> > > > 
> > > > 
> > > > ksih pertanyaan di buat 1 komntar tpi banyk ,, klo 1 1 mls ownernya
> > > 
> > > 
> > > OK Thanks infony lur
> > 
> > 
> > btw cron buat apa ya ngab :V
> 
> Untuk ngatasin botny autoread dan ga respond commandny/delay kali yak , jadi klo di pasang cron bakal auto restart Bot sesuai waktu yg kita tentuin, jadiny gaperlu kita ribet ctrl + c trus npm start lagi, krna udh otomatis

lu pke vps kah ??

**Comment by idkmew** [comment]
> > > > > > > > > pm2 with cron?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > dan juga, saya sebelumny nyoba di SC lain masukin case cerpen dan requireny udh bener lokasiny di arugaApi dan harusny udh bener, tapi pas saya npm start ko malah arugaApiny ga dikenal atau ap gtu lupa, ad solusiga bang?
> > > > > > > 
> > > > > > > 
> > > > > > > panggil dlu
> > > > > > > const rugaApi = require('./tempat file')
> > > > > > 
> > > > > > 
> > > > > > dan bang mau nanya, apakah bisa kalau fitur welcomeny dibuat dgn welcome.js + welcome.json, biar ga spam, soalny saya sebelumny pernah make SC Bot Elaina, dan krna welcomeny gtu + left yg dipisah, jadiny botny ga nyepam gtu bang, tapi entah saya coba terapkan welcomeny di sc abang knp ya gabisa, pdhal udh saya buat const welcome.js di index dan di msg handler untuk welcome.json tapi ttp ga berfungsi + yg welcome enable juga pas saya tulis !welcome enable, malah Botny cmn ngerespond silahkan pilih enable atau Disable stuck disitu, ad saran ga bang? hehe
> > > > > 
> > > > > 
> > > > > ksih pertanyaan di buat 1 komntar tpi banyk ,, klo 1 1 mls ownernya
> > > > 
> > > > 
> > > > OK Thanks infony lur
> > > 
> > > 
> > > btw cron buat apa ya ngab :V
> > 
> > 
> > Untuk ngatasin botny autoread dan ga respond commandny/delay kali yak , jadi klo di pasang cron bakal auto restart Bot sesuai waktu yg kita tentuin, jadiny gaperlu kita ribet ctrl + c trus npm start lagi, krna udh otomatis
> 
> lu pke vps kah ??

nope, make laptop :v

**Comment by idkmew** [comment]
Bang @ArugaZ  mo nanya, ini knp ya? pas udh dijalankan malah jadi gtu?
![image](https://user-images.githubusercontent.com/72456125/101246269-25bbb480-374d-11eb-98f6-67b3f317701b.png)

**Comment by ArugaZ** [comment]
> Bang @ArugaZ mo nanya, ini knp ya? pas udh dijalankan malah jadi gtu?
> ![image](https://user-images.githubusercontent.com/72456125/101246269-25bbb480-374d-11eb-98f6-67b3f317701b.png)

lgsg ke stop?

**Comment by ArugaZ** [comment]
> > > > pm2 with cron?
> > > 
> > > 
> > > dan juga, saya sebelumny nyoba di SC lain masukin case cerpen dan requireny udh bener lokasiny di arugaApi dan harusny udh bener, tapi pas saya npm start ko malah arugaApiny ga dikenal atau ap gtu lupa, ad solusiga bang?
> > 
> > 
> > panggil dlu
> > const rugaApi = require('./tempat file')
> 
> dan bang mau nanya, apakah bisa kalau fitur welcomeny dibuat dgn welcome.js + welcome.json, biar ga spam, soalny saya sebelumny pernah make SC Bot Elaina, dan krna welcomeny gtu + left yg dipisah, jadiny botny ga nyepam gtu bang, tapi entah saya coba terapkan welcomeny di sc abang knp ya gabisa, pdhal udh saya buat const welcome.js di index dan di msg handler untuk welcome.json tapi ttp ga berfungsi + yg welcome enable juga pas saya tulis !welcome enable, malah Botny cmn ngerespond silahkan pilih enable atau Disable stuck disitu, ad saran ga bang? hehe

bisa si dipisah nt saya buat

**Comment by idkmew** [comment]
> > Bang @ArugaZ mo nanya, ini knp ya? pas udh dijalankan malah jadi gtu?
> > ![image](https://user-images.githubusercontent.com/72456125/101246269-25bbb480-374d-11eb-98f6-67b3f317701b.png)
> 
> lgsg ke stop?

iya bang :'

**Comment by idkmew** [comment]
> > > Bang @ArugaZ mo nanya, ini knp ya? pas udh dijalankan malah jadi gtu?
> > > ![image](https://user-images.githubusercontent.com/72456125/101246269-25bbb480-374d-11eb-98f6-67b3f317701b.png)
> > 
> > 
> > lgsg ke stop?
> 
> iya bang :'

dan pas saya npm ulang lagi ke 3x ny muncul ini 00:

√ Browser Launched
[Error: EPERM: operation not permitted, unlink 'C:\Users\user\AppData\Local\Temp\puppeteer_dev_chrome_profile-CmzDcf\CrashpadMetrics-active.pma'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\user\\AppData\\Local\\Temp\\puppeteer_dev_chrome_profile-CmzDcf\\CrashpadMetrics-active.pma'
}
