### ISSUE TITLE
give limit

### ISSUE THREAD

**Issue by MrPawNO** [ArugaZ/whatsapp-bot#152]
Ane pengen ngasih limit ke cmd cersex gimana tuh gan

**Comment by MrZinAG** [comment]
> Ane pengen ngasih limit ke cmd cersex gimana tuh gan

case :'limit'
        aruga.reply ( snk, Maaf perintah ini di limit, id) 
        break
var = (limitbot)) body.slice(4)
    var = (iscmd))  log.err = (1)

**Comment by MrPawNO** [comment]
> > Ane pengen ngasih limit ke cmd cersex gimana tuh gan
> 
> case :'limit'
> aruga.reply ( snk, Maaf perintah ini di limit, id)
> break
> var = (limitbot)) body.slice(4)
> var = (iscmd)) log.err = (1)

masih kurang paham
