### ISSUE TITLE
Fix Error

### ISSUE THREAD

**Issue by DevN2** [ArugaZ/whatsapp-bot#153]
Fix PLAY gan,data hanya dikirimkan berupa foto dan judul.
tapi data audio tidak terkirim, solusinya gimana?

**Comment by MrZinAG** [comment]
> Fix PLAY gan,data hanya dikirimkan berupa foto dan judul.
> tapi data audio tidak terkirim, solusinya gimana?

cd whatsapp-bot
sudo apt install ffmpeg

**Comment by idkmew** [comment]
> > Fix PLAY gan,data hanya dikirimkan berupa foto dan judul.
> > tapi data audio tidak terkirim, solusinya gimana?
> 
> cd whatsapp-bot
> sudo apt install ffmpeg

atau engga, klo make windows, bisa download ffmpegny(check youtube untuk tutor pemasanganny, biar ke detect) ✌️

**Comment by thoriqazzikra** [comment]
> > Fix PLAY gan,data hanya dikirimkan berupa foto dan judul.
> > tapi data audio tidak terkirim, solusinya gimana?
> 
> cd whatsapp-bot
> sudo apt install ffmpeg

ini udah diinstal
terus gada yg ditambahin lagi kah?

**Comment by ArugaZ** [comment]
fitur youtube lgi error dari rest api nya

**Comment by DevN2** [comment]
> > Fix PLAY gan,data hanya dikirimkan berupa foto dan judul.
> > tapi data audio tidak terkirim, solusinya gimana?
> 
> cd whatsapp-bot
> sudo apt install ffmpeg

sudah gan. masih tidak bisa,malah keluar eror spt berikut :
TCL: getDURL -> error Error : connect ECONNREFUSED 127.0.0.1:8,dan bisa lihat di sini
![16071815383681159328085](https://user-images.githubusercontent.com/73986677/101246782-053d2b80-3748-11eb-925d-240337e6e3ae.jpg)
