### ISSUE TITLE
HELP 💤

### ISSUE THREAD

**Issue by ArugaZ** [ArugaZ/whatsapp-bot#154]
### **buat kalian yang ingin membantu project ini silahkan buat pull request**

`kalau ada instagram comment aja nt saya taruh disponsor`

jarang buka github sayanya 🚶

**Comment by MrPawNO** [comment]
> ### **buat kalian yang ingin membantu project ini silahkan buat pull request**
> `kalau ada instagram comment aja nt saya taruh disponsor`
> 
> jarang buka github sayanya

acc pull requests ku gan

**Comment by MrZinAG** [comment]
> ### **buat kalian yang ingin membantu project ini silahkan buat pull request**
> 
> `kalau ada instagram comment aja nt saya taruh disponsor`
> 
> jarang buka github sayanya walking

done

**Comment by ArugaZ** [comment]
> > ### **buat kalian yang ingin membantu project ini silahkan buat pull request**
> > `kalau ada instagram comment aja nt saya taruh disponsor`
> > jarang buka github sayanya
> 
> acc pull requests ku gan

tambahin di menu.js sekalian gan

**Comment by MrPawNO** [comment]
> > > ### **buat kalian yang ingin membantu project ini silahkan buat pull request**
> > > `kalau ada instagram comment aja nt saya taruh disponsor`
> > > jarang buka github sayanya
> > 
> > 
> > acc pull requests ku gan
> 
> tambahin di menu.js sekalian gan

oiye lupa

**Comment by TheSploit** [comment]
btw ko gabisa ngePull ya :'(

Choose different branches or forks above to discuss and review changes. Learn about pull requests

pdhal mo bantu ngepull Brainly, ad yg tau cara biar bisa ngepull?

**Comment by thoriqazzikra** [comment]
> btw ko gabisa ngePull ya :'(
> 
> Choose different branches or forks above to discuss and review changes. Learn about pull requests
> 
> pdhal mo bantu ngepull Brainly, ad yg tau cara biar bisa ngepull?

Pull request dong

**Comment by TheSploit** [comment]
acc Pull reqq ku bang

**Comment by TheSploit** [comment]
> > btw ko gabisa ngePull ya :'(
> > Choose different branches or forks above to discuss and review changes. Learn about pull requests
> > pdhal mo bantu ngepull Brainly, ad yg tau cara biar bisa ngepull?
> 
> Pull request dong

iya

**Comment by Fucksociety666** [comment]
> > > btw ko gabisa ngePull ya :'(
> > > Choose different branches or forks above to discuss and review changes. Learn about pull requests
> > > pdhal mo bantu ngepull Brainly, ad yg tau cara biar bisa ngepull?
> > 
> > 
> > Pull request dong
> 
> iya

bagi sini coba ,, mau sy cek valid gk

**Comment by TheSploit** [comment]
> > > > btw ko gabisa ngePull ya :'(
> > > > Choose different branches or forks above to discuss and review changes. Learn about pull requests
> > > > pdhal mo bantu ngepull Brainly, ad yg tau cara biar bisa ngepull?
> > > 
> > > 
> > > Pull request dong
> > 
> > 
> > iya
> 
> bagi sini coba ,, mau sy cek valid gk

silahkan check di pull request
