### ISSUE TITLE
How to fix?

### ISSUE THREAD

**Issue by syamsulrizaljantho** [ArugaZ/whatsapp-bot#159]
Cara benerinnya gimana ya?

![photo6224273915853777753](https://user-images.githubusercontent.com/75537709/101267116-19088200-3788-11eb-8c9b-3de57d404420.jpg)
![photo6224167349125229137](https://user-images.githubusercontent.com/75537709/101267120-1b6adc00-3788-11eb-9237-9cb79d815dda.jpg)

**Comment by syamsulrizaljantho** [comment]
Biar sama kaya gambar berikut :

![photo6224167349125229138](https://user-images.githubusercontent.com/75537709/101267170-992ee780-3788-11eb-91ba-d9cbfe8c69df.jpg)
![photo6224273915853777754](https://user-images.githubusercontent.com/75537709/101267173-9b914180-3788-11eb-80ae-d0a8e5a2dd81.jpg)

Terus kenapa videonya malah kemute pas udah didownload

![SharedScreenshot](https://user-images.githubusercontent.com/75537709/101267174-9d5b0500-3788-11eb-8f02-2a3ae1813852.jpg)

**Comment by idkmew** [comment]
case 'welcome':
            if (!isGroupMsg) return aruga.reply(from, 'Perintah ini hanya bisa di gunakan dalam group!', id)
            if (!isGroupAdmins) return aruga.reply(from, 'Perintah ini hanya bisa di gunakan oleh Admin group!', id)
            if (args.length === 1) return aruga.reply(from, 'Pilih enable atau disable!', id)
            if (args[1].toLowerCase() === 'enable') {
                welkom.push(chat.id)
                fs.writeFileSync('./lib/database/welcome.json', JSON.stringify(welkom))
                aruga.reply(from, 'Fitur welcome berhasil di aktifkan di group ini!', id)
            } else if (args[1].toLowerCase() === 'disable') {
                welkom.splice(chat.id, 1)
                fs.writeFileSync('./lib/database/welcome.json', JSON.stringify(welkom))
                aruga.reply(from, 'Fitur welcome berhasil di nonaktifkan di group ini!', id)
            } else {
                aruga.reply(from, 'Pilih enable atau disable udin!', id)
            }
            break

Bang mo nanya, saya udh npm start dan pas nyoba !welcome enable, malah botny ngerespondny Pilih enable atau disable!
a[ ad saran knp gabisa?

**Comment by MrPawNO** [comment]
> Cara benerinnya gimana ya?
> 
> ![photo6224273915853777753](https://user-images.githubusercontent.com/75537709/101267116-19088200-3788-11eb-8c9b-3de57d404420.jpg)
> ![photo6224167349125229137](https://user-images.githubusercontent.com/75537709/101267120-1b6adc00-3788-11eb-9237-9cb79d815dda.jpg)

Fitur converter (ytmp3,ytmp4) emang lagi error di rest api nya, saranku sementara ini ganti api lain aja...
BOT ku pakai API lain

**Comment by suyantikasimin** [comment]
> > Cara benerinnya gimana ya?
> > ![photo6224273915853777753](https://user-images.githubusercontent.com/75537709/101267116-19088200-3788-11eb-8c9b-3de57d404420.jpg)
> > ![photo6224167349125229137](https://user-images.githubusercontent.com/75537709/101267120-1b6adc00-3788-11eb-9237-9cb79d815dda.jpg)
> 
> Fitur converter (ytmp3,ytmp4) emang lagi error di rest api nya, saranku sementara ini ganti api lain aja...
> BOT ku pakai API lain

Bagi link gan
