### ISSUE TITLE
Cara Fix Ini Bagaimana?

### ISSUE THREAD

**Issue by DevN2** [ArugaZ/whatsapp-bot#160]
jadi saya ketika menggunakan sc dari ArugaZ,ada 3 masalah spt berikut
-fitur play,nah ketika fitur ini saya coba,data audio tidak muncul,hanya gambar saja yg tulisannya "judul, dilihat seberapa dan sebagainya". saya sudah instal FFMPEG tetapi masih tidak bisa.

-fitur welcome,pas saya sudah menjalankan "welcome on" dan ada yg keluar/masuk grup,bot tidak merespon apa2.

-fitur downlad yt dan teman"nya

mohon bantu saya dalam 3 eror tersebut

**Comment by MrPawNO** [comment]
> jadi saya ketika menggunakan sc dari ArugaZ,ada 3 masalah spt berikut
> -fitur play,nah ketika fitur ini saya coba,data audio tidak muncul,hanya gambar saja yg tulisannya "judul, dilihat seberapa dan sebagainya". saya sudah instal FFMPEG tetapi masih tidak bisa.
> 
> -fitur welcome,pas saya sudah menjalankan "welcome on" dan ada yg keluar/masuk grup,bot tidak merespon apa2.
> 
> -fitur downlad yt dan teman"nya
> 
> mohon bantu saya dalam 3 eror tersebut

Fitur converter (ytmp3,ytmp4) emang lagi error di rest api nya, saranku sementara ini ganti api lain aja...

**Comment by DevN2** [comment]
> > jadi saya ketika menggunakan sc dari ArugaZ,ada 3 masalah spt berikut
> > -fitur play,nah ketika fitur ini saya coba,data audio tidak muncul,hanya gambar saja yg tulisannya "judul, dilihat seberapa dan sebagainya". saya sudah instal FFMPEG tetapi masih tidak bisa.
> > -fitur welcome,pas saya sudah menjalankan "welcome on" dan ada yg keluar/masuk grup,bot tidak merespon apa2.
> > -fitur downlad yt dan teman"nya
> > mohon bantu saya dalam 3 eror tersebut
> 
> Fitur converter (ytmp3,ytmp4) emang lagi error di rest api nya, saranku sementara ini ganti api lain aja...

kalau fitur play gimana ngatasinya?

**Comment by MrPawNO** [comment]
> > > jadi saya ketika menggunakan sc dari ArugaZ,ada 3 masalah spt berikut
> > > -fitur play,nah ketika fitur ini saya coba,data audio tidak muncul,hanya gambar saja yg tulisannya "judul, dilihat seberapa dan sebagainya". saya sudah instal FFMPEG tetapi masih tidak bisa.
> > > -fitur welcome,pas saya sudah menjalankan "welcome on" dan ada yg keluar/masuk grup,bot tidak merespon apa2.
> > > -fitur downlad yt dan teman"nya
> > > mohon bantu saya dalam 3 eror tersebut
> > 
> > 
> > Fitur converter (ytmp3,ytmp4) emang lagi error di rest api nya, saranku sementara ini ganti api lain aja...
> 
> kalau fitur play gimana ngatasinya?

Belom pernah gunakan play, kalo gasalah fiturnya sama kek ytmp3 ya?, kalo iya, api nya samain kek ytmp3 aja
API yang dirubah: ytmp3,ytmp4,play

**Comment by DevN2** [comment]
> 
> 
> > > > jadi saya ketika menggunakan sc dari ArugaZ,ada 3 masalah spt berikut
> > > > -fitur play,nah ketika fitur ini saya coba,data audio tidak muncul,hanya gambar saja yg tulisannya "judul, dilihat seberapa dan sebagainya". saya sudah instal FFMPEG tetapi masih tidak bisa.
> > > > -fitur welcome,pas saya sudah menjalankan "welcome on" dan ada yg keluar/masuk grup,bot tidak merespon apa2.
> > > > -fitur downlad yt dan teman"nya
> > > > mohon bantu saya dalam 3 eror tersebut
> > > 
> > > 
> > > Fitur converter (ytmp3,ytmp4) emang lagi error di rest api nya, saranku sementara ini ganti api lain aja...
> > 
> > 
> > kalau fitur play gimana ngatasinya?
> 
> Belom pernah gunakan play, kalo gasalah fiturnya sama kek ytmp3 ya?, kalo iya, api nya samain kek ytmp3 aja
> API yang dirubah: ytmp3,ytmp4,play

ok terimakasih :)
