### ISSUE TITLE
mau buat pull request tapi gatau caranya wkwk terus disini aja ya bang maap.... INI FITUR GET PROFILE INFO

### ISSUE THREAD

**Issue by thoriqazzikra** [ArugaZ/whatsapp-bot#161]
case 'profile':
            if (isBanned) return false
            if (isGroupMsg) {
                if (!quotedMsg) {
                var pic = await aruga.getProfilePicFromServer(author)
                var namae = pushname
                var sts = await aruga.getStatus(author)
                var adm = isGroupAdmins
                const { status } = sts
                if (pic == undefined) {
                    var pfp = errorurl 
                } else {
                    var pfp = pic
                } 
                await aruga.sendFileFromUrl(from, pfp, 'pfp.jpg', `*User Profile* ✨️ \n\n➸ *Username: ${namae}*\n\n➸ *User Info: ${status}*\n\n➸ *Admin Group: ${adm}*\n\n`)
             } else if (quotedMsg) {
             var qmid = quotedMsgObj.sender.id
             var pic = await aruga.getProfilePicFromServer(qmid)
             var namae = quotedMsgObj.sender.name
             var sts = await aruga.getStatus(qmid)
             var adm = isGroupAdmins
             var donate = isAdmin
             const { status } = sts
              if (pic == undefined) {
              var pfp = errorurl 
              } else {
              var pfp = pic
              } 
              await aruga.sendFileFromUrl(from, pfp, 'pfp.jpg', `*User Profile* ✨️ \n\n➸ *Username: ${namae}*\n\n➸ *User Info: ${status}*\n\n➸ *Admin Group: ${adm}*\n\n`)
             }
            }
            break

**Comment by Tanaka9531** [comment]
case 'groupinfo' :
            if (isLimit(serial)) return kaguya.reply(from, `Maaf ${pushname}, Kuota Limit Kamu Sudah Habis, Ketik #limit Untuk Mengecek Kuota Limit Kamu`, id)
            
            await limitAdd(serial)
            if (!isGroupMsg) return kaguya.reply(from, '.', message.id) 
            var totalMem = chat.groupMetadata.participants.length
            var desc = chat.groupMetadata.desc
            var groupname = name
            var welgrp = wel.includes(chat.id)
            var ngrp = nsfwgrp.includes(chat.id)
            var grouppic = await kaguya.getProfilePicFromServer(chat.id)
            if (grouppic == undefined) {
                 var pfp = errorurl
            } else {
                 var pfp = grouppic 
            }
            await kaguya.sendFileFromUrl(from, pfp, 'group.png', `*${groupname}* 

🌐️ *Members: ${totalMem}*

💌️ *Welcome: ${welgrp}*

⚜️ *NSFW: ${ngrp}*

📃️ *Group Description* 

${desc}`)
        break

**Comment by Tanaka9531** [comment]
case 'groupinfo' :
            if (!isGroupMsg) return kaguya.reply(from, '.', message.id) 
            var totalMem = chat.groupMetadata.participants.length
            var desc = chat.groupMetadata.desc
            var groupname = name
            var welgrp = wel.includes(chat.id)
            var ngrp = nsfwgrp.includes(chat.id)
            var grouppic = await kaguya.getProfilePicFromServer(chat.id)
            if (grouppic == undefined) {
                 var pfp = errorurl
            } else {
                 var pfp = grouppic 
            }
            await kaguya.sendFileFromUrl(from, pfp, 'group.png', `*${groupname}* 

🌐️ *Members: ${totalMem}*

💌️ *Welcome: ${welgrp}*

⚜️ *NSFW: ${ngrp}*

📃️ *Group Description* 

${desc}`)
        break

**Comment by Tanaka9531** [comment]
> ```
>     case 'groupinfo' :
>         if (!isGroupMsg) return kaguya.reply(from, '.', message.id) 
>         var totalMem = chat.groupMetadata.participants.length
>         var desc = chat.groupMetadata.desc
>         var groupname = name
>         var welgrp = wel.includes(chat.id)
>         var ngrp = nsfwgrp.includes(chat.id)
>         var grouppic = await kaguya.getProfilePicFromServer(chat.id)
>         if (grouppic == undefined) {
>              var pfp = errorurl
>         } else {
>              var pfp = grouppic 
>         }
>         await kaguya.sendFileFromUrl(from, pfp, 'group.png', `*${groupname}* 
> ```
> 
> 🌐️ _Members: ${totalMem}_
> 
> 💌️ _Welcome: ${welgrp}_
> 
> ⚜️ _NSFW: ${ngrp}_
> 
> 📃️ _Group Description_
> 
> ${desc}`)
> break

:v

**Comment by TheSploit** [comment]
> > ```
> >     case 'groupinfo' :
> >         if (!isGroupMsg) return kaguya.reply(from, '.', message.id) 
> >         var totalMem = chat.groupMetadata.participants.length
> >         var desc = chat.groupMetadata.desc
> >         var groupname = name
> >         var welgrp = wel.includes(chat.id)
> >         var ngrp = nsfwgrp.includes(chat.id)
> >         var grouppic = await kaguya.getProfilePicFromServer(chat.id)
> >         if (grouppic == undefined) {
> >              var pfp = errorurl
> >         } else {
> >              var pfp = grouppic 
> >         }
> >         await kaguya.sendFileFromUrl(from, pfp, 'group.png', `*${groupname}* 
> > ```
> > 
> > 
> > 🌐️ _Members: ${totalMem}_
> > 💌️ _Welcome: ${welgrp}_
> > ⚜️ _NSFW: ${ngrp}_
> > 📃️ _Group Description_
> > ${desc}`)
> > break
> 
> :v

kykny bakal error deh, soalny yg NSFW ny ga terdefinisi dan welcomenyklo dari wel juga bakal sama, jadi harusny dibuat :
var welgrp = wel.includes(chat.id) jadi var welgrp = welcome.includes(chat.id), trus yg NSFWny harus dibuat dlu baru bisa ✌️

**Comment by thoriqazzikra** [comment]
> > > ```
> > >     case 'groupinfo' :
> > >         if (!isGroupMsg) return kaguya.reply(from, '.', message.id) 
> > >         var totalMem = chat.groupMetadata.participants.length
> > >         var desc = chat.groupMetadata.desc
> > >         var groupname = name
> > >         var welgrp = wel.includes(chat.id)
> > >         var ngrp = nsfwgrp.includes(chat.id)
> > >         var grouppic = await kaguya.getProfilePicFromServer(chat.id)
> > >         if (grouppic == undefined) {
> > >              var pfp = errorurl
> > >         } else {
> > >              var pfp = grouppic 
> > >         }
> > >         await kaguya.sendFileFromUrl(from, pfp, 'group.png', `*${groupname}* 
> > > ```
> > > 
> > > 
> > > globe_with_meridians _Members: ${totalMem}_
> > > love_letter _Welcome: ${welgrp}_
> > > fleur_de_lis _NSFW: ${ngrp}_
> > > page_with_curl _Group Description_
> > > ${desc}`)
> > > break
> > 
> > 
> > :v
> 
> kykny bakal error deh, soalny yg NSFW ny ga terdefinisi dan welcomenyklo dari wel juga bakal sama, jadi harusny dibuat :
> var welgrp = wel.includes(chat.id) jadi var welgrp = welcome.includes(chat.id), trus yg NSFWny harus dibuat dlu baru bisa

nihh yang gua pakee

case 'groupinfo' :
            case 'gcinfo' :
            if (!isGroupMsg) return aruga.reply(from, 'Perintah ini hanya bisa di gunakan dalam group!', message.id)
            var totalMem = chat.groupMetadata.participants.length
            var desc = chat.groupMetadata.desc
            var groupname = name
            var antlink = antilink.includes(chat.id)
            var grouppic = await aruga.getProfilePicFromServer(chat.id)
            if (grouppic == undefined) {
                 var pfp = errorurl
            } else {
                 var pfp = grouppic 
            }
            await aruga.sendFileFromUrl(from, pfp, 'group.png', `*「 GROUP INFO 」*
*➸ *Name : ${groupname}* 
*➸ Members : ${totalMem}*
*➸ Anti Link : ${antlink ? 'Aktif' : 'Tidak Aktif'}*
*➸ Group Description* 
${desc}`)
            break

**Comment by selyxn** [comment]
> > > > ```
> > > >     case 'groupinfo' :
> > > >         if (!isGroupMsg) return kaguya.reply(from, '.', message.id) 
> > > >         var totalMem = chat.groupMetadata.participants.length
> > > >         var desc = chat.groupMetadata.desc
> > > >         var groupname = name
> > > >         var welgrp = wel.includes(chat.id)
> > > >         var ngrp = nsfwgrp.includes(chat.id)
> > > >         var grouppic = await kaguya.getProfilePicFromServer(chat.id)
> > > >         if (grouppic == undefined) {
> > > >              var pfp = errorurl
> > > >         } else {
> > > >              var pfp = grouppic 
> > > >         }
> > > >         await kaguya.sendFileFromUrl(from, pfp, 'group.png', `*${groupname}* 
> > > > ```
> > > > 
> > > > 
> > > > globe_with_meridians _Members: ${totalMem}_
> > > > love_letter _Welcome: ${welgrp}_
> > > > fleur_de_lis _NSFW: ${ngrp}_
> > > > page_with_curl _Group Description_
> > > > ${desc}`)
> > > > break
> > > 
> > > 
> > > :v
> > 
> > 
> > kykny bakal error deh, soalny yg NSFW ny ga terdefinisi dan welcomenyklo dari wel juga bakal sama, jadi harusny dibuat :
> > var welgrp = wel.includes(chat.id) jadi var welgrp = welcome.includes(chat.id), trus yg NSFWny harus dibuat dlu baru bisa
> 
> nihh yang gua pakee
> 
> ```
> - [ ] case 'groupinfo' :
> - [ ]             case 'gcinfo' :
> - [ ]             if (!isGroupMsg) return aruga.reply(from, 'Perintah ini hanya bisa di gunakan dalam group!', message.id)
> - [ ]             var totalMem = chat.groupMetadata.participants.length
> - [ ]             var desc = chat.groupMetadata.desc
> - [ ]             var groupname = name
> - [ ]             var antlink = antilink.includes(chat.id)
> - [ ]             var grouppic = await aruga.getProfilePicFromServer(chat.id)
> - [ ]             if (grouppic == undefined) {
> - [ ]                  var pfp = errorurl
> - [ ]             } else {
> - [ ]                  var pfp = grouppic 
> - [ ]             }
> - [ ]             await aruga.sendFileFromUrl(from, pfp, 'group.png', `*「 GROUP INFO 」*
> - [ ] *➸ *Name : ${groupname}* 
> - [ ] *➸ Members : ${totalMem}*
> - [ ] *➸ Anti Link : ${antlink ? 'Aktif' : 'Tidak Aktif'}*
> - [ ] *➸ Group Description* 
> - [ ] ${desc}`)
> - [ ]             break
> - [ ] 
> ```

minta antilink :(

**Comment by thoriqazzikra** [comment]
> > > > > ```
> > > > >     case 'groupinfo' :
> > > > >         if (!isGroupMsg) return kaguya.reply(from, '.', message.id) 
> > > > >         var totalMem = chat.groupMetadata.participants.length
> > > > >         var desc = chat.groupMetadata.desc
> > > > >         var groupname = name
> > > > >         var welgrp = wel.includes(chat.id)
> > > > >         var ngrp = nsfwgrp.includes(chat.id)
> > > > >         var grouppic = await kaguya.getProfilePicFromServer(chat.id)
> > > > >         if (grouppic == undefined) {
> > > > >              var pfp = errorurl
> > > > >         } else {
> > > > >              var pfp = grouppic 
> > > > >         }
> > > > >         await kaguya.sendFileFromUrl(from, pfp, 'group.png', `*${groupname}* 
> > > > > ```
> > > > > 
> > > > > 
> > > > > globe_with_meridians _Members: ${totalMem}_
> > > > > love_letter _Welcome: ${welgrp}_
> > > > > fleur_de_lis _NSFW: ${ngrp}_
> > > > > page_with_curl _Group Description_
> > > > > ${desc}`)
> > > > > break
> > > > 
> > > > 
> > > > :v
> > > 
> > > 
> > > kykny bakal error deh, soalny yg NSFW ny ga terdefinisi dan welcomenyklo dari wel juga bakal sama, jadi harusny dibuat :
> > > var welgrp = wel.includes(chat.id) jadi var welgrp = welcome.includes(chat.id), trus yg NSFWny harus dibuat dlu baru bisa
> > 
> > 
> > nihh yang gua pakee
> > ```
> > - [ ] case 'groupinfo' :
> > - [ ]             case 'gcinfo' :
> > - [ ]             if (!isGroupMsg) return aruga.reply(from, 'Perintah ini hanya bisa di gunakan dalam group!', message.id)
> > - [ ]             var totalMem = chat.groupMetadata.participants.length
> > - [ ]             var desc = chat.groupMetadata.desc
> > - [ ]             var groupname = name
> > - [ ]             var antlink = antilink.includes(chat.id)
> > - [ ]             var grouppic = await aruga.getProfilePicFromServer(chat.id)
> > - [ ]             if (grouppic == undefined) {
> > - [ ]                  var pfp = errorurl
> > - [ ]             } else {
> > - [ ]                  var pfp = grouppic 
> > - [ ]             }
> > - [ ]             await aruga.sendFileFromUrl(from, pfp, 'group.png', `*「 GROUP INFO 」*
> > - [ ] *➸ *Name : ${groupname}* 
> > - [ ] *➸ Members : ${totalMem}*
> > - [ ] *➸ Anti Link : ${antlink ? 'Aktif' : 'Tidak Aktif'}*
> > - [ ] *➸ Group Description* 
> > - [ ] ${desc}`)
> > - [ ]             break
> > - [ ] 
> > ```
> 
> minta antilink :(

udh didelete ngab
itu kedetect, cmn pas ketik #antilink enable, itu botnya malah reply "pilih enable atau disable"
pusing ngab

**Comment by Fucksociety666** [comment]
> case 'profile':
> if (isBanned) return false
> if (isGroupMsg) {
> if (!quotedMsg) {
> var pic = await aruga.getProfilePicFromServer(author)
> var namae = pushname
> var sts = await aruga.getStatus(author)
> var adm = isGroupAdmins
> const { status } = sts
> if (pic == undefined) {
> var pfp = errorurl
> } else {
> var pfp = pic
> }
> await aruga.sendFileFromUrl(from, pfp, 'pfp.jpg', `*User Profile* ✨️ \n\n➸ *Username: ${namae}*\n\n➸ *User Info: ${status}*\n\n➸ *Admin Group: ${adm}*\n\n`)
> } else if (quotedMsg) {
> var qmid = quotedMsgObj.sender.id
> var pic = await aruga.getProfilePicFromServer(qmid)
> var namae = quotedMsgObj.sender.name
> var sts = await aruga.getStatus(qmid)
> var adm = isGroupAdmins
> var donate = isAdmin
> const { status } = sts
> if (pic == undefined) {
> var pfp = errorurl
> } else {
> var pfp = pic
> }
> await aruga.sendFileFromUrl(from, pfp, 'pfp.jpg', `*User Profile* ✨️ \n\n➸ *Username: ${namae}*\n\n➸ *User Info: ${status}*\n\n➸ *Admin Group: ${adm}*\n\n`)
> }
> }
> break

ke detect syntax

**Comment by thoriqazzikra** [comment]
> > case 'profile':
> > if (isBanned) return false
> > if (isGroupMsg) {
> > if (!quotedMsg) {
> > var pic = await aruga.getProfilePicFromServer(author)
> > var namae = pushname
> > var sts = await aruga.getStatus(author)
> > var adm = isGroupAdmins
> > const { status } = sts
> > if (pic == undefined) {
> > var pfp = errorurl
> > } else {
> > var pfp = pic
> > }
> > await aruga.sendFileFromUrl(from, pfp, 'pfp.jpg', `*User Profile* ✨️ \n\n➸ *Username: ${namae}*\n\n➸ *User Info: ${status}*\n\n➸ *Admin Group: ${adm}*\n\n`)
> > } else if (quotedMsg) {
> > var qmid = quotedMsgObj.sender.id
> > var pic = await aruga.getProfilePicFromServer(qmid)
> > var namae = quotedMsgObj.sender.name
> > var sts = await aruga.getStatus(qmid)
> > var adm = isGroupAdmins
> > var donate = isAdmin
> > const { status } = sts
> > if (pic == undefined) {
> > var pfp = errorurl
> > } else {
> > var pfp = pic
> > }
> > await aruga.sendFileFromUrl(from, pfp, 'pfp.jpg', `*User Profile* ✨️ \n\n➸ *Username: ${namae}*\n\n➸ *User Info: ${status}*\n\n➸ *Admin Group: ${adm}*\n\n`)
> > }
> > }
> > break
> 
> ke detect syntax

Check pull ane yg update handlemsg
