### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by Tanaka9531** [ArugaZ/whatsapp-bot#163]
![WhatsApp Image 2020-12-06 at 10 15 20 (1)](https://user-images.githubusercontent.com/73052642/101270493-259ed180-37ac-11eb-9b87-59fbe54d9dad.jpeg)
kok gitu yah??

tapi pas aku ubah file dokumennya jadi format mp3 baru bisa ke putar tuh musiknya cara fixnya gimanayah
![WhatsApp Image 2020-12-06 at 10 15 20](https://user-images.githubusercontent.com/73052642/101270515-5aab2400-37ac-11eb-89b3-94c0b4c67c18.jpeg)

**Comment by ShinzX** [comment]
Nah ada yang komen juga :v

**Comment by Tanaka9531** [comment]
> Nah ada yang komen juga :v

:) kamu jg yah

**Comment by syamsulrizaljantho** [comment]
if (res.error) return aruga.sendFileFromUrl(from, `${res.url}`, '', `${res.error}`)
				await aruga.sendFileFromUrl(from, `${res.result.thumb}`, '', `Audio ditemukan\n\nJudul : ${res.result.title}\n\nUkuran : ${res.result.filesize}`, id)
				await aruga.sendFileFromUrl(from, `${res.result.url}`, `${res.result.title}.mp3`,, '', id)
				.catch(() => {
					aruga.reply(from, `URL INI ${args[0]} SUDAH PERNAH DI DOWNLOAD SEBELUMNYA ..URL AKAN RESET SETELAH 60 MENIT`, id)
				})
