### ISSUE TITLE
Error pas mau ngePull 

### ISSUE THREAD

**Issue by TheSploit** [ArugaZ/whatsapp-bot#168]
fatal: unable to access 'https://github.com/ArugaZ/whatsapp-bot/': The requested URL returned error: 403

ad yg bisa bantu? soalny mo commit untuk ngepull brainly, antilink ma kawan"ny jadi susah :'(

**Comment by MrPawNO** [comment]
> fatal: unable to access 'https://github.com/ArugaZ/whatsapp-bot/': The requested URL returned error: 403
> 
> ad yg bisa bantu? soalny mo commit untuk ngepull brainly, antilink ma kawan"ny jadi susah :'(

situ fork dulu -> make changes (perubahan) di repo yang udah di fork -> pull requests

**Comment by MrPawNO** [comment]
> fatal: unable to access 'https://github.com/ArugaZ/whatsapp-bot/': The requested URL returned error: 403
> 
> ad yg bisa bantu? soalny mo commit untuk ngepull brainly, antilink ma kawan"ny jadi susah :'(

harap untuk close issue ini, terimakasih
