### ISSUE TITLE
knapa BOT Nya Nyepam ya?

### ISSUE THREAD

**Issue by agusydk3** [ArugaZ/whatsapp-bot#17]
![image](https://user-images.githubusercontent.com/57493908/98463310-e8671400-21ec-11eb-9751-3bd4eda632ed.png)
![image](https://user-images.githubusercontent.com/57493908/98463315-edc45e80-21ec-11eb-824f-bdefedeae43f.png)

**Comment by shansekai** [comment]
Dari open wa nya..

**Comment by ArugaZ** [comment]
dari open-wa nya gan
