### ISSUE TITLE
Sticker to Image

### ISSUE THREAD

**Issue by selyxn** [ArugaZ/whatsapp-bot#171]
Tolong buatin fitur sticker to image dung

**Comment by TheSploit** [comment]
> Tolong buatin fitur sticker to image dung

Okey saya pull untuk sticker to img ya :')

**Comment by thoriqazzikra** [comment]
> Tolong buatin fitur sticker to image dung

`           case 'stmg':
            case 'stickertoimg':
                if (quotedMsg && quotedMsg.type == 'sticker') {
                    const mediaData = await decryptMedia(quotedMsg)
                    aruga.reply(from, `[WAIT] Sedang di proses⏳ silahkan tunggu!`, id)
                    const imageBase64 = `data:${quotedMsg.mimetype};base64,${mediaData.toString('base64')}`
                    await aruga.sendFile(from, imageBase64, 'imagesticker.jpg', 'Success Convert Sticker to Image!', id)
            } else if (!quotedMsg) return aruga.reply(from, `Mohon tag sticker yang ingin dijadikan gambar!`, id)
            break`

**Comment by thoriqazzikra** [comment]
buat di menunya tambahin sendiri ya xixi
