### ISSUE TITLE
help, req fitur

### ISSUE THREAD

**Issue by selyxn** [ArugaZ/whatsapp-bot#181]
Fiture premium pornhub @ArugaZ

**Comment by shansekai** [comment]
Bokep terooos

**Comment by selyxn** [comment]
> Bokep terooos

Kalo gamau bantu gausah komen, nanya ke @ArugaZ

**Comment by Fucksociety666** [comment]
> Fiture premium pornhub @ArugaZ

lngsung dm ig aj ngab :V kalo command premium

**Comment by ArugaZ** [comment]
cmnd pornhub udh pernah saya masukin di versi sebelumnya, cmn banyk yg pada error jdi saya hapus lgi
