### ISSUE TITLE
!welcome on bug no respon

### ISSUE THREAD

**Issue by Fucksociety666** [ArugaZ/whatsapp-bot#182]
![image](https://user-images.githubusercontent.com/74858900/101442203-63872b80-394d-11eb-98dc-1989116285dc.png)

**Comment by Fucksociety666** [comment]
![Screenshot pada 2020-12-08 21-12-27](https://user-images.githubusercontent.com/74858900/101494875-c71a5480-395f-11eb-895a-8f735bcfca2d.png)

**Comment by ArugaZ** [comment]
coba restart bot nya

**Comment by Fucksociety666** [comment]
![Screenshot pada 2020-12-11 13-08-05](https://user-images.githubusercontent.com/74858900/101869599-b80def00-3b77-11eb-8adb-2702f87287e9.png)
sama aja

**Comment by Suryapardana** [comment]
Saya juga sama, udah di restart masih tetap gabisa
