### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Suryapardana** [ArugaZ/whatsapp-bot#183]
![Screenshot_2020-12-07-17-36-07-611_com whatsapp](https://user-images.githubusercontent.com/47344288/101446677-4dca3400-3956-11eb-8752-8fc1251527ae.jpg)

Cara fix bagaimana? **Sticker, on/off semuanya gitu, cuma di reply. terus**

**Comment by MrPawNO** [comment]
> ![Screenshot_2020-12-07-17-36-07-611_com whatsapp](https://user-images.githubusercontent.com/47344288/101446677-4dca3400-3956-11eb-8752-8fc1251527ae.jpg)
> 
> Cara fix bagaimana? **Sticker, on/off semuanya gitu, cuma di reply. terus**



> ![Screenshot_2020-12-07-17-36-07-611_com whatsapp](https://user-images.githubusercontent.com/47344288/101446677-4dca3400-3956-11eb-8752-8fc1251527ae.jpg)
> 
> Cara fix bagaimana? **Sticker, on/off semuanya gitu, cuma di reply. terus**

Ganti prefix nya
