### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by thoriqazzikra** [ArugaZ/whatsapp-bot#190]
ada yang tau ga cara masukin orang tanpa ngetag?, misalnya nih kan kita ngekick orang terus kan ada fotonya tuh(kalo pake profile sih) ya karna ane pake jadi ane mau tanya. itu masukin orang tinggal ngereply message bot yg barusan kita kick gimana?

**Comment by ArugaZ** [comment]
bisa si gan

**Comment by thoriqazzikra** [comment]
> bisa si gan

nah tuh bang, jadi ga repot bang kalo mau masukin org yg udah di kick

**Comment by thoriqazzikra** [comment]
> bisa si gan

bang, cara block onGlobalParticipants gimana?
ini jadi suka spam sendiri bang
