### ISSUE TITLE
${prefix}everyone Suggestion

### ISSUE THREAD

**Issue by mioscape** [ArugaZ/whatsapp-bot#192]
I think you should change the `${prefix}` to `@` its make it more make sense, and change permission to all Members.

**Comment by Fucksociety666** [comment]
can't because it's universal command

**Comment by mioscape** [comment]
> can't because it's universal command

I need ArugaZ to Review it.

**Comment by Fucksociety666** [comment]
> I need ArugaZ to Review it. Also what do you mean by `universal`

what I mean is if $ {prefix} help
it will be detected! help
well in every command there must be a $ {prefix} function so that it is easy to change in setting.json so as not to change every (prefix / command)

**Comment by Fucksociety666** [comment]
Do you understand??

**Comment by mioscape** [comment]
> > I need ArugaZ to Review it. Also what do you mean by `universal`
> 
> what I mean is if $ {prefix} help
> it will be detected! help
> well in every command there must be a $ {prefix} function so that it is easy to change in setting.json so as not to change every (prefix / command)
> 
> 
> 

I see, and this is just Suggestion
