### ISSUE TITLE
Help ngab

### ISSUE THREAD

**Issue by Suryapardana** [ArugaZ/whatsapp-bot#193]
## Fitur translate, welcome, eror ngab
**Cara fix gimana ngab**

**Comment by Fucksociety666** [comment]
kick juga error

**Comment by Fucksociety666** [comment]
![Screenshot pada 2020-12-09 12-59-39](https://user-images.githubusercontent.com/74858900/101591185-d642e600-39e3-11eb-8c4c-70fdda552835.png)
![Screenshot pada 2020-12-09 12-59-56](https://user-images.githubusercontent.com/74858900/101591191-da6f0380-39e3-11eb-8354-499ebae12dce.png)
![Screenshot pada 2020-12-09 13-01-19](https://user-images.githubusercontent.com/74858900/101591369-549f8800-39e4-11eb-92e4-a2dc3ba3654e.png)

**Comment by Suryapardana** [comment]
Yaudah sama :'

**Comment by ArugaZ** [comment]
translate dr modulenya, kick add udh di fix
