### ISSUE TITLE
error option #kick

### ISSUE THREAD

**Issue by thoriqazzikra** [ArugaZ/whatsapp-bot#195]
cmn send text doang botnya tpi ga ngekick member yg di tag

**Comment by Fucksociety666** [comment]
![Screenshot pada 2020-12-09 12-56-02](https://user-images.githubusercontent.com/74858900/101590948-469d3780-39e3-11eb-8c75-0952e6854ae8.png)
iya bjirr

**Comment by thoriqazzikra** [comment]
kirain gua doang awkoawko

**Comment by thoriqazzikra** [comment]
solved 
`case 'kick':
                if (!isGroupMsg) return aruga.reply(from, 'Maaf, perintah ini hanya dapat dipakai didalam grup!', id)
                if (!isGroupAdmins) return aruga.reply(from, 'Gagal, perintah ini hanya dapat digunakan oleh admin grup!', id)
                if (!isBotGroupAdmins) return aruga.reply(from, 'Gagal, silahkan tambahkan bot sebagai admin grup!', id)
                if (mentionedJidList.length === 0) return aruga.reply(from, 'Maaf, format pesan salah.\nSilahkan tag satu atau lebih orang yang akan dikeluarkan', id)
                if (mentionedJidList[0] === botNumber) return await aruga.reply(from, 'Maaf, format pesan salah.\nTidak dapat mengeluarkan akun bot sendiri', id)
                await aruga.sendTextWithMentions(from, `Done, mengeluarkan:\n${mentionedJidList.map(x => `@${x.replace('@c.us', '')}`).join('\n')} agar menjadi anak pungut...`)
                for (let i = 0; i < mentionedJidList.length; i++) {
                    if (groupAdmins.includes(mentionedJidList[i])) return await aruga.sendText(from, 'Gagal, kamu tidak bisa mengeluarkan admin grup.')
                    await aruga.removeParticipant(groupId, mentionedJidList[i])
                }
                break`

**Comment by Gimenz** [comment]
kick udah normal lagi, udah di patch sama maintainer nya

**Comment by Fucksociety666** [comment]
welcome pada bug gk??

**Comment by thoriqazzikra** [comment]
> welcome pada bug gk??

masih keknya
cmn ane gatau, soalnya udh ga pake welcome on, otomatis aja kalo ada yg masuk tinggal send photo akwowko

**Comment by ferhacks** [comment]
Could you send me the code of the "! profile"?

**Comment by ferhacks** [comment]
> ![Screenshot pada 2020-12-09 12-56-02](https://user-images.githubusercontent.com/74858900/101590948-469d3780-39e3-11eb-8c75-0952e6854ae8.png)
> iya bjirr

Could you send me the code of the "! profile"?

**Comment by thoriqazzikra** [comment]
> > ![Screenshot pada 2020-12-09 12-56-02](https://user-images.githubusercontent.com/74858900/101590948-469d3780-39e3-11eb-8c75-0952e6854ae8.png)
> > iya bjirr
> 
> Could you send me the code of the "! profile"?

Profile got error, for me, there is nothing photo includes in bot message

**Comment by Fucksociety666** [comment]
punya saya tidak error cuman delay

**Comment by Fucksociety666** [comment]
> > welcome pada bug gk??
> 
> masih keknya
> cmn ane gatau, soalnya udh ga pake welcome on, otomatis aja kalo ada yg masuk tinggal send photo akwowko

owhh

**Comment by thoriqazzikra** [comment]
> punya saya tidak error cuman delay

Iya skrng udh engga, semalem url fotonya gada

**Comment by thoriqazzikra** [comment]
> > ![Screenshot pada 2020-12-09 12-56-02](https://user-images.githubusercontent.com/74858900/101590948-469d3780-39e3-11eb-8c75-0952e6854ae8.png)
> > iya bjirr
> 
> Could you send me the code of the "! profile"?

Check my pull request
