### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kingsalman99** [ArugaZ/whatsapp-bot#197]
scan qr use linux not working ,
diem doang anjir wa nya gak nyaut ,
aku coba di chrome web.whatsapp.com bisa

tapi di bot gak bisa
hampir smua bot aku coba gak bisa scan qr , iam use linux ubuntu 18.04

**Comment by m1dark** [comment]
Make sure all the necessary dependencies are installed: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

Fix Stuck on linux, install google chrome stable:

> wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
> sudo apt install ./google-chrome

**Comment by Fucksociety666** [comment]
> scan qr use linux not working ,
> diem doang anjir wa nya gak nyaut ,
> aku coba di chrome web.whatsapp.com bisa
> 
> tapi di bot gak bisa
> hampir smua bot aku coba gak bisa scan qr , iam use linux ubuntu 18.04

rm -rf node_modules
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome
npm install
node index.js

**Comment by ArugaZ** [comment]
kabari gan

**Comment by kingsalman99** [comment]
![Screenshot_2020-12-11-11-22-29-95](https://user-images.githubusercontent.com/58569784/101861684-3d5ac900-3ba3-11eb-89e5-11d8875d0b44.jpg)
masi sama ,wa nya kga bisa di scan qr nya

**Comment by Fucksociety666** [comment]
> ![Screenshot_2020-12-11-11-22-29-95](https://user-images.githubusercontent.com/58569784/101861684-3d5ac900-3ba3-11eb-89e5-11d8875d0b44.jpg)
> masi sama ,wa nya kga bisa di scan qr nya

pantesan code qrnya aja gk jelas gmbrnya,, coba runingnya di terminal laptop gk ush di remote

**Comment by kingsalman99** [comment]
sama aja ,aku make vnc di leptop juga gtu..
tapi kalo di window belom nyoba sih

**Comment by kingsalman99** [comment]
> > ![Screenshot_2020-12-11-11-22-29-95](https://user-images.githubusercontent.com/58569784/101861684-3d5ac900-3ba3-11eb-89e5-11d8875d0b44.jpg)
> > masi sama ,wa nya kga bisa di scan qr nya
> 
> pantesan code qrnya aja gk jelas gmbrnya,, coba runingnya di terminal laptop gk ush di remote,
> 
> scan QR di terminal laptop>hbis itu di remote

kalo kemaren mah masi bisa pak ,aku make bot-whatsapp yang slavyan-bot di vnc juga

**Comment by Fucksociety666** [comment]
coba aj di window
