### ISSUE TITLE
HELP 

### ISSUE THREAD

**Issue by ShinzX** [ArugaZ/whatsapp-bot#199]
Ytmp3/4 sama play nya di fix gan :)

**Comment by Fucksociety666** [comment]
beli api keynya

**Comment by Suryapardana** [comment]
> Ytmp3/4 sama play nya di fix gan :)

# [Nih baca](https://github.com/ArugaZ/whatsapp-bot/issues/147#issuecomment-739280389)

**Kalau udah ada issues lama ngapain bikin issues baru!**
**Baca tuh!!**

**Comment by ShinzX** [comment]
> > Ytmp3/4 sama play nya di fix gan :)
> 
> # [Nih baca](https://github.com/ArugaZ/whatsapp-bot/issues/147#issuecomment-739280389)
> **Kalau udah ada issues lama ngapain bikin issues baru!**
> **Baca tuh!!**

Lahh ngamukk

**Comment by Suryapardana** [comment]
Lah masih g di close

**Comment by mioscape** [comment]
Sebelum bikin ISSUES baru, coba dibaca dulu ISSUES sebelumnya. Silahkan untuk men-close Issues ini, Terimakasih.
