### ISSUE TITLE
mampir dulu dah sekalian bilang ada yg error

### ISSUE THREAD

**Issue by ferlitopym** [ArugaZ/whatsapp-bot#20]
fitur yang error

- jsolat
- cuaca ( cannot read property "tempat" )
- ceklokasi ( cannon read property "type" )

sementara sih itu gatau juga, intinya mampir hehe
semoga sukses mas ruga

**Comment by iksanriyanto** [comment]
> fitur yang error
> 
> * jsolat
> * cuaca ( cannot read property "tempat" )
> * ceklokasi ( cannon read property "type" )
> 
> sementara sih itu gatau juga, intinya mampir hehe
> semoga sukses mas ruga

Ente yang nekopoi error gak ?

**Comment by ArugaZ** [comment]
> fitur yang error
> 
> * jsolat
> * cuaca ( cannot read property "tempat" )
> * ceklokasi ( cannon read property "type" )
> 
> sementara sih itu gatau juga, intinya mampir hehe
> semoga sukses mas ruga

oke nt saya benerin

**Comment by ArugaZ** [comment]
> fitur yang error
> 
> * jsolat
> * cuaca ( cannot read property "tempat" )
> * ceklokasi ( cannon read property "type" )
> 
> sementara sih itu gatau juga, intinya mampir hehe
> semoga sukses mas ruga

untuk cek lokasi harus kirim lokasi dlu baru reply dengan ceklokasi

**Comment by shinz404** [comment]
Kalo ada member masuk / keluar, bot nya suka spam sendiri, di fix lagi gan, yang lainnya udah bagus kok :)

**Comment by ferlitopym** [comment]
> Kalo ada member masuk / keluar, bot nya suka spam sendiri, di fix lagi gan, yang lainnya udah bagus kok :)

gabisa kecuali lu kasih timesleep di welcome + leave
soalnya net tetep berjalan,dan mungkin sinyal hplu lag makanya jadi spam

mending matiin aja fitur itu

**Comment by ferlitopym** [comment]
> Ente yang nekopoi error gak ?

ngga bisa gan wkwkwk @iksanriyanto

**Comment by ArugaZ** [comment]
yang nekopoi nt ane scrape ulang

**Comment by ArugaZ** [comment]
> fitur yang error
> 
> * jsolat
> * cuaca ( cannot read property "tempat" )
> * ceklokasi ( cannon read property "type" )
> 
> sementara sih itu gatau juga, intinya mampir hehe
> semoga sukses mas ruga

udh gan, makasih bnyk

**Comment by shinz404** [comment]
> > Kalo ada member masuk / keluar, bot nya suka spam sendiri, di fix lagi gan, yang lainnya udah bagus kok :)
> 
> gabisa kecuali lu kasih timesleep di welcome + leave
> soalnya net tetep berjalan,dan mungkin sinyal hplu lag makanya jadi spam
> 
> mending matiin aja fitur itu @shinz404
> **untuk sementara**

Owhh okk, terimakasih gan
