### ISSUE TITLE
!play EROR 

### ISSUE THREAD

**Issue by SyauqiR** [ArugaZ/whatsapp-bot#206]
bang kenapa ya pas aku pake !play,!ytmp3,!ytmp4,!nekopoi,!brainly ko eror yak?

**Comment by MrPawNO** [comment]
> bang kenapa ya pas aku pake !play,!ytmp3,!ytmp4,!nekopoi,!brainly ko eror yak?

play,ytmp3,ytmp4 emang lagi error.. pakai api lain dulu

**Comment by BimaAdinirma** [comment]
> > bang kenapa ya pas aku pake !play,!ytmp3,!ytmp4,!nekopoi,!brainly ko eror yak?
> 
> play,ytmp3,ytmp4 emang lagi error.. pakai api lain dulu

gimana bg?

**Comment by Tanaka9531** [comment]
> > bang kenapa ya pas aku pake !play,!ytmp3,!ytmp4,!nekopoi,!brainly ko eror yak?
> 
> play,ytmp3,ytmp4 emang lagi error.. pakai api lain dulu

Bang Mau Tanya Kalau Mau Ubah Kayak Link ini https://i.waifu.pics/yMRfqOV.gif ke Sticker Gif Gimana Yah ?

**Comment by Tanaka9531** [comment]
> > > bang kenapa ya pas aku pake !play,!ytmp3,!ytmp4,!nekopoi,!brainly ko eror yak?
> > 
> > 
> > play,ytmp3,ytmp4 emang lagi error.. pakai api lain dulu
> 
> Bang Mau Tanya Kalau Mau Ubah Kayak Link ini https://i.waifu.pics/yMRfqOV.gif ke Sticker Gif Gimana Yah ?

Kalau Bisa Buatin Case Nya Makasih

**Comment by SyauqiR** [comment]
kalo udah up kabar" dong

**Comment by MrPawNO** [comment]
> > > bang kenapa ya pas aku pake !play,!ytmp3,!ytmp4,!nekopoi,!brainly ko eror yak?
> > 
> > 
> > play,ytmp3,ytmp4 emang lagi error.. pakai api lain dulu
> 
> gimana bg?

https://st4rz.herokuapp.com

**Comment by lockthed00r** [comment]
> > > > bang kenapa ya pas aku pake !play,!ytmp3,!ytmp4,!nekopoi,!brainly ko eror yak?
> > > 
> > > 
> > > play,ytmp3,ytmp4 emang lagi error.. pakai api lain dulu
> > 
> > 
> > gimana bg?
> 
> https://st4rz.herokuapp.com

![Screenshot_16](https://user-images.githubusercontent.com/76064861/102559308-26b3f500-4102-11eb-962d-da2af674df08.png)
yang harus diubah di script nya apa aja ya sob ?  biar jalan

**Comment by SyauqiR** [comment]
caranya bosss
@MrPawNO
