### ISSUE TITLE
Help Me Plis

### ISSUE THREAD

**Issue by Tanaka9531** [ArugaZ/whatsapp-bot#215]
Tolong Buatin case nya plis https://neko-love.xyz/api/v1/cry
makasih

**Comment by thoriqazzikra** [comment]
> Tolong Buatin case nya plis https://neko-love.xyz/api/v1/cry
> makasih

nama fiturnya apa?

**Comment by Tanaka9531** [comment]
> > Tolong Buatin case nya plis https://neko-love.xyz/api/v1/cry 
> > makasih
> 
> nama fiturnya apa?

nama fiturnya kasi nama aja crygif

**Comment by shansekai** [comment]
> > > Tolong Buatin case nya plis https://neko-love.xyz/api/v1/cry
> > > makasih
> > 
> > 
> > nama fiturnya apa?
> 
> nama fiturnya kasi nama aja crygif

case 'gifcry':         
          axios.get('https://neko-love.xyz/api/v1/cry')
          .then(async(rest) => {
          aruga.sendStickerfromUrl(from, rest.data.url)
        .catch(() => {
                aruga.reply(from, 'Sepertinya server sedang error', id)
            })
          })
            break

**Comment by Tanaka9531** [comment]
> > > > Tolong Buatin case nya plis https://neko-love.xyz/api/v1/cry 
> > > > makasih
> > > 
> > > 
> > > nama fiturnya apa?
> > 
> > 
> > fitur nama kasi nama aja crygif
> 
> case 'gifcry': 
> axios.get (' https://neko-love.xyz/api/v1/cry ') 
> . lalu (async (rest) => { 
> aruga.sendStickerfromUrl (from, rest.data.url) 
> . catch (() => { 
> aruga.reply (from, 'he server sedang error', id) 
> }) 
> }) 
> break

Makasih
