### ISSUE TITLE
CARA DELETE SESSION GIMANA?

### ISSUE THREAD

**Issue by thoriqazzikra** [ArugaZ/whatsapp-bot#219]
jadi gini
tadi nomer bot wa ane diblok sama whatsapp, nah itu pas diblok masih dalam mode bot
nah terus mau gnti botnya itu saya gatau, malah stuck di authenticating, harus nunggu nomer bot yg satunya baru bisa lolos

COMMAND BUAT RESTART SESSION ATAU CARA DELETE SESSION ITU GIMANA NGAB HELP:)

**Comment by Tanaka9531** [comment]
Coba delet file ARUGA.data.json

**Comment by thoriqazzikra** [comment]
> Coba delet file ARUGA.data.json

malah ga muncul authenticate ke whatsappnya

ehh sklian mau nanya
cara convert url html jadi kebaca di javascript gmna?
