### ISSUE TITLE
Mau Nanya

### ISSUE THREAD

**Issue by Rimuru9531** [ArugaZ/whatsapp-bot#22]
Bang Itu Ceklokasi knp yah gini
![bandicam 2020-11-11 23-44-55-410](https://user-images.githubusercontent.com/73052642/98839441-1c099e80-2478-11eb-9b44-23fad4174c46.jpg)

**Comment by ArugaZ** [comment]
> Bang Itu Ceklokasi knp yah gini
> ![bandicam 2020-11-11 23-44-55-410](https://user-images.githubusercontent.com/73052642/98839441-1c099e80-2478-11eb-9b44-23fad4174c46.jpg)

kirim lokasi, lalu reply dengan ceklokasi

**Comment by ArugaZ** [comment]
nt saya benerin
