### ISSUE TITLE
Bang mau req

### ISSUE THREAD

**Issue by SyauqiR** [ArugaZ/whatsapp-bot#225]
kalo pesan di dalate di grub akan ke tau an,dan akan mucul kembali,sama menu welcome ku ga berfungsi,info bg

**Comment by ShinzX** [comment]
> kalo pesan di dalate di grub akan ke tau an,dan akan mucul kembali,sama menu welcome ku ga berfungsi,info bg


Iyaa welcome ga berfungsi
