### ISSUE TITLE
Aruga Kok Rest Api Mu Error

### ISSUE THREAD

**Issue by Tanaka9531** [ArugaZ/whatsapp-bot#229]

**Comment by ILHAMBISAMAR** [comment]
iya bner broo apikey nya kok error ya?

**Comment by chuaky** [comment]
iya kok error ya? masih bisa di perbaiki ga tuh?

**Comment by dikanata** [comment]
Iyaa bang error, semoga cepet diperbaikin

**Comment by sFauzan** [comment]
itu kah yang bikin sebagian command ngga jalan? dan juga

(node:9728) UnhandledPromiseRejectionWarning: Error: Request failed with status code 503
    at createError (C:\whatsapp-bot\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\whatsapp-bot\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\whatsapp-bot\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:9728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Saya masih awam bang

**Comment by thoriqazzikra** [comment]
> itu kah yang bikin sebagian command ngga jalan? dan juga
> 
> (node:9728) UnhandledPromiseRejectionWarning: Error: Request failed with status code 503
> at createError (C:\whatsapp-bot\node_modules\axios\lib\core\createError.js:16:15)
> at settle (C:\whatsapp-bot\node_modules\axios\lib\core\settle.js:17:12)
> at IncomingMessage.handleStreamEnd (C:\whatsapp-bot\node_modules\axios\lib\adapters\http.js:260:11)
> at IncomingMessage.emit (events.js:215:7)
> at endReadableNT (_stream_readable.js:1183:12)
> at processTicksAndRejections (internal/process/task_queues.js:80:21)
> (node:9728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:9728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> Saya masih awam bang

Itu syntax keknya
