### ISSUE TITLE
Bnyk yg error ngab

### ISSUE THREAD

**Issue by thoriqazzikra** [ArugaZ/whatsapp-bot#234]
Rest api?

**Comment by dxxoo** [comment]
Pake Rest Api vhtear aja Bro

**Comment by fikrin36** [comment]
> Pake Rest Api vhtear aja Bro

bagii lahkey  apinya ahhahaha

**Comment by thoriqazzikra** [comment]
> > Pake Rest Api vhtear aja Bro
> 
> bagii lahkey apinya ahhahaha

Bjirrr pencuri:v
