### ISSUE TITLE
Announcement❤️

### ISSUE THREAD

**Issue by ArugaZ** [ArugaZ/whatsapp-bot#237]
Saya tidak akan mengupdate repos ini lagi namun saya akan tetap membantu jika ada masalah bug atau semacamnya, mungkin nanti akan dilanjutkan oleh teman. Rest Api akan tetap berjalan, sabar aja nanti juga diperbarui. Terima kasih telah membantu membangun repos ini.

Ohya saya akan membuat tutorial-tutorial mengenai pemrograman
Bantu youtube channel saya ya, butuh kritik dan saran.
Channel :  [KocakZ](https://www.youtube.com/c/kocakz)

**Comment by dikanata** [comment]
oke kak, terima kasih telah membuat repo ini, cukup membantu saya mempelajari cara membuat bot wa :)

**Comment by HAFizh-15** [comment]
terima kasih banyak bwang baseny, bisa di kembangin

**Comment by MSI0072** [comment]
udah ku subs ngab, thanks rest api nya

**Comment by chuaky** [comment]
> tengkyu

https://arugaytdl.herokuapp.com/search?q= yg ini masih error bg....

**Comment by MSI0072** [comment]
nggab fitur anti spam sticker error

error :
[EROR] ReferenceError: serial is not defined
at HandleMsg (D:\IT\BOT\BOT 5\whatsapp-bot\HandleMsg.js:271:34)
at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by jamet1337** [comment]
Minta rest api buat search engine bro
