### ISSUE TITLE
REQUEST FEATURE ⛳

### ISSUE THREAD

**Issue by ArugaZ** [ArugaZ/whatsapp-bot#24]
yang mau request disini ya

**Comment by iksanriyanto** [comment]
Saran fitur
-simisimi (biar lebih interaktif)
-clone profil orang 
-xnxx (wkwkwkwkwk)
Udah sih yes

**Comment by harieyadi** [comment]
Reues simsimi, sticker text, serch google image, terimakasih

**Comment by mioscape** [comment]
> Saran fitur
> -simisimi (biar lebih interaktif)
> -clone profil orang 
> -xnxx (wkwkwkwkwk)
> Udah sih yes 

Meh, pornhub a lot better

**Comment by ferlitopym** [comment]
Saran dari ane

- text to sticker
- sticker to image

udh itu doang mybe

**Comment by ferlitopym** [comment]
> Meh, pornhub a lot better

mehh, xvid better XD

**Comment by uukdesu** [comment]
![WhatsApp Image 2020-11-12 at 1 59 00 PM](https://user-images.githubusercontent.com/54493113/98906699-27001580-24f0-11eb-8dda-3c42ac9e2217.jpeg)


> > Saran fitur
> > -simisimi (biar lebih interaktif)
> > -clone profil orang
> > -xnxx (wkwkwkwkwk)
> > Udah sih yes
> 
> Meh, pornhub a lot better

pornhub yg kemaren bisa, tapi link streamingnya forbidden

**Comment by iksanriyanto** [comment]
> ![WhatsApp Image 2020-11-12 at 1 59 00 PM](https://user-images.githubusercontent.com/54493113/98906699-27001580-24f0-11eb-8dda-3c42ac9e2217.jpeg)
> 
> > > Saran fitur
> > > -simisimi (biar lebih interaktif)
> > > -clone profil orang
> > > -xnxx (wkwkwkwkwk)
> > > Udah sih yes
> > 
> > 
> > Meh, pornhub a lot better
> 
> pornhub yg kemaren bisa, tapi link streamingnya forbidden

Kok ada fitur pornhub nya? Pnyaku cuman ada nekopoi

**Comment by uukdesu** [comment]
@iksanriyanto update sebelumnya ada, tapi diilangin karena banyak yg error. w juga kurang tau

**Comment by iksanriyanto** [comment]
> @iksanriyanto update sebelumnya ada, tapi diilangin karena banyak yg error. w juga kurang tau

Pengen dong source yg masih ada ph nya hahaha

**Comment by bdrsmsdn** [comment]
fitur nulis tambahin bahasa lain, jadi nulis bahasa korea arab etc

**Comment by RzkyO** [comment]
fiture lirik lagu
api: https://api.i-tech.id/ or https://documenter.getpostman.com/view/10780576/T1Ds9bRV?version=latest#2e9b80b0-bbaf-43c5-881c-f7b483d07d0a
info gempa
api: https://api.i-tech.id/ or http://st4rz.herokuapp.com/
brainly
api: https://api.i-tech.id/ or https://api.i-tech.id/
tiktok video download no wm
api: http://st4rz.herokuapp.com/

**Comment by ArugaZ** [comment]
> ![WhatsApp Image 2020-11-12 at 1 59 00 PM](https://user-images.githubusercontent.com/54493113/98906699-27001580-24f0-11eb-8dda-3c42ac9e2217.jpeg)
> 
> > > Saran fitur
> > > -simisimi (biar lebih interaktif)
> > > -clone profil orang
> > > -xnxx (wkwkwkwkwk)
> > > Udah sih yes
> > 
> > 
> > Meh, pornhub a lot better
> 
> pornhub yg kemaren bisa, tapi link streamingnya forbidden

tp saya aneh, knp yng lain bnyk yg gbisa pas installasi module

**Comment by mioscape** [comment]
> > ![WhatsApp Image 2020-11-12 at 1 59 00 PM](https://user-images.githubusercontent.com/54493113/98906699-27001580-24f0-11eb-8dda-3c42ac9e2217.jpeg)
> > 
> > > > Saran fitur
> > > > -simisimi (biar lebih interaktif)
> > > > -clone profil orang
> > > > -xnxx (wkwkwkwkwk)
> > > > Udah sih yes
> > > 
> > > 
> > > Meh, pornhub a lot better
> > 
> > pornhub yg kemaren bisa, tapi link streamingnya forbidden
> 
> tp saya aneh, knp yng lain bnyk yg gbisa pas installasi module

Coba aja di commit ulang👀

**Comment by ArugaZ** [comment]
> fiture lirik lagu
> api: https://api.i-tech.id/ or https://documenter.getpostman.com/view/10780576/T1Ds9bRV?version=latest#2e9b80b0-bbaf-43c5-881c-f7b483d07d0a
> info gempa
> api: https://api.i-tech.id/ or http://st4rz.herokuapp.com/
> brainly
> api: https://api.i-tech.id/ or https://api.i-tech.id/
> tiktok video download no wm
> api: http://st4rz.herokuapp.com/

info gempa saya sdh ada, untuk tiktok lg error

**Comment by ArugaZ** [comment]
> > > ![WhatsApp Image 2020-11-12 at 1 59 00 PM](https://user-images.githubusercontent.com/54493113/98906699-27001580-24f0-11eb-8dda-3c42ac9e2217.jpeg)
> > > > > Saran fitur
> > > > > -simisimi (biar lebih interaktif)
> > > > > -clone profil orang
> > > > > -xnxx (wkwkwkwkwk)
> > > > > Udah sih yes
> > > > 
> > > > 
> > > > Meh, pornhub a lot better
> > > 
> > > 
> > > pornhub yg kemaren bisa, tapi link streamingnya forbidden
> > 
> > 
> > tp saya aneh, knp yng lain bnyk yg gbisa pas installasi module
> 
> Coba aja di commit ulang👀

xixixi nt ane commit ulang di new branch

**Comment by RzkyO** [comment]
> > fiture lirik lagu
> > api: https://api.i-tech.id/ or https://documenter.getpostman.com/view/10780576/T1Ds9bRV?version=latest#2e9b80b0-bbaf-43c5-881c-f7b483d07d0a
> > info gempa
> > api: https://api.i-tech.id/ or http://st4rz.herokuapp.com/
> > brainly
> > api: https://api.i-tech.id/ or https://api.i-tech.id/
> > tiktok video download no wm
> > api: http://st4rz.herokuapp.com/
> 
> info gempa saya sdh ada, untuk tiktok lg error

oke siap bro :D

**Comment by Rimuru9531** [comment]
Api Nulis Apa ??

**Comment by TigerManC1** [comment]
Request fitur

• Doujin Downloader
• Xp(total chating) 
    Kayak bot di discord gitu lah

Play

• Economy(money, xp, job, dll) 

Dah gitu doang maybe:)

**Comment by ArugaZ** [comment]
> Request fitur
> 
> • Doujin Downloader
> • Xp(total chating)
> Kayak bot di discord gitu lah
> 
> Play
> 
> • Economy(money, xp, job, dll)
> 
> Dah gitu doang maybe:)

okeii

**Comment by arh-space** [comment]
Request :

- Brainly
- Search Lirik
- text to QR
- tiktok & twitter downloader
- google search
- daily limit

Please :))

**Comment by Rimuru9531** [comment]
Wallpaper anime hd

**Comment by mioscape** [comment]
> Wallpaper anime hd 

Ga bisa kayanya, btw ini issue udah tutup

**Comment by bdrsmsdn** [comment]
REQUEST TTP BANG

**Comment by RzkyO** [comment]
Request fiture bot auto restart ulang dong tiap 15menit soalnya kadang kadang kalo on terus suka ga jalan kaya ngestuck walaupun udah command #menu
