### ISSUE TITLE
req tiktok borr(:

### ISSUE THREAD

**Issue by SyauqiR** [arugaz/whatsapp-bot#244]

**Comment by SyauqiR** [comment]
sama instagram

**Comment by JustPandaEver** [comment]
Awokwokwokwok si syauqi muncul

**Comment by SyauqiR** [comment]
apa mek wkwk

Sel, 29 Des 2020 pukul 14.26 PandaEver <notifications@github.com> menulis:

**Comment by Tanaka9531** [comment]
https://github.com/ArugaZ/whatsapp-bot/issues/245

**Comment by GuckTubeYT** [comment]
wah, tiktokers nih

**Comment by ArugaZ** [comment]
cek di rest api yang baru udh saya tambahkan :))

**Comment by Urbaee** [comment]
> sama instagram

sad:v ig nya belom bisa:v

**Comment by ArugaZ** [comment]
> > sama instagram
> 
> sad:v ig nya belom bisa:v

harus login dlu pas buka ig nya jd gbs wkwk
