### ISSUE TITLE
Update by PandaEver

### ISSUE THREAD

**Issue by JustPandaEver** [arugaz/whatsapp-bot#245]
case 'bc': 
            if (!isOwnerBot) return aruga.reply(from, 'heh, siapa ini bukan owner Bot main suruh', id)
            if (args.length == 0) return aruga.reply(from, `Untuk broadcast ke semua chat ketik:\n${prefix}bc [isi chat]`)
            let msg = body.slice(4)
            const chatz = await aruga.getAllChatIds()
            if(quotedMsg && quotedMsg.type == 'image'){                             const mediaData = await decryptMedia(quotedMsg)                                                                                 const imageBase64 = `data:${quotedMsg.mimetype};base64,${mediaData.toString('base64')}`
                    for (let idk of chatz) {
                        var cvk = await aruga.getChatById(idk)
                        if (!cvk.isReadOnly) aruga.sendImage(idk, imageBase64, 'gambar.jpeg', `〘 *PandaEver* 〙\n\n${msg}`)                            if (cvk.isReadOnly) aruga.sendImage(idk, imageBase64, 'gambar.jpeg', `〘 *PandaEver* 〙\n\n${msg}`)
                }                                                               aruga.reply(from, 'Broadcast Success!', id)
            }else{
                    for(let idk of chatz){                                              var cvk = await aruga.getChatById(idk)                          if(!cvk.isReadOnly) aruga.sendText(idk, `〘 *PandaEver* 〙\n\n${msg}`)
                    }
                            aruga.reply('Broadcast Success!')                   }                                                           break

**Comment by JustPandaEver** [comment]
untuk lebih lanjut pm https://wa.me/6282278103764

**Comment by JustPandaEver** [comment]
case 'tiktok':
              if (args.length !== 1) return aruga.reply(from, `Ada Yang Salah Coba Priksa Kembali Url Anda`)
                        arugaapi.tik(args[0])
                        .then(async(res) => {
                                await aruga.sendFileFromUrl(from, `${res.mp4direct}`, '', '', id)                                                       })
                        break

**Comment by JustPandaEver** [comment]
const tik = async (url) => new Promise((resolve, reject) => {
        axios.get(`http://128.199.72.121/?id=tiktok&key=PandaEver&url=${url}`)
        .then((res) => {
                resolve(res.data)
        })
        .catch((err) => {
                reject(err)
        })
})

**Comment by thoriqazzikra** [comment]
> const tik = async (url) => new Promise((resolve, reject) => {
> axios.get(`http://128.199.72.121/?id=tiktok&key=PandaEver&url=${url}`)
> .then((res) => {
> resolve(res.data)
> })
> .catch((err) => {
> reject(err)
> })
> })

Pull request lah asw ngapain di issues

**Comment by Fucksociety666** [comment]
> > const tik = async (url) => new Promise((resolve, reject) => {
> > axios.get(`http://128.199.72.121/?id=tiktok&key=PandaEver&url=${url}`)
> > .then((res) => {
> > resolve(res.data)
> > })
> > .catch((err) => {
> > reject(err)
> > })
> > })
> 
> Pull request lah asw ngapain di issues

dia gk bisa pull req keknya

**Comment by JustPandaEver** [comment]
> > const tik = async (url) => new Promise((resolve, reject) => {
> > axios.get(`http://128.199.72.121/?id=tiktok&key=PandaEver&url=${url}`)
> > .then((res) => {
> > resolve(res.data)
> > })
> > .catch((err) => {
> > reject(err)
> > })
> > })
> 
> Pull request lah asw ngapain di issues

Ga bisa pull asw udh w test pull

**Comment by JustPandaEver** [comment]
Thoriq memeq

**Comment by SyauqiR** [comment]
jir pada gelud awkaowk anj

**Comment by thoriqazzikra** [comment]
> > > const tik = async (url) => new Promise((resolve, reject) => {
> > > axios.get(`http://128.199.72.121/?id=tiktok&key=PandaEver&url=${url}`)
> > > .then((res) => {
> > > resolve(res.data)
> > > })
> > > .catch((err) => {
> > > reject(err)
> > > })
> > > })
> > 
> > 
> > Pull request lah asw ngapain di issues
> 
> Ga bisa pull asw udh w test pull

Cacat bet anjg ga bisa di pull request

**Comment by JustPandaEver** [comment]
erererer @thoriqazzikra memeq

**Comment by SyauqiR** [comment]
Halo Kuntul

**Comment by JustPandaEver** [comment]
ape mek
