### ISSUE TITLE
Qr dont coming

### ISSUE THREAD

**Issue by ozgurlook** [arugaz/whatsapp-bot#248]
![Screenshot_20201230-194150](https://user-images.githubusercontent.com/76402349/103367837-1d9a2f00-4ad7-11eb-9f72-6caa82771c13.jpg)

**Comment by JustPandaEver** [comment]
hapus node-modules sama aruga.data.json,install ulang + run ulang

**Comment by ferhacks** [comment]
try  install google chrome

**Comment by DevERS-0** [comment]
> hapus node-modules sama aruga.data.json,install ulang + run ulang

Aruga Data itu Yang Mana ;-;

**Comment by omerbeylife** [comment]
I have the same problem on ubuntu 20, what is the solution?
