### ISSUE TITLE
REPORT ERROR / BUG ❤️

### ISSUE THREAD

**Issue by ArugaZ** [ArugaZ/whatsapp-bot#25]
jika kalian menemukan error/bug, kabarin dimari

**Comment by mioscape** [comment]
![Screenshot_20201112-132013121.jpg](https://user-images.githubusercontent.com/43681888/98903260-d2f23280-24e9-11eb-8c73-4872eb92cda4.jpg)

Untuk last commit itu `let datax` nya ndak sekalian di ganti?

**Comment by uukdesu** [comment]
![WhatsApp Image 2020-11-12 at 1 55 05 PM](https://user-images.githubusercontent.com/54493113/98906420-97f2fd80-24ef-11eb-88de-03fe3cb20c8f.jpeg)

ini kenapa bang? command stickergif

**Comment by lockthedoor** [comment]
Pas mau start bot begitu kenapa ya bro ? padahal kemaren kemaren engga
![Screenshot_35](https://user-images.githubusercontent.com/74348067/98913943-a0046a80-24fa-11eb-9171-09ac25a84d16.png)

**Comment by ArugaZ** [comment]
> ![Screenshot_20201112-132013121.jpg](https://user-images.githubusercontent.com/43681888/98903260-d2f23280-24e9-11eb-8c73-4872eb92cda4.jpg)
> 
> Untuk last commit itu `let datax` nya ndak sekalian di ganti?

ngga

**Comment by ArugaZ** [comment]
> ![WhatsApp Image 2020-11-12 at 1 55 05 PM](https://user-images.githubusercontent.com/54493113/98906420-97f2fd80-24ef-11eb-88de-03fe3cb20c8f.jpeg)
> 
> ini kenapa bang? command stickergif

nnga ke proses itu

**Comment by mioscape** [comment]
> Pas mau start bot begitu kenapa ya bro ? padahal kemaren kemaren engga
> ![Screenshot_35](https://user-images.githubusercontent.com/74348067/98913943-a0046a80-24fa-11eb-9171-09ac25a84d16.png)
> 

Itu liat error nya ada di rugaApi.js line 111

**Comment by TheSploit** [comment]
> > Pas mau start bot begitu kenapa ya bro ? padahal kemaren kemaren engga
> > ![Screenshot_35](https://user-images.githubusercontent.com/74348067/98913943-a0046a80-24fa-11eb-9171-09ac25a84d16.png)
> 
> Itu liat error nya ada di rugaApi.js line 111.
> Kalau ndak mau repot clone ulang aja

Untuk atasinya kan errorny di resolve(text tinggal kasih ) diujung (text, jadinya gini resolve(text)

Done xixi

**Comment by ArugaZ** [comment]
> > > Pas mau start bot begitu kenapa ya bro ? padahal kemaren kemaren engga
> > > ![Screenshot_35](https://user-images.githubusercontent.com/74348067/98913943-a0046a80-24fa-11eb-9171-09ac25a84d16.png)
> > 
> > 
> > Itu liat error nya ada di rugaApi.js line 111.
> > Kalau ndak mau repot clone ulang aja
> 
> Untuk atasinya kan errorny di resolve(text tinggal kasih ) diujung (text, jadinya gini resolve(text)
> 
> Done xixi

iy audh ane ubah typo :V

**Comment by uukdesu** [comment]
> > ![WhatsApp Image 2020-11-12 at 1 55 05 PM](https://user-images.githubusercontent.com/54493113/98906420-97f2fd80-24ef-11eb-88de-03fe3cb20c8f.jpeg)
> > 
> > ini kenapa bang? command stickergif
> 
> nnga ke proses itu

solusinya bang? hampir semua kek gitu

**Comment by ArugaZ** [comment]
> > > ![WhatsApp Image 2020-11-12 at 1 55 05 PM](https://user-images.githubusercontent.com/54493113/98906420-97f2fd80-24ef-11eb-88de-03fe3cb20c8f.jpeg)
> > > ini kenapa bang? command stickergif
> > 
> > 
> > nnga ke proses itu
> 
> solusinya bang? hampir semua kek gitu

itu dr prosesnya gagal, ya kl gabisa pake gify-cli nt saya buat prosesnya pake ffmpeg

**Comment by alfiansx** [comment]
fitur nekopoinya error bang?

**Comment by ArugaZ** [comment]
> fitur nekopoinya error bang?

iya ngab blm di scrape ulang

**Comment by habibhantam445** [comment]
![Screenshot_20201113-035733558](https://user-images.githubusercontent.com/74045441/98996083-e4c4eb80-2564-11eb-8707-bdb665bab618.jpg)


Eror Disitu Bro Harus Gmna?

Kondisi Hp Root, Ubuntu 19 Dah w install Chromium ttp gabisa

**Comment by agusydk3** [comment]
Result Alay Ga sesuai ama kalimat bang

**Comment by agusydk3** [comment]
> Result Alay Ga sesuai ama kalimat bang

![image](https://user-images.githubusercontent.com/57493908/99015858-709c3f00-2588-11eb-84e8-b045347c0547.png)

**Comment by ArugaZ** [comment]
> Result Alay Ga sesuai ama kalimat bang

yang bapak font?

**Comment by ArugaZ** [comment]
> Result Alay Ga sesuai ama kalimat bang

bisa kirim foto?

**Comment by iksanriyanto** [comment]
@ArugaZ bang kalo begini salahnya dimana ya "ReferenceError: ramalan is not defined

**Comment by banguucup** [comment]
ReferenceError: url is not defined
    at /home/hafisaroci/botbang/lib/rugaApi.js:130:56
    at new Promise (<anonymous>)
    at Object.tulis (/home/hafisaroci/botbang/lib/rugaApi.js:129:31)
    at HandleMsg (/home/hafisaroci/botbang/HandleMsg.js:273:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

command #nulis kayak gini solusinya bang

**Comment by ArugaZ** [comment]
> ReferenceError: url is not defined
> at /home/hafisaroci/botbang/lib/rugaApi.js:130:56
> at new Promise ()
> at Object.tulis (/home/hafisaroci/botbang/lib/rugaApi.js:129:31)
> at HandleMsg (/home/hafisaroci/botbang/HandleMsg.js:273:42)
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> 
> command #nulis kayak gini solusinya bang

clone ulang bre

**Comment by ArugaZ** [comment]
> @ArugaZ bang kalo begini salahnya dimana ya "ReferenceError: ramalan is not defined

tolong kiirim yang lengkapnya

**Comment by uukdesu** [comment]
![WhatsApp Image 2020-11-13 at 12 38 49 PM](https://user-images.githubusercontent.com/54493113/99035907-2ed4be00-25b3-11eb-933a-46789d496abe.jpeg)

lapor mang, sering mati sendiri

**Comment by banguucup** [comment]
![Screenshot (132)](https://user-images.githubusercontent.com/74356954/99069468-fba92380-25e0-11eb-9331-c6d7a9f17ab2.png)
ini ngaruh gk bang? soalnya nulis jadi gk bisa

**Comment by alvnfaiz** [comment]
![image](https://user-images.githubusercontent.com/17441900/99074189-e1277800-25e9-11eb-96f5-892eaecb1008.png)
Stuck disini mulu

**Comment by RzkyO** [comment]
> ![image](https://user-images.githubusercontent.com/17441900/99074189-e1277800-25e9-11eb-96f5-892eaecb1008.png)
> Stuck disini mulu

kalo kaya gitu setau gua mah di cmd ctrl + c terus npm start aja lagi, gua juga biasa kaya gitu

**Comment by ArugaZ** [comment]
> ![image](https://user-images.githubusercontent.com/17441900/99074189-e1277800-25e9-11eb-96f5-892eaecb1008.png)
> Stuck disini mulu

run ulang coba gan, ane bisa kok

**Comment by alvnfaiz** [comment]
> > ![image](https://user-images.githubusercontent.com/17441900/99074189-e1277800-25e9-11eb-96f5-892eaecb1008.png)
> > Stuck disini mulu
> 
> run ulang coba gan, ane bisa kok

Oke, ini di vps, OS Ubuntu 18
node version v.10^
nvm v.15^
npm v.6^

**Comment by zencats22** [comment]
![Uploading HYPER_20201114_093510_null.jpg…]()
Fitur instagram knp y,tdi malam bisa.maaf difoto doang :"v

**Comment by riintan2** [comment]
> > > ![image](https://user-images.githubusercontent.com/17441900/99074189-e1277800-25e9-11eb-96f5-892eaecb1008.png)
> > > Stuck disini mulu
> > 
> > 
> > run ulang coba gan, ane bisa kok
> 
> Oke, ini di vps, OS Ubuntu 18
> node version v.10^
> nvm v.15^
> npm v.6^

hapus node modulenya dengan node-persistnya bro

**Comment by zencats22** [comment]
Instagram knp g bisa ya ?

**Comment by ArugaZ** [comment]
> Fitur Instagram downloader knp g bisa ya ?,lewat api jg g bisa ko coba

nanti saya benerin apinya

**Comment by MSI0072** [comment]
nggab fitur anti sticker error

error : 
[EROR] ReferenceError: serial is not defined
    at HandleMsg (D:\IT\BOT\BOT 5\whatsapp-bot\HandleMsg.js:271:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
