### ISSUE TITLE
Nih saya buatkan REST API baru

### ISSUE THREAD

**Issue by arugaz** [arugaz/whatsapp-bot#253]
[https://www.arugaz.my.id/api](https://www.arugaz.my.id/api)
`yang mau request bisa langsung chat aja 👍  gratis`

**Comment by MSI0072** [comment]
Thanks bang

**Comment by Urbaee** [comment]
server api nya down?

**Comment by juwenaja** [comment]
apinya down

**Comment by ArugaZ** [comment]
update : https://kocakz.herokuapp.com/api

**Comment by ArugaZ** [comment]
fitur youtube semua bisa, tiktok, ig, text pro dll :)

**Comment by ArugaZ** [comment]
mau website apa yang ingin di scrape nt saya masukin ke rest apinya

**Comment by Urbaee** [comment]
> mau website apa yang ingin di scrape nt saya masukin ke rest apinya

Yg mp3 emg ngirim file ya ngab?

**Comment by Urbaee** [comment]
> mau website apa yang ingin di scrape nt saya masukin ke rest apinya

filmapik

**Comment by MSI0072** [comment]
> fitur youtube semua bisa, tiktok, ig, text pro dll :)

ngab result dari  pornhub scrapper ga bisa di bukak di pornhub detail

**Comment by MSI0072** [comment]
![image](https://user-images.githubusercontent.com/63404067/104125145-80b57c80-5387-11eb-920e-8115128a4921.png)
error bang

**Comment by ArugaZ** [comment]
pake web ini aja : [http://arugaz.my.id/api](http://arugaz.my.id/api)

**Comment by ArugaZ** [comment]
kabarin ngab :)

**Comment by mrfzvx12** [comment]
Cara ngambil pictnya gimana kalo bentuk script nya seperti ini..

if (text.includes('.tes')){
const teks = text.replace(/.tes /, "")
axios.get(`https://kocakz.herokuapp.com/api/textpro/luxury?text=${teks}`)
    .then((res) => {
      imageToBase64(res.data)
        .then(
          (ress) => {
            var buf = Buffer.from(ress, 'base64')
            conn.sendMessage(id, buf, MessageType.image, { quoted: m } )
        })
    })
}

**Comment by ArugaZ** [comment]
> Cara ngambil pictnya gimana kalo bentuk script nya seperti ini..
> 
> if (text.includes('.tes')){
> const teks = text.replace(/.tes /, "")
> axios.get(`https://kocakz.herokuapp.com/api/textpro/luxury?text=${teks}`)
> .then((res) => {
> imageToBase64(res.data)
> .then(
> (ress) => {
> var buf = Buffer.from(ress, 'base64')
> conn.sendMessage(id, buf, MessageType.image, { quoted: m } )
> })
> })
> }

Pakai bent aja gan, npm i --save bent --no-fund

`const bent = require('bent')

const BufferData = await bent('buffer')('https://www.arugaz.my.id/api/textpro/luxury?text=aruga')
conn.sendMessage(id, BufferData, MessageType.image, { quoted: m } )
`

**Comment by ArugaZ** [comment]
> > Cara ngambil pictnya gimana kalo bentuk script nya seperti ini..
> > if (text.includes('.tes')){
> > const teks = text.replace(/.tes /, "")
> > axios.get(`https://kocakz.herokuapp.com/api/textpro/luxury?text=${teks}`)
> > .then((res) => {
> > imageToBase64(res.data)
> > .then(
> > (ress) => {
> > var buf = Buffer.from(ress, 'base64')
> > conn.sendMessage(id, buf, MessageType.image, { quoted: m } )
> > })
> > })
> > }
> 
> Pakai bent aja gan, npm i --save bent --no-fund
> 
> `const bent = require('bent')
> 
> const BufferData = await bent('buffer')('https://www.arugaz.my.id/api/textpro/luxury?text=aruga')
> conn.sendMessage(id, BufferData, MessageType.image, { quoted: m } )
> `



> > mau website apa yang ingin di scrape nt saya masukin ke rest apinya
> 
> Yg mp3 emg ngirim file ya ngab?

youtube dh bisa semua, ig kena limit entah

**Comment by Urbaee** [comment]
> > > Cara ngambil pictnya gimana kalo bentuk script nya seperti ini..
> > > if (text.includes('.tes')){
> > > const teks = text.replace(/.tes /, "")
> > > axios.get(`https://kocakz.herokuapp.com/api/textpro/luxury?text=${teks}`)
> > > .then((res) => {
> > > imageToBase64(res.data)
> > > .then(
> > > (ress) => {
> > > var buf = Buffer.from(ress, 'base64')
> > > conn.sendMessage(id, buf, MessageType.image, { quoted: m } )
> > > })
> > > })
> > > }
> > 
> > 
> > Pakai bent aja gan, npm i --save bent --no-fund
> > `const bent = require('bent')
> > const BufferData = await bent('buffer')('https://www.arugaz.my.id/api/textpro/luxury?text=aruga')
> > conn.sendMessage(id, BufferData, MessageType.image, { quoted: m } )
> > `
> 
> > > mau website apa yang ingin di scrape nt saya masukin ke rest apinya
> > 
> > 
> > Yg mp3 emg ngirim file ya ngab?
> 
> youtube dh bisa semua, ig kena limit entah

Yg video bisa, cmn yg audio ngirim file

**Comment by SyzuTopia54y** [comment]
Source apikey brp?

**Comment by mrfzvx12** [comment]
Yang mau request gratis.. 🤔
Api pinterest scraper..

**Comment by ArugaZ** [comment]
> > mau website apa yang ingin di scrape nt saya masukin ke rest apinya
> 
> filmapik

web nya?

**Comment by ArugaZ** [comment]
> Yang mau request gratis.. 🤔
> Api pinterest video scraper..

pinterest video scraper?

**Comment by ArugaZ** [comment]
> Source apikey brp?

gada apikey :>

**Comment by Urbaee** [comment]
> > > mau website apa yang ingin di scrape nt saya masukin ke rest apinya
> > 
> > 
> > filmapik
> 
> web nya?

http://103.194.171.18/

**Comment by ArugaZ** [comment]
> > > > mau website apa yang ingin di scrape nt saya masukin ke rest apinya
> > > 
> > > 
> > > filmapik
> > 
> > 
> > web nya?
> 
> http://103.194.171.18/

udh saya tambahin, silahkan di cek
[Scraper](https://arugaz.my.id/api/media/filmapik/search?query=fast%20and%20furious)
[Detail](https://arugaz.my.id/api/media/filmapik/detail?url=http://103.194.171.18/tenet/play)

**Comment by Urbaee** [comment]
> > > > > mau website apa yang ingin di scrape nt saya masukin ke rest apinya
> > > > 
> > > > 
> > > > filmapik
> > > 
> > > 
> > > web nya?
> > 
> > http://103.194.171.18/
> 
> udh saya tambahin, silahkan di cek
> [Scraper](https://arugaz.my.id/api/media/filmapik/search?query=fast%20and%20furious)
> [Detail](https://arugaz.my.id/api/media/filmapik/detail?url=http://103.194.171.18/tenet/play)

Cepet bgt bang😂
Makasih yak

**Comment by mrfzvx12** [comment]
Req download video pinterest 🙏🏻

**Comment by ArugaZ** [comment]
> Req download video pinterest 🙏🏻

oke aga lama yaa lg scrape joox, spotify dan soundcloud

**Comment by mrfzvx12** [comment]
> > Req download video pinterest 🙏🏻
> 
> oke aga lama yaa lg scrape joox, spotify dan soundcloud

> Wih mantap.. oke bang.. santai

**Comment by mrfzvx12** [comment]
> >  Req download video pinterest 🙏🏻
>
> 
>  oke aga lama yaa lg scrape joox, spotify dan soundcloud
 
>  Wih mantap.. oke bang.. santai

> Untuk puisi sama cerpen cemana bang.. ilang kah ?

**Comment by MSI0072** [comment]
bang bisa req scraper google classroom nga hehe

**Comment by Urbaee** [comment]
> > Req download video pinterest 🙏🏻
> 
> oke aga lama yaa lg scrape joox, spotify dan soundcloud

bang, kalo bisa yang youtube audio2 dikecilin lagi aja bang resolusinya

**Comment by TheSploit** [comment]
> 
> 
> https://www.arugaz.my.id/api
> `yang mau request bisa langsung chat aja 👍 gratis`

Pak Req Cerita Urban legend or Cerita horror xixi

**Comment by Urbaee** [comment]
tambahin drakor bang

link : https://mydramalist.com/

**Comment by ArugaZ** [comment]
okeyy nanti yaa

Pada tanggal Sen, 25 Jan 2021 17.17, Thoriq Azzikra <
notifications@github.com> menulis:

**Comment by MSI0072** [comment]
> https://www.arugaz.my.id/api
> `yang mau request bisa langsung chat aja 👍 gratis`

kok notfound bang

**Comment by Urbaee** [comment]
Udah ngga deh perasaan

Pada tanggal Jum, 8 Jan 2021 10.45 AM, Juwendi S <notifications@github.com>
menulis:

**Comment by Urbaee** [comment]
> > https://www.arugaz.my.id/api
> > `yang mau request bisa langsung chat aja 👍 gratis`
> 
> kok notfound bang

https://api.arugaz.my.id/

**Comment by MSI0072** [comment]
> > > https://www.arugaz.my.id/api
> > > `yang mau request bisa langsung chat aja 👍 gratis`
> > 
> > 
> > kok notfound bang
> 
> https://api.arugaz.my.id/

Thanks bang, bisa req api nulis?

**Comment by hardiantojek93** [comment]
Cara masukin foto truss di jadiin link truss di lanjutkan ke rest api kek case missing gitu tapi ngmbl dri quoted m

**Comment by Urbaee** [comment]
> Cara masukin foto truss di jadiin link truss di lanjutkan ke rest api kek case missing gitu tapi ngmbl dri quoted m

keknya gini deh

```if (isMedia && isImage || isQuotedImage) {
                                await aruga.reply(from, mess.wait, id)
                                const encryptMedia = isQuotedImage ? quotedMsg : message
                                const mediaData = await decryptMedia(encryptMedia, uaOverride)
                                const linkImg = await uploadImages(mediaData, `${sender.id}_img`)```

**Comment by hardiantojek93** [comment]
Owh gitu thanks kak

**Comment by QUERY-GANI** [comment]
> pake web ini aja : https://www.arugaz.my.id/api

![image](https://user-images.githubusercontent.com/73988956/106988252-e425a500-67a1-11eb-9a17-c34440aeed87.png)

not found ngab :v

**Comment by Urbaeexyz** [comment]
> > pake web ini aja : https://www.arugaz.my.id/api
> 
> ![image](https://user-images.githubusercontent.com/73988956/106988252-e425a500-67a1-11eb-9a17-c34440aeed87.png)
> 
> not found ngab :v

api.arugaz.my.id/api
