### ISSUE TITLE
yang ada rest api play yotube bagi dong hehe

### ISSUE THREAD

**Issue by MSI0072** [ArugaZ/whatsapp-bot#256]

**Comment by KillovSky** [comment]
Lihatlah bot yang saya buat, ada API fungsional untuk youtube dan banyak fitur yang tidak dapat saya tempatkan di sini berdasarkan ukurannya.
https://github.com/KillovSky/iris

**Comment by JustPandaEver** [comment]
http://128.199.72.121/ytsc.php?key=PandaEver&title=

**Comment by JustPandaEver** [comment]
Untuk search

**Comment by JustPandaEver** [comment]
http://128.199.72.121/ytmp4.php?key=PandaEver&url=

**Comment by JustPandaEver** [comment]
http://128.199.72.121/ytmp3.php?key=PandaEver&url=

**Comment by JustPandaEver** [comment]
sama2

**Comment by ArugaZ** [comment]
https://kocakz.herokuapp.com/api
