### ISSUE TITLE
DEBRIEF // QUESTION & ANSWER 💕

### ISSUE THREAD

**Issue by ArugaZ** [ArugaZ/whatsapp-bot#26]
Silahkan yang ingin bertanya, kalau ada yang tau bantu jawabin yaaa.. hhee

**Comment by mioscape** [comment]
Asiap

**Comment by idkmew** [comment]
Bang mau nanya, knp ya saya make Botnya untuk beberapa menit sih bisa, trus setelah 20 menit atau lebih, Botnya cmn ngeRead ajh, tapi di cmdny tulisanny EXEC , tapi ga muncul hasilny

**Comment by ArugaZ** [comment]
> Bang mau nanya, knp ya saya make Botnya untuk beberapa menit sih bisa, trus setelah 20 menit atau lebih, Botnya cmn ngeRead ajh, tapi di cmdny tulisanny EXEC , tapi ga muncul hasilny

entah, pending mungkin.. kl saya run nya dikasih cron job 15menit biar run ulang

**Comment by Chizuru-San** [comment]
gan no wa nya berapa ? biar enak komunikasinya, mau bahas tentang bot ini gan :)

**Comment by idkmew** [comment]
Mas gimana cron jobny? btw thanks banged saya udah nunggu untuk fitur simsiminya :') gasabar pengen nyoba

**Comment by iksanriyanto** [comment]
Mantaab lah dah ada simi..sukses terus mas aruga😍😍😍

**Comment by ArugaZ** [comment]
> gan no wa nya berapa ? biar enak komunikasinya, mau bahas tentang bot ini gan :)

ig aja gan, wa saya kena blockir whatsapp wkwk

**Comment by ArugaZ** [comment]
> Mas gimana cron jobny? btw thanks banged saya udah nunggu untuk fitur simsiminya :') gasabar pengen nyoba

nanti deh sy buatkan tutornya

**Comment by ArugaZ** [comment]
> Mantaab lah dah ada simi..sukses terus mas aruga😍😍😍

iya makasih, bantu share yoo 👍
