### ISSUE TITLE
error on  npm install gify-cli -g

### ISSUE THREAD

**Issue by Flashminat0** [arugaz/whatsapp-bot#263]
![image](https://user-images.githubusercontent.com/64888128/104120818-bf374100-535f-11eb-8be2-0f391ada294b.png)

**Comment by JustPandaEver** [comment]
sudo su dulu biar akses root enak installnya

**Comment by JustPandaEver** [comment]
itu akses nte masih blom akses root

**Comment by Urbaee** [comment]
> ![image](https://user-images.githubusercontent.com/64888128/104120818-bf374100-535f-11eb-8be2-0f391ada294b.png)
> 
> 

Buat gif kah?
