### ISSUE TITLE
ERROR !!

### ISSUE THREAD

**Issue by SayangkuCantik** [arugaz/whatsapp-bot#281]
> whatsapp-bot@2.1.0 start C:\Users\ASUS\Downloads\whatsapp-bot-master-02
> node index.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '@open-wa/wa-automate'
Require stack:
- C:\Users\ASUS\Downloads\whatsapp-bot-master-02\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\ASUS\Downloads\whatsapp-bot-master-02\index.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\ASUS\\Downloads\\whatsapp-bot-master-02\\index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot@2.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-bot@2.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUS\AppData\Roaming\npm-cache\_logs\2021-01-16T13_50_34_240Z-debug.log

C:\Users\ASUS\Downloads\whatsapp-bot-master-02>node index.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '@open-wa/wa-automate'
Require stack:
- C:\Users\ASUS\Downloads\whatsapp-bot-master-02\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\ASUS\Downloads\whatsapp-bot-master-02\index.js:1:28)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\Users\\ASUS\\Downloads\\whatsapp-bot-master-02\\index.js'←[39m ]
}

C:\Users\ASUS\Downloads\whatsapp-bot-master-02>npm install

> sharp@0.27.0 install C:\Users\ASUS\Downloads\whatsapp-bot-master-02\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-win32-x64.tar.br
ERR! sharp write EPROTO 1364:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
ERR! sharp
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies

C:\Users\ASUS\Downloads\whatsapp-bot-master-02\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: tunneling socket could not be established, statusCode=503
gyp ERR! stack     at ClientRequest.onConnect (C:\Program Files\nodejs\node_modules\npm\node_modules\tunnel-agent\index.js:166:19)
gyp ERR! stack     at Object.onceWrapper (events.js:422:26)
gyp ERR! stack     at ClientRequest.emit (events.js:315:20)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:547:11)
gyp ERR! stack     at Socket.emit (events.js:315:20)
gyp ERR! stack     at addChunk (internal/streams/readable.js:309:12)
gyp ERR! stack     at readableAddChunk (internal/streams/readable.js:284:9)
gyp ERR! stack     at Socket.Readable.push (internal/streams/readable.js:223:10)
gyp ERR! stack     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ASUS\Downloads\whatsapp-bot-master-02\node_modules\sharp
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.27.0 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.27.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUS\AppData\Roaming\npm-cache\_logs\2021-01-16T13_52_54_507Z-debug.log

**Comment by SayangkuCantik** [comment]
Ini error gara2 apa ya gan?? saya pakai Windows 10.

**Comment by QUERY-GANI** [comment]
kasian terkacang :v
