### ISSUE TITLE
ERROR FITUR : IG, YT, PUISI, MOTIVASI

### ISSUE THREAD

**Issue by SayangkuCantik** [arugaz/whatsapp-bot#287]
![error-ig](https://user-images.githubusercontent.com/77530540/105349320-95e9a100-5bfa-11eb-8a40-f47712b1b86b.PNG)
![error-puisi](https://user-images.githubusercontent.com/77530540/105349329-984bfb00-5bfa-11eb-9549-892e5ead59a9.PNG)

_Ini karena apa ya gan? mohon bantuannya._

**Comment by ArugaZ** [comment]
heroku habis dynos nya

**Comment by dxxoo** [comment]
Ganti Rest Apinya ke https://arugaz.my.id/api

**Comment by dxxoo** [comment]
Ganti Rest Apinya ke https://arugaz.my.id/api
