### ISSUE TITLE
Attention

### ISSUE THREAD

**Issue by arugaz** [arugaz/whatsapp-bot#296]
sepertinya banyak yang error ya?
oke deh nt saya aktif untuk update repos ini lagi.. mksh :>

**Comment by Urbaee** [comment]
> sepertinya banyak yang error ya?
> oke deh nt saya aktif untuk update repos ini lagi.. mksh :>

wihh thanks bang wkwk

**Comment by brogalan-blora** [comment]
Di tunggu bang

**Comment by ArugaZ** [comment]
Sipp bntr ane lg buat tutor bikin rest api

**Comment by Urbaee** [comment]
> Sipp bntr ane lg buat tutor bikin rest api

wanjirrrrr, yg gua tunggu" akhirnya dibuat tutor

thanks bang
