### ISSUE TITLE
REQUEST DISINI ! >///<

### ISSUE THREAD

**Issue by shinz404** [ArugaZ/whatsapp-bot#3]
Tambah yt,ig downloaderny gan :)

**Comment by ArugaZ** [comment]
> Tambah yt,ig downloaderny gan :)

iyaa lagi coba ngescrape, kl pake api rest harus pake api-key xixixi, syg duit mh

**Comment by ArugaZ** [comment]
> Tambah yt,ig downloaderny gan :)

sipp ane tampung

**Comment by shinz404** [comment]
Di tunggu gan :v

**Comment by agusydk3** [comment]
Tambahin Cek Resi Bang

**Comment by ArugaZ** [comment]
> Tambahin Cek Resi Bang

udah ada yaa

**Comment by ArugaZ** [comment]
> Di tunggu gan :v

ada nih bre, cuma harus install ffmpeg

**Comment by riintan** [comment]
request fitur screenshot dekstop dengan kapasitas memori bang

**Comment by ArugaZ** [comment]
> request fitur screenshot dekstop dengan kapasitas memori bang

oke nanti ane update fitur link nekopoi dlu

**Comment by riintan** [comment]
> > request fitur screenshot dekstop dengan kapasitas memori bang
> 
> oke nanti ane update fitur link nekopoi dlu

gak kerasa start abang naik cepet hahaha

**Comment by huudxx** [comment]
Bro, Request Informasi Covid-19. Makasih 🙏🏻

**Comment by ArugaZ** [comment]
> > > request fitur screenshot dekstop dengan kapasitas memori bang
> > 
> > 
> > oke nanti ane update fitur link nekopoi dlu
> 
> gak kerasa start abang naik cepet hahaha

iya nih, bantuin share yaa

**Comment by ArugaZ** [comment]
> Bro, Request Informasi Covid-19. Makasih 🙏🏻

kalau covid yang dari lokasi sdh ada, nt saya tambahkan yang info untuk negara

**Comment by shansekai** [comment]
Req fitur kalkulator bang

**Comment by shinz404** [comment]
Downloaderny gan

**Comment by ArugaZ** [comment]
> Downloaderny gan

nt sore saya update ig, ytmp4 ,ytmp3

**Comment by ArugaZ** [comment]
> Req fitur kalkulator bang

maunya sih bikin foto to text, jadi orang foto soal math nya.. botnya akan kirim jawaban

**Comment by shinz404** [comment]
> > Downloaderny gan
> 
> nt sore saya update ig, ytmp4 ,ytmp3

Udah gan ?

**Comment by ArugaZ** [comment]
> > > Downloaderny gan
> > 
> > 
> > nt sore saya update ig, ytmp4 ,ytmp3
> 
> Udah gan ?

udhh sori baru update sekarang wkwk

**Comment by shinz404** [comment]
> > > > Downloaderny gan
> > > 
> > > 
> > > nt sore saya update ig, ytmp4 ,ytmp3
> > 
> > 
> > Udah gan ?
> 
> udhh sori baru update sekarang wkwk

Terimakasih gan >///<

**Comment by mioscape** [comment]
NHentai Webview/Downloader hehe

**Comment by andra12lol** [comment]
> NHentai Webview/Downloader hehe

goblok haha

**Comment by ArugaZ** [comment]
> NHentai Webview/Downloader hehe

okeiii syapp

**Comment by ArugaZ** [comment]
> Req fitur kalkulator bang

ini mau callculator yg ky gmn??

**Comment by shansekai** [comment]
> > Req fitur kalkulator bang
> 
> ini mau callculator yg ky gmn??

Yang contohnya gini:

#kalkulator 5 * 5

**Comment by shinz404** [comment]
Baru kali ini nemu admin bot yang baik >//<

**Comment by ArugaZ** [comment]
> > > Req fitur kalkulator bang
> > 
> > 
> > ini mau callculator yg ky gmn??
> 
> Yang contohnya gini:
> 
> #kalkulator 5 * 5

okeeee

**Comment by riintan2** [comment]
bang tambahin fitur !limit soalnya sering bug klo gada batas  tks :)

**Comment by ArugaZ** [comment]
> bang tambahin fitur !limit soalnya sering bug klo gada batas tks :)

ini project hanya sample, kalian bisa variasiin sendiri
kl mau pakai limit catat aja datanya ke dalam json

**Comment by riintan2** [comment]
7 start lagi  :v

**Comment by ArugaZ** [comment]
> 7 start lagi :v

nah iya ntr 50 star ane share pornhub sm simi-simi

**Comment by riintan2** [comment]
Bang
Di setting apison itukan ada "apiNoBg": "API-KEY",
Nah yang misal saya dpt keynya = abcd
Itu yg diubah "API-abcd" Kek gini bang? Maaf newbie :D

**Comment by ArugaZ** [comment]
> Bang
> Di setting apison itukan ada "apiNoBg": "API-KEY",
> Nah yang misal saya dpt keynya = abcd
> Itu yg diubah "API-abcd" Kek gini bang? Maaf newbie :D

bukan, diubahnya dari "API-KEY" jadi => "abcd"

**Comment by DMart23** [comment]
![Screenshot_20201106-034833](https://user-images.githubusercontent.com/73910013/98294716-ff3a1a80-1fe2-11eb-8da1-576cef4a24ea.png)
Solusinya dong bang, selalu stak disini.. Maaf newbie

**Comment by ArugaZ** [comment]
> ![Screenshot_20201106-034833](https://user-images.githubusercontent.com/73910013/98294716-ff3a1a80-1fe2-11eb-8da1-576cef4a24ea.png)
> Solusinya dong bang, selalu stak disini.. Maaf newbie

https://github.com/lovell/sharp/issues/1627#issuecomment-477109851 baca disini gan

**Comment by muhammadzakizn07** [comment]
nambahin fitur mute botnya digrup, kadang member pakai buat spam-_

**Comment by ImZayy** [comment]
Dah 50 ngab

**Comment by Aryasatya12** [comment]
Dh 53 star gan 
Ditunggu update fitur simsimi, pornhub nya :v wkwk

**Comment by bagusdwip** [comment]
Fiture limit+mute dong :) kebanyakan spam suka ga resp

**Comment by idkmew** [comment]
btw ko fitur meme nya gabisa ya bang

**Comment by rwahyudii** [comment]
ditunggu  fitur simsimi nya bg xixixi

**Comment by mioscape** [comment]
> nambahin fitur mute botnya digrup, kadang member pakai buat spam-_

Kan ada fiture banned, banned aja langsung yang nge-spam bot nya

**Comment by ArugaZ** [comment]
istirahat dlu gan ane :D

**Comment by arh-space** [comment]
Please Fitur !limit tambahin :(

**Comment by dedekganteng** [comment]
tambahin fitur:
#kurs 1 usd-idr btc-idr dll

**Comment by SayangkuCantik** [comment]
**REQUEST HIDETAG GAN !!**
