### ISSUE TITLE
kgk ada err tapi kgk return respon cuy

### ISSUE THREAD

**Issue by QUERY-GANI** [ArugaZ/whatsapp-bot#306]
terminal : 

![image](https://user-images.githubusercontent.com/73988956/106989129-01f40980-67a4-11eb-9c85-bc06724c6bb2.png)

di wanya :

![image](https://user-images.githubusercontent.com/73988956/106989154-133d1600-67a4-11eb-873c-8a435bebc810.png)

**Comment by Urbaeexyz** [comment]
> terminal :
> 
> ![image](https://user-images.githubusercontent.com/73988956/106989129-01f40980-67a4-11eb-9c85-bc06724c6bb2.png)
> 
> di wanya :
> 
> ![image](https://user-images.githubusercontent.com/73988956/106989154-133d1600-67a4-11eb-873c-8a435bebc810.png)

```npm i --save @open-wa/wa-automate@3.2.2```

**Comment by Urbaeexyz** [comment]
gua juga problem disitu
mesti downgrade open wa nya dlu baru kerespon
