### ISSUE TITLE
Error, Stuck

### ISSUE THREAD

**Issue by dzakijo1** [arugaz/whatsapp-bot#311]
![image](https://user-images.githubusercontent.com/47619660/109297289-5a2ea080-7864-11eb-8a37-5c1e5acfb6b6.png)

log stuck disitu bang, udah kirim perintah tetep aja gtu

**Comment by Aalcantaraxxx** [comment]
Doesn´t Work for me. I dont know why, someone can help me?
![image](https://user-images.githubusercontent.com/77713872/109319151-2a57ac80-7814-11eb-9553-0b1f656c33e5.png)

**Comment by MulqiGaming64** [comment]
Sama stuck

**Comment by Rmdhn-20** [comment]
> ![image](https://user-images.githubusercontent.com/47619660/109297289-5a2ea080-7864-11eb-8a37-5c1e5acfb6b6.png)
> 
> log stuck disitu bang, udah kirim perintah tetep aja gtu

![Screenshot (2)](https://user-images.githubusercontent.com/76412415/109574179-11a40b00-7b22-11eb-81b2-dab7641c7a98.png)


nih sekedar info aja, sama gue juga ga respon botnya wkwk
