### ISSUE TITLE
Error bang!!

### ISSUE THREAD

**Issue by Rmdhn-20** [arugaz/whatsapp-bot#312]
![Screenshot (3)](https://user-images.githubusercontent.com/76412415/109736364-c60f6100-7bf6-11eb-8a52-b5415db15b26.png)

Karna kaga ada respon akhirnya di downgrade open-wa nya, eh malah gini:)

help dong!!

**Comment by Aalcantaraxxx** [comment]
I HAVE THE SAME PROBLEM SINCE 1 WEEK OR 2 WEEKS

HELP US PLEASEEE! 
I NEED MAKE STICKERS AND USE THE BOT

**Comment by Rmdhn-20** [comment]
> I HAVE THE SAME PROBLEM SINCE 1 WEEK OR 2 WEEKS
> 
> HELP US PLEASEEE!
> I NEED MAKE STICKERS AND USE THE BOT

try using another script first, bro. maybe because there is an error from the author

**Comment by Aalcantaraxxx** [comment]
How can i do this?
u use another script? Work for u?

**Comment by Rmdhn-20** [comment]
ya, saya mencoba skrip lain dan itu bekerja. coba saja kamu gunakan skrip milik Urbaeexyz

**Comment by Aalcantaraxxx** [comment]
can you help me add the script please? 
my email is aalcantara_27@mail.com

**Comment by Urbaeexyz** [comment]
> ![Screenshot (3)](https://user-images.githubusercontent.com/76412415/109736364-c60f6100-7bf6-11eb-8a52-b5415db15b26.png)
> 
> Karna kaga ada respon akhirnya di downgrade open-wa nya, eh malah gini:)
> 
> help dong!!

https://github.com/Urbaeexyz/wa-bot

**Comment by Aalcantaraxxx** [comment]
I try your repo and doesnt work 
look its freeze
![image](https://user-images.githubusercontent.com/77713872/110377422-ffdad000-8019-11eb-9466-8c691975bacf.png)

**Comment by Urbaeexyz** [comment]
> I try your repo and doesnt work
> look its freeze
> ![image](https://user-images.githubusercontent.com/77713872/110377422-ffdad000-8019-11eb-9466-8c691975bacf.png)

https://github.com/Urbaeexyz/wa-bot

**Comment by Aalcantaraxxx** [comment]
Doesn´t work.
When I write "menu" nothing happens

**Comment by Urbaeexyz** [comment]
> Doesn´t work.
> When I write "menu" nothing happens

Use prefix lol
!menu or /menu

**Comment by Aalcantaraxxx** [comment]
Noup, ill try this and nothing
The bot is on but don´t respond the "!menu" or something like that, help me :(

**Comment by Urbaeexyz** [comment]
try this repo
https://github.com/Urbaeexyz/wa-bot

Pada tanggal Rab, 10 Mar 2021 07.03, Aalcantaraxxx <notifications@github.com>
menulis:

**Comment by Aalcantaraxxx** [comment]
Okay Wait me 2 mins, thx bro

**Comment by Aalcantaraxxx** [comment]
Hi bro finally work
I try on Visual Studio and works perfect (i think) 
But i wanna try in repl.it, but doesnt work.
![image](https://user-images.githubusercontent.com/77713872/110566172-3e08ea00-8115-11eb-8041-51eb5ca40dcf.png)

**Comment by Aalcantaraxxx** [comment]
> Hi bro finally work
> I try on Visual Studio and works perfect (i think)
> But i wanna try in repl.it, but doesnt work.
> ![image](https://user-images.githubusercontent.com/77713872/110566172-3e08ea00-8115-11eb-8041-51eb5ca40dcf.png)

What can i do for works on "repl.it"?????

**Comment by Urbaeexyz** [comment]
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
> sudo apt install ./google-chrome-stable_current_amd64.deb


Pada tanggal Rab, 10 Mar 2021 09.25, Aalcantaraxxx <notifications@github.com>
menulis:

**Comment by Urbaeexyz** [comment]
> > Hi bro finally work
> > I try on Visual Studio and works perfect (i think)
> > But i wanna try in repl.it, but doesnt work.
> > ![image](https://user-images.githubusercontent.com/77713872/110566172-3e08ea00-8115-11eb-8041-51eb5ca40dcf.png)
> 
> What can i do for works on "repl.it"?????
>
 
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

Thenn

sudo apt install ./google-chrome-stable_current_amd64.deb

**Comment by Urbaeexyz** [comment]
> > Hi bro finally work
> > I try on Visual Studio and works perfect (i think)
> > But i wanna try in repl.it, but doesnt work.
> > ![image](https://user-images.githubusercontent.com/77713872/110566172-3e08ea00-8115-11eb-8041-51eb5ca40dcf.png)
> 
> What can i do for works on "repl.it"?????
> 

Is it work?

**Comment by Urbaeexyz** [comment]
> Hi bro, i went out  my house sorry.
> Where i put thi "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"?
> I already download this, and now? in what folder i need put in?
> Maybe i´ll reply you in a 6 or 7 hours because in my country its too late

Open your bot folder
And do this

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

And then

sudo apt install ./google-chrome-stable_current_amd64.deb

**Comment by Urbaeexyz** [comment]
> The command "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" Works
> But **"sudo apt install ./google-chrome-stable_current_amd64.deb** NO
> ![image](https://user-images.githubusercontent.com/77713872/110634945-2e6abf00-8170-11eb-9809-2b37edb2d65f.png)

remove sudo
apt install

**Comment by Aalcantaraxxx** [comment]
no bro, look
![image](https://user-images.githubusercontent.com/77713872/110686458-13ff0880-81a5-11eb-850d-9a7ef3af2c60.png)
When i run the bot this happen :((
![image](https://user-images.githubusercontent.com/77713872/110687999-be2b6000-81a6-11eb-8940-89c37af7bba0.png)
![image](https://user-images.githubusercontent.com/77713872/110689526-655cc700-81a8-11eb-93bb-f1363aad5b2e.png)

**Comment by Aalcantaraxxx** [comment]
I try with a new folder and when i run(npm start) its frezze for a few seconds and this happen
![image](https://user-images.githubusercontent.com/77713872/110689984-fcc21a00-81a8-11eb-8174-a602d4ea2433.png)
![image](https://user-images.githubusercontent.com/77713872/110690148-33983000-81a9-11eb-845f-99ab5ade0d88.png)

**Comment by Aalcantaraxxx** [comment]
I create a new folder, this is the link if you want to join for help me
https://repl.it/join/iqyihfap-aalcantaraxx

**Comment by Urbaeexyz** [comment]
> I create a new folder, this is the link if you want to join for help me
> https://repl.it/join/iqyihfap-aalcantaraxx

![image](https://user-images.githubusercontent.com/75126993/110701282-90383100-8223-11eb-84c5-ced0274768c4.png)


i didn't get something wrong

**Comment by Aalcantaraxxx** [comment]
hmm
Can u tell me what i need to do step for step?
Im online right now if U are free we can do right now
https://repl.it/join/iqyihfap-aalcantaraxx

**Comment by Urbaeexyz** [comment]
> hmm
> Can u tell me what i need to do step for step?
> Im online right now if U are free we can do right now
> https://repl.it/join/iqyihfap-aalcantaraxx

wait

**Comment by Aalcantaraxxx** [comment]
okay

**Comment by Urbaeexyz** [comment]
![image](https://user-images.githubusercontent.com/75126993/110702737-7ef02400-8225-11eb-900f-e09f999d5bd3.png)

**Comment by Aalcantaraxxx** [comment]
![image](https://user-images.githubusercontent.com/77713872/110703256-26833d00-81b9-11eb-95dc-8b15236da12d.png)

**Comment by Urbaeexyz** [comment]
![image](https://user-images.githubusercontent.com/75126993/110703282-2705ed00-8226-11eb-8efc-31fed4949b24.png)

**Comment by Aalcantaraxxx** [comment]
![image](https://user-images.githubusercontent.com/77713872/110703487-79f58b00-81b9-11eb-81f6-263a298c661f.png)

**Comment by Urbaeexyz** [comment]
create a new one and run like usual

if there is still error
i will reply till i wake up again

**Comment by Aalcantaraxxx** [comment]
![image](https://user-images.githubusercontent.com/77713872/110703700-b5905500-81b9-11eb-840b-af6cc6941619.png)
Iam cloning your repo

**Comment by Aalcantaraxxx** [comment]
okay bro, rest
thx for the help
see u in a few hours

**Comment by Aalcantaraxxx** [comment]
I write "**npm install -g npm**
and this happen like u 
and next i write "**npm install** and are install all
![image](https://user-images.githubusercontent.com/77713872/110704281-5ed74b00-81ba-11eb-973d-2a9b9c1ba579.png)

**Comment by Aalcantaraxxx** [comment]
I will install this **wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb**
![image](https://user-images.githubusercontent.com/77713872/110704450-95ad6100-81ba-11eb-94aa-1cd08c91c750.png)

**Comment by Aalcantaraxxx** [comment]
I install chromium but doesnt work, i marked u
![image](https://user-images.githubusercontent.com/77713872/110704711-f89ef800-81ba-11eb-8992-ec38903b03d9.png)
Say the same and the command **"sudo apt install ./google-chrome-stable_current_amd64.deb** doesn´t wprk
![image](https://user-images.githubusercontent.com/77713872/110704765-0ce2f500-81bb-11eb-9814-ccc91997dda0.png)

I will try with **apt install ./google-chrome-stable_current_amd64.deb**
