### ISSUE TITLE
Bot gak respon

### ISSUE THREAD

**Issue by farrasrayhand** [arugaz/whatsapp-bot#316]
![image](https://user-images.githubusercontent.com/35839373/112464987-24b39f00-8d9f-11eb-8577-0af0eff5d991.png)
![image](https://user-images.githubusercontent.com/35839373/112465018-2da47080-8d9f-11eb-84da-5b8c0a2f39b8.png)

**Comment by Rmdhn-20** [comment]
pake punya Urbaexyz aja cuy

**Comment by farrasrayhand** [comment]
link?

**Comment by Urbaeexyz** [comment]
> link?

https://github.com/Urbaeexyz/wa-bot

**Comment by GuckTubeYT** [comment]
Itu lu pake nya dmn? Di group atau chat?

**Comment by Harsh-beep** [comment]
have same issue.. I guess solution is yet to be found......

**Comment by Rmdhn-20** [comment]
> have same issue.. I guess solution is yet to be found......

Coba pake repo ini
https://github.com/Urbaeexyz/wa-bot

**Comment by Urbaeexyz** [comment]
> have same issue.. I guess solution is yet to be found......

Yooo i think i knew you
Are you Harshu?
Did you know Game For peace?

**Comment by Harsh-beep** [comment]
> > have same issue.. I guess solution is yet to be found......
> 
> Coba pake repo ini
> https://github.com/Urbaeexyz/wa-bot

thankU. I saw the link above. I'm currenty using that.

**Comment by Harsh-beep** [comment]
> > have same issue.. I guess solution is yet to be found......
> 
> Yooo i think i knew you
> Are you Harshu?
> Did you know Game For peace?

Sorry I'm not..

**Comment by Harsh-beep** [comment]
> > have same issue.. I guess solution is yet to be found......
> 
> Yooo i think i knew you
> Are you Harshu?
> Did you know Game For peace?

Sorry I'm not..
I do know about Game for peace but I don't play it.
