### ISSUE TITLE
Error when starting bot

### ISSUE THREAD

**Issue by AdiiAndre** [ArugaZ/whatsapp-bot#318]
whatsapp-bot@2.1.0 start /data/data/com.termux/files/home/whatsapp-bot
> node index.js

internal/modules/cjs/loader.js:458
  throw e;
  ^

Error: Package exports for '/data/data/com.termux/files/home/whatsapp-bot/node_modules/uuid' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:455:13)
    at resolveExports (internal/modules/cjs/loader.js:388:16)
    at Function.Module._findPath (internal/modules/cjs/loader.js:487:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:782:27)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:52:16)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot@2.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-bot@2.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-03-29T21_52_57_367Z-debug.log

**Comment by Urbaeexyz** [comment]
https://github

> whatsapp-bot@2.1.0 start /data/data/com.termux/files/home/whatsapp-bot
> 
> > node index.js
> 
> internal/modules/cjs/loader.js:458
> throw e;
> ^
> 
> Error: Package exports for '/data/data/com.termux/files/home/whatsapp-bot/node_modules/uuid' do not define a valid '.' target
> at resolveExportsTarget (internal/modules/cjs/loader.js:455:13)
> at resolveExports (internal/modules/cjs/loader.js:388:16)
> at Function.Module._findPath (internal/modules/cjs/loader.js:487:20)
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:782:27)
> at Function.Module._load (internal/modules/cjs/loader.js:688:27)
> at Module.require (internal/modules/cjs/loader.js:850:19)
> at require (internal/modules/cjs/helpers.js:74:18)
> at Object. (/data/data/com.termux/files/home/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:52:16)
> at Module._compile (internal/modules/cjs/loader.js:958:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10) {
> code: 'MODULE_NOT_FOUND'
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! whatsapp-bot@2.1.0 start: `node index.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the whatsapp-bot@2.1.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /data/data/com.termux/files/home/.npm/_logs/2021-03-29T21_52_57_367Z-debug.log

https://github.com/Urbaeexyz/wa-bot

**Comment by GuckTubeYT** [comment]
Termux cant use whatsapp bot (maybe?)
