### ISSUE TITLE
bagi saya muncul ini paling daz kali saya mengetik perintah

### ISSUE THREAD

**Issue by strang445** [ArugaZ/whatsapp-bot#33]
![image](https://user-images.githubusercontent.com/69132413/99014733-0ce72700-2532-11eb-83ae-343038aecb29.png)

**Comment by strang445** [comment]
bisakah kamu memperbaikinya? Bot lain yang terlihat seperti ini juga mengalami masalah yang sama

**Comment by ArugaZ** [comment]
> bisakah kamu memperbaikinya? Bot lain yang terlihat seperti ini juga mengalami masalah yang sama

untuk tts, masukan bahasa yang support pada node-gtts
untuk nekopoi, sepertinya error
