### ISSUE TITLE
Terimakasih <3

### ISSUE THREAD

**Issue by zencats22** [ArugaZ/whatsapp-bot#38]
UwU ~,terimakasih ya sdh sharing ginian yg totally free.terus update ya 😁
⭐

**Comment by ArugaZ** [comment]
kami sebgai user gratisan  siap menunggu sc turun :v

**Comment by iksanriyanto** [comment]
@ArugaZ cara ganti apikey simi simi ya bgimana ya..ane kudet wkwk  udh coba ku cari msih bingung :v

**Comment by ArugaZ** [comment]
> @ArugaZ cara ganti apikey simi simi ya bgimana ya..ane kudet wkwk udh coba ku cari msih bingung :v

ubah di settings/api.json
untuk dapat apikey nya lihat di readme.md

**Comment by iksanriyanto** [comment]
> > @ArugaZ cara ganti apikey simi simi ya bgimana ya..ane kudet wkwk udh coba ku cari msih bingung :v
> 
> ubah di settings/api.json
> untuk dapat apikey nya lihat di readme.md

Sudah kuubah api simi nya di api.json tpi masih limit..jdi bingung aku tuch

**Comment by ArugaZ** [comment]
> > > @ArugaZ cara ganti apikey simi simi ya bgimana ya..ane kudet wkwk udh coba ku cari msih bingung :v
> > 
> > 
> > ubah di settings/api.json
> > untuk dapat apikey nya lihat di readme.md
> 
> Sudah kuubah api simi nya di api.json tpi masih limit..jdi bingung aku tuch

di dashboard simi-simi nya jgn lupa klik project-active biar nyala

**Comment by ArugaZ** [comment]
![Uploading 16052960404477777053665714664630.jpg…]()

**Comment by ArugaZ** [comment]
![Uploading Screenshot_2020-11-14-02-39-33-815_com.android.chrome.jpg…]()

**Comment by ArugaZ** [comment]
![Screenshot_2020-11-14-02-39-33-815_com android chrome](https://user-images.githubusercontent.com/53950128/99114193-02f12100-2623-11eb-809b-9b019490d8e7.jpg)

**Comment by riintan2** [comment]
gada yang unlimited bang :v

**Comment by ArugaZ** [comment]
> gada yang unlimited bang :v

gadalah wkk klo bayar mahal pula

**Comment by akujeleksad** [comment]
limit

**Comment by anggasd** [comment]
Bang play sama stikergif error' kah bang

**Comment by SyauqiR** [comment]
bang kalo pake !play kok eror yaa?

**Comment by partyboyz** [comment]
Bang ko aku stuck di banner aja ya ?? Apa yang slaah ya ?? Ada video instalasi di termux kah ??

**Comment by normanweid333** [comment]
kak untuk masalah banned nya itu gmna yaa ?
