### ISSUE TITLE
[HOWTO] Generate specific language

### ISSUE THREAD

**Issue by LSystemus-2** [arugaz/whatsapp-bot#393]
how to generate  nl dutch

i can't figure out

**Comment by arugaz** [comment]
you just need to remove the languages you don't want to use in [this file](https://github.com/arugaz/whatsapp-bot/blob/master/database/languages.json)

ex: if you just want to use dutch
```js
[{ "iso": "nl", "lang": "Dutch" }]
```

**Comment by arugaz** [comment]
@all-contributors please add @LSystemus-2  for bug
