### ISSUE TITLE
jangan lupa aktifkan ini saat ambil apikey simi-simi

### ISSUE THREAD

**Issue by ArugaZ** [ArugaZ/whatsapp-bot#41]
![Screenshot_2020-11-14-02-39-33-815_com android chrome](https://user-images.githubusercontent.com/53950128/99114193-02f12100-2623-11eb-809b-9b019490d8e7.jpg)

_Originally posted by @ArugaZ in https://github.com/ArugaZ/whatsapp-bot/issues/38#issuecomment-726995594_

**Comment by iksanriyanto** [comment]
> ![Screenshot_2020-11-14-02-39-33-815_com android chrome](https://user-images.githubusercontent.com/53950128/99114193-02f12100-2623-11eb-809b-9b019490d8e7.jpg)
> 
> _Originally posted by @ArugaZ in [#38 (comment)](https://github.com/ArugaZ/whatsapp-bot/issues/38#issuecomment-726995594)_

Asiap, tpi saya aneh bang.  Kok pdhal bikin baru dan masih fresh tpi end date nya tetep tanggal 14
Masih limit juga..apa gara gara udh expired ya api ku
