### ISSUE TITLE
${prefix} add - Pemborosan Command

### ISSUE THREAD

**Issue by mioscape** [ArugaZ/whatsapp-bot#45]
`.then(() => aruga.reply(from, 'Hai selamat datang', id))`
Delete code itu, soalnya kalo invite ke group bot nya jadi nge-trigger 2 commands, tadi kelupaan pas mau pull request
![image](https://user-images.githubusercontent.com/43681888/99141687-6b222000-2680-11eb-992f-cf5bdc532f35.png)

**Comment by bagusdwip** [comment]
> `.then(() => aruga.reply(from, 'Hai selamat datang', id))`
> Delete code itu, soalnya kalo invite ke group bot nya jadi nge-trigger 2 commands, tadi kelupaan pas mau pull request
> ![image](https://user-images.githubusercontent.com/43681888/99141687-6b222000-2680-11eb-992f-cf5bdc532f35.png)

Welcome grub masih bug ga gan ?

**Comment by mioscape** [comment]
> > `.then(() => aruga.reply(from, 'Hai selamat datang', id))`
> > Delete code itu, soalnya kalo invite ke group bot nya jadi nge-trigger 2 commands, tadi kelupaan pas mau pull request
> > ![image](https://user-images.githubusercontent.com/43681888/99141687-6b222000-2680-11eb-992f-cf5bdc532f35.png)
> 
> Welcome grub masih bug ga gan ?

Ndak tau saya, soalnya ga pernah ngalamin. Tunggu yang punya repo dateng coba

**Comment by agusydk3** [comment]
![Screenshot_2020-11-14-16-54-32-689_com whatsapp](https://user-images.githubusercontent.com/57493908/99144669-3c18a800-269a-11eb-8f2b-8c46254e3630.jpg)

Gini atasin nya gimana ya

**Comment by ArugaZ** [comment]
> ![Screenshot_2020-11-14-16-54-32-689_com whatsapp](https://user-images.githubusercontent.com/57493908/99144669-3c18a800-269a-11eb-8f2b-8c46254e3630.jpg)
> 
> Gini atasin nya gimana ya

block aja gan yg aruga.onGlobalParticipants

**Comment by agusydk3** [comment]
> > ![Screenshot_2020-11-14-16-54-32-689_com whatsapp](https://user-images.githubusercontent.com/57493908/99144669-3c18a800-269a-11eb-8f2b-8c46254e3630.jpg)
> > Gini atasin nya gimana ya
> 
> block aja gan yg aruga.onGlobalParticipants

block nya kek mana sob ?

**Comment by ferlitopym** [comment]
> block nya kek mana sob ?

kasih tanda //
@agusydk3

**Comment by mioscape** [comment]
> > > ![Screenshot_2020-11-14-16-54-32-689_com whatsapp](https://user-images.githubusercontent.com/57493908/99144669-3c18a800-269a-11eb-8f2b-8c46254e3630.jpg)
> > > Gini atasin nya gimana ya
> > 
> > 
> > block aja gan yg aruga.onGlobalParticipants
> 
> block nya kek mana sob ?

`/* */` di antara kode nya

**Comment by ArugaZ** [comment]
> `.then(() => aruga.reply(from, 'Hai selamat datang', id))`
> Delete code itu, soalnya kalo invite ke group bot nya jadi nge-trigger 2 commands, tadi kelupaan pas mau pull request
> ![image](https://user-images.githubusercontent.com/43681888/99141687-6b222000-2680-11eb-992f-cf5bdc532f35.png)

buat sementara aruga.onGlobalParicipantsChanged nonaktifkan dlu, karena ada problem dari sananya

**Comment by NaldoMota1** [comment]
![bot erro](https://user-images.githubusercontent.com/71650872/99161184-40f74f00-26ce-11eb-9890-299525d4e51d.PNG)

what error is this?

**Comment by ArugaZ** [comment]
> ![Screenshot_2020-11-14-16-54-32-689_com whatsapp](https://user-images.githubusercontent.com/57493908/99144669-3c18a800-269a-11eb-8f2b-8c46254e3630.jpg)
> 
> Gini atasin nya gimana ya

silahkan update modules

**Comment by ArugaZ** [comment]
> ![bot erro](https://user-images.githubusercontent.com/71650872/99161184-40f74f00-26ce-11eb-9890-299525d4e51d.PNG)
> 
> what error is this?
nothin
