### ISSUE TITLE
[BUG] Error "node_modules/fastify/types/route.d.ts"

### ISSUE THREAD

**Issue by rivai45** [arugaz/whatsapp-bot#492]
### Description

```bash
'Found 280 errors' habis 'npm run build'.
Semuanya berawalan 'node_modules/fastify/types/instance.d.ts'
*cek gambar

Kalau langsung ketik 'npm start' munculnya 

node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module 'D:\Github\whatsapp-bot\dist\main.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.9.0
```

### Reproduction steps

```bash
1. 'npx run build'
2. Found 280 errors
3. 'npm start'
4. Error module
```

### Screenshots

![image](https://github.com/arugaz/whatsapp-bot/assets/110272391/1ac30348-140c-46a0-8587-bea4839cdb31)

### Whatsapp Version

whatsapp-bot@3.0.0 build

### OS

Windows

**Comment by ilterugur** [comment]
@rivai45 Looks like the latest version of fastify package is using typescript version ^5.2.2 and this project is using ^4.9.4 so the problem is related to this reason. Update typescript version of this project on package.json to "^5.2.2" and it should work fine.

**Comment by rivai45** [comment]
@ilterugur it stil same.. Nothing changed.. Still appear 280 error with same error code too..

**Comment by rivai45** [comment]
@ilterugur wwhoaa.. thanks.. Yesterday I tried updating TypeScript directly, not from package.json
