### ISSUE TITLE
[REQ] Anti view once for direct message

### ISSUE THREAD

**Issue by rivai45** [arugaz/whatsapp-bot#494]
### Just describe the feature

Can you add anti view once for private message? This feature can only be used by the number owner.
Command for example .vv

**Comment by arugaz** [comment]
You can create on dir owner with the command object, here the example how to resend

https://github.com/arugaz/whatsapp-bot/blob/3a9785eb3984b14debe8cff670b8e126e299a327/src/commands/group/antiviewonce_.ts#L3-L9

**Comment by rivai45** [comment]
I dont know how to code, but I've try it, and the command not respond lol

`"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    category: "owner",
    ownerOnly: true,
    example: `
  @PREFIX@CMD
  `.trimEnd(),
    execute: async ({ aruga, message }) => {
        if (message.viewOnce) {
            return await aruga.resendMessage(message.from, message, { ephemeralExpiration: message.expiration });
        }
    }
};
`

**Comment by rivai45** [comment]
@arugaz bang, selalu muncul "Perintah penggunaannya salah", ini salah dimana nya ya?

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    category: "owner",
    aliases: ["vv", "viewo"],
    cd: 3,
    desc: "Anti view once",
    ownerOnly: true,
    example: `
@PREFIX@CMD
`.trimEnd(),
    execute: async ({ aruga, message }) => {
        if (message.viewOnce) {
            return aruga.sendMessage(message.from, message, {ephemeralExpiration: message.expiration });
            }
        throw "noCmd";
        }
    }
;

**Comment by rivai45** [comment]
Dah berhasil.. Tinggal otak atik dikit karna captionnya gk muncul wkwk..

[vv.txt](https://github.com/arugaz/whatsapp-bot/files/13447687/vv.txt)
