### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by shinz404** [ArugaZ/whatsapp-bot#51]
![Screenshot_2020-11-15-11-18-41-25](https://user-images.githubusercontent.com/72645468/99162806-7d5d9600-2734-11eb-9713-39202adf13dd.png)

Ko ytmp3 saya null.htm ya gan ?

**Comment by ArugaZ** [comment]
> ![Screenshot_2020-11-15-11-18-41-25](https://user-images.githubusercontent.com/72645468/99162806-7d5d9600-2734-11eb-9713-39202adf13dd.png)
> 
> Ko ytmp3 saya null.htm ya gan ?

dari rest apinya, nt coba sy cek

**Comment by ArugaZ** [comment]
coba url lain gan

**Comment by riintan2** [comment]
bang fitur playnya knp gak muncul ya audionya,kek terkirim tapi gagal bang

**Comment by shinz404** [comment]
> coba url lain gan

Masih null.htm gan

**Comment by shinz404** [comment]
> bang fitur playnya knp gak muncul ya audionya,kek terkirim tapi gagal bang

![IMG_20201115_133545](https://user-images.githubusercontent.com/72645468/99178623-b2bfaf00-2747-11eb-8d61-ff4821852b00.jpg)


Sama saya juga ga bisa di play :v

**Comment by nugraizy** [comment]
coba kalo yg play misal ada error atau apa, coba ganti class sendPtt jadi SendFileFromUrl. dicoba dlu moga bisa

**Comment by Aryasatya12** [comment]
> coba kalo yg play misal ada error atau apa, coba ganti class sendPtt jadi SendFileFromUrl. dicoba dlu moga bisa

Sama aja gan null.html hasilnya

**Comment by ArugaZ** [comment]
dari y2mate nya gan

**Comment by Rimuru9531** [comment]
> dari y2mate nya gan

Cara Perbaikinya gimana

**Comment by Rimuru9531** [comment]
https://api.vhtear.com/ 

:) 👍
