### ISSUE TITLE
Yang ngerti bantu yaa

### ISSUE THREAD

**Issue by iksanriyanto** [ArugaZ/whatsapp-bot#58]
rror: Cannot find module 'app-root-path'
equire stack:
 C:\Users\IAS\i\HandleMsg.js
 C:\Users\IAS\i\index.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:9
[90m    at Function.Module._load (internal/modules/cjs/loader.js:838:27)←[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1022:19)←[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
   at Object.<anonymous> (C:\Users\IAS\i\HandleMsg.js:9:17)
[90m    at Module._compile (internal/modules/cjs/loader.js:1118:30)←[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138
[90m    at Module.load (internal/modules/cjs/loader.js:982:32)←[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:875:14)←[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1022:19)←[39m {
 code: ←[32m'MODULE_NOT_FOUND'←[39m,
 requireStack: [ ←[32m'C:\\Users\\IAS\\i\\HandleMsg.js'←[39m, ←[32m'C:\\Users

pm ERR! code ELIFECYCLE
pm ERR! errno 1
pm ERR! whatsapp-bot@2.0.0 start: `node index.js`
pm ERR! Exit status 1
pm ERR!
pm ERR! Failed at the whatsapp-bot@2.0.0 start script.
pm ERR! This is probably not a problem with npm. There is likely additional l

pm ERR! A complete log of this run can be found in:
pm ERR!     C:\Users\IAS\AppData\Roaming\npm-cache\_logs\2020-11-16T05_40_54_

:\Users\IAS\i>

napa ini ya ngab

**Comment by mioscape** [comment]
Ini mau ngapain?

**Comment by bagusdwip** [comment]
> rror: Cannot find module 'app-root-path'
> equire stack:
> C:\Users\IAS\i\HandleMsg.js
> C:\Users\IAS\i\index.js
> [90m at Function.Module._resolveFilename (internal/modules/cjs/loader.js:9
> [90m at Function.Module._load (internal/modules/cjs/loader.js:838:27)←[39m
> [90m at Module.require (internal/modules/cjs/loader.js:1022:19)←[39m
> [90m at require (internal/modules/cjs/helpers.js:72:18)←[39m
> at Object. (C:\Users\IAS\i\HandleMsg.js:9:17)
> [90m at Module._compile (internal/modules/cjs/loader.js:1118:30)←[39m
> [90m at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138
> [90m at Module.load (internal/modules/cjs/loader.js:982:32)←[39m
> [90m at Function.Module._load (internal/modules/cjs/loader.js:875:14)←[39m
> [90m at Module.require (internal/modules/cjs/loader.js:1022:19)←[39m {
> code: ←[32m'MODULE_NOT_FOUND'←[39m,
> requireStack: [ ←[32m'C:\Users\IAS\i\HandleMsg.js'←[39m, ←[32m'C:\Users
> 
> pm ERR! code ELIFECYCLE
> pm ERR! errno 1
> pm ERR! whatsapp-bot@2.0.0 start: `node index.js`
> pm ERR! Exit status 1
> pm ERR!
> pm ERR! Failed at the whatsapp-bot@2.0.0 start script.
> pm ERR! This is probably not a problem with npm. There is likely additional l
> 
> pm ERR! A complete log of this run can be found in:
> pm ERR! C:\Users\IAS\AppData\Roaming\npm-cache_logs\2020-11-16T05_40_54_
> 
> :\Users\IAS\i>
> 
> napa ini ya ngab

Modulnya blom ada udh lu tambahin di package blom trus update

**Comment by iksanriyanto** [comment]
> Ini mau ngapain?

ane nge clone github yang tebaru.. pas di run gtu bang...

**Comment by iksanriyanto** [comment]
> app-root-path

ohiya ternyata module nya blm ku install ..thanks!
