### ISSUE TITLE
bot spam di grub

### ISSUE THREAD

**Issue by albertstyles312** [ArugaZ/whatsapp-bot#61]
![image](https://user-images.githubusercontent.com/72325255/99230810-59787e00-2822-11eb-9d85-cbe0fdce896d.png)

ini biar gak spam kek mana bang
Terimakasih

**Comment by idkmew** [comment]
> ![image](https://user-images.githubusercontent.com/72325255/99230810-59787e00-2822-11eb-9d85-cbe0fdce896d.png)
> 
> ini biar gak spam kek mana bang
> Terimakasih

Di Block ajh bro, atau engga dihapus ajh di bagian index.js trus cari yg ini : // ketika seseorang masuk/keluar dari group, klo mau sisain ajh yg bagan :  // kondisi ketika seseorang dikick/keluar dari group

**Comment by mioscape** [comment]
Budayakan membaca _Issue_ yang sudah ada. Dimohon untuk meng-close _Issue_ ini terimakasih.
