### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Rimuru9531** [ArugaZ/whatsapp-bot#62]
![bandicam 2020-11-17 09-50-58-510](https://user-images.githubusercontent.com/73052642/99340370-752f6300-28ba-11eb-8842-a5fcd1ec08fc.jpg)

Itu knp yah Yang Tau Tolong Plis

**Comment by Rimuru9531** [comment]
![Uploading WhatsApp Image 2020-11-17 at 09.43.11.jpeg…]()

**Comment by riintan2** [comment]
> ![bandicam 2020-11-17 09-50-58-510](https://user-images.githubusercontent.com/73052642/99340370-752f6300-28ba-11eb-8842-a5fcd1ec08fc.jpg)
> 
> Itu knp yah Yang Tau Tolong Plis

udh download nodejs nya?

**Comment by Rimuru9531** [comment]
> > ![bandicam 2020-11-17 09-50-58-510](https://user-images.githubusercontent.com/73052642/99340370-752f6300-28ba-11eb-8842-a5fcd1ec08fc.jpg)
> > Itu knp yah Yang Tau Tolong Plis
> 
> udh download nodejs nya?

udah

**Comment by iksanriyanto** [comment]
> > > ![bandicam 2020-11-17 09-50-58-510](https://user-images.githubusercontent.com/73052642/99340370-752f6300-28ba-11eb-8842-a5fcd1ec08fc.jpg)
> > > Itu knp yah Yang Tau Tolong Plis
> > 
> > 
> > udh download nodejs nya?
> 
> udah

node js nya versi brapa?

**Comment by Rimuru9531** [comment]
> > > > ![bandicam 2020-11-17 09-50-58-510](https://user-images.githubusercontent.com/73052642/99340370-752f6300-28ba-11eb-8842-a5fcd1ec08fc.jpg)
> > > > Itu knp yah Yang Tau Tolong Plis
> > > 
> > > 
> > > udh download nodejs nya?
> > 
> > 
> > udah
> 
> node js nya versi brapa?

versi 14.15.1 LS

**Comment by Rimuru9531** [comment]
> > > > > ![bandicam 2020-11-17 09-50-58-510](https://user-images.githubusercontent.com/73052642/99340370-752f6300-28ba-11eb-8842-a5fcd1ec08fc.jpg)
> > > > > Itu knp yah Yang Tau Tolong Plis
> > > > 
> > > > 
> > > > udh download nodejs nya?
> > > 
> > > 
> > > udah
> > 
> > 
> > node js nya versi brapa?
> 
> versi 14.15.1 LST

Kok bisa gitu yah Mohon yang tau Plis

**Comment by dedekganteng** [comment]
cek disini gan https://github.com/nodejs/help/issues/2874#issuecomment-663661148

**Comment by Rimuru9531** [comment]
C:\Users\ACER\whatsapp-bot>npm start

> whatsapp-bot@2.0.0 start C:\Users\ACER\whatsapp-bot
> node index.js

C:\Users\ACER\whatsapp-bot\lib\rugaApi.js:238
    })
     ^

SyntaxError: Unexpected token ')'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\ACER\whatsapp-bot\lib\index.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot@2.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-bot@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ACER\AppData\Roaming\npm-cache\_logs\2020-11-20T01_24_24_485Z-debug.log

Itu Knp Yah..
