### ISSUE TITLE
Tanya

### ISSUE THREAD

**Issue by man-x199** [ArugaZ/whatsapp-bot#65]
INI PAKE TERMUX KAH SC NYA???

**Comment by ArugaZ** [comment]
ndak ngab, blm dibuat versi termos

**Comment by man-x199** [comment]
Plis bkin bro gw dh donate.
Request itu aja kok tapi fiturnya jgn dkit2 juga buat termux nya.

Pada tanggal Sab, 21 Nov 2020 18.07, ArugaZ <notifications@github.com>
menulis:
