### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iksanriyanto** [ArugaZ/whatsapp-bot#66]
[EXEC] 18/11/20 17:00:17 nekopoi [0] from Muhammad Iksan 
(node:1420) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]:
The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at dispatchHttpRequest (C:\Users\IAS\i\node_modules\axios\lib\adapters\http.
js:66:22)
    at new Promise (<anonymous>)
    at httpAdapter (C:\Users\IAS\i\node_modules\axios\lib\adapters\http.js:21:10
)
    at dispatchRequest (C:\Users\IAS\i\node_modules\axios\lib\core\dispatchReque
st.js:52:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 3)
(node:1420) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by ArugaZ** [comment]
ini udh clone ulang ?

**Comment by iksanriyanto** [comment]
> ini udh clone ulang ?

Sudah saya clone ulang bang, tapi tetap

**Comment by ferlitopym** [comment]
> Sudah saya clone ulang bang, tapi tetap

botnya ga ngijinin buat lu berdosa kali bro @iksanriyanto

**Comment by iksanriyanto** [comment]
> > Sudah saya clone ulang bang, tapi tetap
> 
> botnya ga ngijinin buat lu berdosa kali bro @iksanriyanto 

Sa ae lu ahh

**Comment by andikidsss** [comment]
Tolong error gini baru belajar ngikutin step by step makasih

internal/modules/cjs/loader.js:883                  throw err;
  ^
                                                  Error: Cannot find module '@open-wa/wa-automate'
Require stack:
- /storage/emulated/0/Download/yul/wa/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/storage/emulated/0/Download/yul/wa/index.js:2:28)                           at Module._compile (internal/modules/cjs/loader.js:1063:30)                                         at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/storage/emulated/0/Download/yul/wa/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot@2.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-bot@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2020-11-21T20_42_54_191Z-debug.log

**Comment by andra12lol** [comment]
> Tolong error gini baru belajar ngikutin step by step makasih
> 
> internal/modules/cjs/loader.js:883 throw err;
> ^
> Error: Cannot find module '@open-wa/wa-automate'
> Require stack:
> 
> * /storage/emulated/0/Download/yul/wa/index.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>   at Module.require (internal/modules/cjs/loader.js:952:19)
>   at require (internal/modules/cjs/helpers.js:88:18)
>   at Object. (/storage/emulated/0/Download/yul/wa/index.js:2:28)                           at Module._compile (internal/modules/cjs/loader.js:1063:30)                                         at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>   at Module.load (internal/modules/cjs/loader.js:928:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/storage/emulated/0/Download/yul/wa/index.js' ]
>   }
>   npm ERR! code ELIFECYCLE
>   npm ERR! errno 1
>   npm ERR! whatsapp-bot@2.0.0 start: `node index.js`
>   npm ERR! Exit status 1
>   npm ERR!
>   npm ERR! Failed at the whatsapp-bot@2.0.0 start script.
>   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /data/data/com.termux/files/home/.npm/_logs/2020-11-21T20_42_54_191Z-debug.log

udh npm i?
