### ISSUE TITLE
error waktu start

### ISSUE THREAD

**Issue by egmu** [ArugaZ/whatsapp-bot#67]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot@2.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-bot@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LENOVO\AppData\Roaming\npm-cache\_logs\2020-11-18T14_09_26_609Z-debug.log

**Comment by mioscape** [comment]
`npm install` udah?

**Comment by egmu** [comment]
udah

**Comment by ArugaZ** [comment]
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! whatsapp-bot@2.0.0 start: `node index.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the whatsapp-bot@2.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\LENOVO\AppData\Roaming\npm-cache_logs\2020-11-18T14_09_26_609Z-debug.log

#62 baca dsni gan

**Comment by egmu** [comment]
udh bisa kemarin gan hehe
