### ISSUE TITLE
FIX ERROR SAAT START

### ISSUE THREAD

**Issue by ArugaZ** [ArugaZ/whatsapp-bot#68]
cek disini gan https://github.com/nodejs/help/issues/2874#issuecomment-663661148

_Originally posted by @dedekganteng in https://github.com/ArugaZ/whatsapp-bot/issues/62#issuecomment-729445630_

**Comment by riintan2** [comment]
bang ytmp3 nya dengan fitur playnya null.html

**Comment by ArugaZ** [comment]
> bang ytmp3 nya dengan fitur playnya null.html

iya lgi saya benerin

**Comment by Mrfky** [comment]
> > bang ytmp3 nya dengan fitur playnya null.html
> 
> iya lgi saya benerin

Bang cara make ini github ini gmana ya, maklum baru make termux

**Comment by xnbw** [comment]
Nah iya bang ini gmna cara install lewat termux?
