### ISSUE TITLE
REQ mute bot di GC

### ISSUE THREAD

**Issue by thoriqazzra** [ArugaZ/whatsapp-bot#70]
req ngab

**Comment by mioscape** [comment]
Ga bisa.

**Comment by mioscape** [comment]
Maksudnya gmn nih?

**Comment by thoriqazzra** [comment]
> Maksudnya gmn nih?

itu bang, botnya bisa di mute in di group chat, klo mau ngeban cape juga kalo mau ngetag semuanya
mau nanya juga ini updatenya gimana ya?

**Comment by mioscape** [comment]
> > Maksudnya gmn nih?
> 
> itu bang, botnya bisa di mute in di group chat, klo mau ngeban cape juga kalo mau ngetag semuanya
> mau nanya juga ini updatenya gimana ya?
> 

Oh ok, I'll figure it out

**Comment by ArugaZ** [comment]
oke nt saya usahakan, soalnya lg buat project leveling bot

**Comment by thoriqazzra** [comment]
> oke nt saya usahakan, soalnya lg buat project leveling bot

play yt udah fix bang?

**Comment by mioscape** [comment]
> > oke nt saya usahakan, soalnya lg buat project leveling bot
> 
> play yt udah fix bang?

As commit say, seperti nya sudah

**Comment by thoriqazzra** [comment]
> > > oke nt saya usahakan, soalnya lg buat project leveling bot
> > 
> > 
> > play yt udah fix bang?
> 
> As commit say, seperti nya sudah



> > > oke nt saya usahakan, soalnya lg buat project leveling bot
> > 
> > 
> > play yt udah fix bang?
> 
> As commit say, seperti nya sudah

cara fixed nya gmna bang? maaf banyak tanya. masih awam

**Comment by ArugaZ** [comment]
> > > > oke nt saya usahakan, soalnya lg buat project leveling bot
> > > 
> > > 
> > > play yt udah fix bang?
> > 
> > 
> > As commit say, seperti nya sudah
> 
> > > > oke nt saya usahakan, soalnya lg buat project leveling bot
> > > 
> > > 
> > > play yt udah fix bang?
> > 
> > 
> > As commit say, seperti nya sudah
> 
> cara fixed nya gmna bang? maaf banyak tanya. masih awam

coba clone ulang, soalnya saya gabisa langsung test ke bot, gada rdp/vps.. ni laptop bnyk problem :D

**Comment by andra12lol** [comment]
> oke nt saya usahakan, soalnya lg buat project leveling bot

lah xp gw dah 400+ malah dari ulang

**Comment by ArugaZ** [comment]
> > oke nt saya usahakan, soalnya lg buat project leveling bot
> 
> lah xp gw dah 400+ malah dari ulang

wkwk masih tester ngab
