### ISSUE TITLE
ketika memulai bot

### ISSUE THREAD

**Issue by strang445** [ArugaZ/whatsapp-bot#73]
![image](https://user-images.githubusercontent.com/69132413/99619204-ae261f80-2a01-11eb-9e46-4c600349dbb9.png)
sudah mencoba pada 3 teminal yang berbeda selalu menggantung di layar ini, saya mengetik node index.js dan tidak akan, saya mengetik npm start dan juga tidak akan

**Comment by mioscape** [comment]
> ![image](https://user-images.githubusercontent.com/69132413/99619204-ae261f80-2a01-11eb-9e46-4c600349dbb9.png)
> sudah mencoba pada 3 teminal yang berbeda selalu menggantung di layar ini, saya mengetik node index.js dan tidak akan, saya mengetik npm start dan juga tidak akan

Internet bagus?

**Comment by iksanriyanto** [comment]
> ![image](https://user-images.githubusercontent.com/69132413/99619204-ae261f80-2a01-11eb-9e46-4c600349dbb9.png)
> sudah mencoba pada 3 teminal yang berbeda selalu menggantung di layar ini, saya mengetik node index.js dan tidak akan, saya mengetik npm start dan juga tidak akan

Sambil buka chrome nya bro, ane prnah gitu dN work

**Comment by mioscape** [comment]
> ![image](https://user-images.githubusercontent.com/69132413/99619204-ae261f80-2a01-11eb-9e46-4c600349dbb9.png)
> sudah mencoba pada 3 teminal yang berbeda selalu menggantung di layar ini, saya mengetik node index.js dan tidak akan, saya mengetik npm start dan juga tidak akan

Itu vps kan? Kenapa nggak beli yang linux sekalian?

**Comment by dedekganteng** [comment]
itu biasanya stuck di chrome
coba install chrome nya dulu

**Comment by strang445** [comment]
> > ![image](https://user-images.githubusercontent.com/69132413/99619204-ae261f80-2a01-11eb-9e46-4c600349dbb9.png)
> > sudah mencoba pada 3 teminal yang berbeda selalu menggantung di layar ini, saya mengetik node index.js dan tidak akan, saya mengetik npm start dan juga tidak akan
> 
> Itu vps kan? Kenapa nggak beli yang linux sekalian?

Saya menggunakan linux tetapi komputer ini dan baru namun saya tidak menginstal
