### ISSUE TITLE
Keraguan

### ISSUE THREAD

**Issue by strang445** [ArugaZ/whatsapp-bot#79]
Saya orang Brazil dan saya suka bot, tapi saya ingin menandatangani paket simi-bot tapi saya tidak tahu cara mengubah bahasa simi, dapatkah seseorang membantu saya?

**Comment by NaldoMota1** [comment]
> Saya orang Brazil dan saya suka bot, tapi saya ingin menandatangani paket simi-bot tapi saya tidak tahu cara mengubah bahasa simi, dapatkah seseorang membantu saya?

Eu tbm sou Brasileiro mano,seria ótimo colocar em porttuguês.

**Comment by strang445** [comment]
> > Saya orang Brazil dan saya suka bot, tapi saya ingin menandatangani paket simi-bot tapi saya tidak tahu cara mengubah bahasa simi, dapatkah seseorang membantu saya?
> 
> Eu tbm sou Brasileiro mano,seria ótimo colocar em porttuguês.

Eu tentei procurar nas pastas e nos Scripts mas nada com referência a linguagem do bot simi ;-;

**Comment by idkmew** [comment]
Bro ad yg tau cara atasi Botny bekerja tapi ko lambat ya berjalanny di cmdny munculny lama, kadang di WA udh !help tapi di cmdny munculny lama, ad yg tau cara atasiny?

**Comment by strang445** [comment]
Saat dia lambat terus tekan enter

**Comment by ferlitopym** [comment]
> Bro ad yg tau cara atasi Botny bekerja tapi ko lambat ya berjalanny di cmdny munculny lama, kadang di WA udh !help tapi di cmdny munculny lama, ad yg tau cara atasiny?

Jaringanmu kali itu bro @idkmew

**Comment by ArugaZ** [comment]
> Saya orang Brazil dan saya suka bot, tapi saya ingin menandatangani paket simi-bot tapi saya tidak tahu cara mengubah bahasa simi, dapatkah seseorang membantu saya?

https://arugaz.herokuapp.com/api/simisimien?text=halo+simi&apikey=APIKEY here for english simi
