### ISSUE TITLE
Translate Problem

### ISSUE THREAD

**Issue by Fucksociety666** [ArugaZ/whatsapp-bot#85]
udh di reply tetep aja tulisnya kode bahasa salah UP

**Comment by ArugaZ** [comment]
> udh di reply tetep aja tulisnya kode bahasa salah UP

itu ngab dari lib nya

**Comment by Fucksociety666** [comment]
![Cuplikan layar dari 2020-11-24 23-04-52](https://user-images.githubusercontent.com/74858900/100119549-92ab9080-2ea9-11eb-82ba-87143266e6de.png)
??

**Comment by shansekai** [comment]
> ![Cuplikan layar dari 2020-11-24 23-04-52](https://user-images.githubusercontent.com/74858900/100119549-92ab9080-2ea9-11eb-82ba-87143266e6de.png)
> ??

Restart aja sampe bisa, aku jg gitu error terus ku restart bot beberapa kali bisa lg

**Comment by shansekai** [comment]
> > udh di reply tetep aja tulisnya kode bahasa salah UP
> 
> itu ngab dari lib nya

Req bang coba pkai lib lain aja:)

**Comment by ArugaZ** [comment]
> > > udh di reply tetep aja tulisnya kode bahasa salah UP
> > 
> > 
> > itu ngab dari lib nya
> 
> Req bang coba pkai lib lain aja:)

okehh
