### ISSUE TITLE
#ask (solved)

### ISSUE THREAD

**Issue by shansekai** [ArugaZ/whatsapp-bot#87]
Aku mau tanya, ini cara fixnya bagaimana?
![20201124_141037](https://user-images.githubusercontent.com/34540627/100060218-dd53eb00-2e5e-11eb-9ba1-57e4605374bb.jpg)

**Comment by akujeleksad** [comment]
w juga tpi pas di qrnya
nya

**Comment by ArugaZ** [comment]
itu pas bagian apa?
