### ISSUE TITLE
fitur

### ISSUE THREAD

**Issue by momoiko** [ArugaZ/whatsapp-bot#88]
tambahin tiktok downloader sma pinterest

**Comment by ArugaZ** [comment]
images itu pinterest ngab

**Comment by fawwaz37** [comment]
gimana biar support get.get('...').json() ?

**Comment by banguucup** [comment]
yt downloadernya kalo buat download kayak gini 
URL INI dahlah SUDAH PERNAH DI DOWNLOAD SEBELUMNYA ..URL AKAN RESET SETELAH 60 MENIT
Padah udah 1 jam lebih

**Comment by momoiko** [comment]
> images itu pinterest ngab

o iya ok sip ,gw gatau soalny wkwkwwk

**Comment by ArugaZ** [comment]
> yt downloadernya kalo buat download judul yg sama kayak gini. Padahal udah 1 jam lebih tetep kayak gitu
> URL INI dahlah SUDAH PERNAH DI DOWNLOAD SEBELUMNYA ..URL AKAN RESET SETELAH 60 MENIT

yg download pake link itu bnyk gan
