### ISSUE TITLE
tautan grup yang tidak diinginkan

### ISSUE THREAD

**Issue by NaldoMota1** [ArugaZ/whatsapp-bot#89]
Apakah Anda memiliki opsi untuk secara otomatis menghapus pengguna yang memutar tautan dalam grup.

**Comment by mioscape** [comment]
Fitur itu tidak akan ada di Whatsapp, karena admin grup saja tidak bisa menghapus pesan orang lain, kecuali menghapus pesan dia sendiri.

**Comment by mioscape** [comment]
Silahkan untuk menutup Issues ini, terimakasih.
