### ISSUE TITLE
fitur nekopoi

### ISSUE THREAD

**Issue by MrPawNO** [ArugaZ/whatsapp-bot#92]
Hallo gan, fitur #nekopoi nya segera diperbaiki dong

Fitur #instagram juga diperbaiki, malah keluar gambar 404 Not Found

Terimakasih

**Comment by ArugaZ** [comment]
nekopoi di ane bisa gan

**Comment by Ardans2003** [comment]
> Hallo gan, fitur #nekopoi nya segera diperbaiki dong
> 
> Fitur #instagram juga diperbaiki, malah keluar gambar 404 Not Found
> 
> Terimakasih

nekopoi : coba pakai vpn gan,soalnya di indonesia diblock situsnya

**Comment by ArugaZ** [comment]
nah eta, buat yang gapakai rdp/vps disarankan pakai VPN :D
