### ISSUE TITLE
Typo fix

### ISSUE THREAD

**Issue by andra12lol** [ArugaZ/whatsapp-bot#99]
dikarenakan gw gk tau cara pull request jadi pake issues aja deh :v [`Disini ganti jadi (setGroupToAdminsOnly)`](https://github.com/ArugaZ/whatsapp-bot/blob/master/HandleMsg.js#L1000) [`Disini ganti jadi (setGroupToAdminsOnly)`](https://github.com/ArugaZ/whatsapp-bot/blob/master/HandleMsg.js#L1002)

Jadi yg ad bacaan Edit dihapus aj soalnya gk bisa nge mute grup

**Comment by ArugaZ** [comment]
> dikarenakan gw gk tau cara pull request jadi pake issues aja deh :v [`Disini ganti jadi (setGroupToAdminsOnly)`](https://github.com/ArugaZ/whatsapp-bot/blob/master/HandleMsg.js#L1000) [`Disini ganti jadi (setGroupToAdminsOnly)`](https://github.com/ArugaZ/whatsapp-bot/blob/master/HandleMsg.js#L1002)
> 
> Jadi yg ad bacaan Edit dihapus aj soalnya gk bisa nge mute grup

thnk gan
